volumes:
  aidbox_pg_data: {}

services:
  aidbox_db:
    image: healthsamurai/aidboxdb:17
    volumes:
      - aidbox_pg_data:/var/lib/postgresql/data:delegated
    environment:
      POSTGRES_USER: aidbox
      POSTGRES_PORT: "5432"
      POSTGRES_DB: aidbox
      POSTGRES_PASSWORD: M3ya7uZxdJ

  aidbox:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    pull_policy: always
    image: healthsamurai/aidboxone:edge
    depends_on:
      - aidbox_db
    ports:
      - 8888:8888
    environment:
      BOX_ADMIN_PASSWORD: cwSgexVsRb
      BOX_BOOTSTRAP_FHIR_PACKAGES: hl7.fhir.r4.core#4.0.1
      BOX_COMPATIBILITY_VALIDATION_JSON__SCHEMA_REGEX: "#{:fhir-datetime}"
      BOX_DB_DATABASE: aidbox
      BOX_DB_HOST: aidbox_db
      BOX_DB_PASSWORD: M3ya7uZxdJ
      BOX_DB_PORT: "5432"
      BOX_DB_USER: aidbox
      BOX_FHIR_COMPLIANT_MODE: true
      BOX_FHIR_CORRECT_AIDBOX_FORMAT: true
      BOX_FHIR_CREATEDAT_URL: https://aidbox.app/ex/createdAt
      BOX_FHIR_SCHEMA_VALIDATION: true
      BOX_FHIR_SEARCH_AUTHORIZE_INLINE_REQUESTS: true
      BOX_FHIR_SEARCH_CHAIN_SUBSELECT: true
      BOX_FHIR_SEARCH_COMPARISONS: true
      BOX_FHIR_TERMINOLOGY_ENGINE: hybrid
      BOX_FHIR_TERMINOLOGY_ENGINE_HYBRID_EXTERNAL_TX_SERVER: https://tx.health-samurai.io/fhir
      BOX_FHIR_TERMINOLOGY_SERVICE_BASE_URL: https://tx.health-samurai.io/fhir
      BOX_INIT_BUNDLE: file:///app/init-bundle.json
      BOX_MODULE_SDC_STRICT_ACCESS_CONTROL: true
      BOX_ROOT_CLIENT_SECRET: BQuJmUG7N6
      BOX_SEARCH_INCLUDE_CONFORMANT: true
      BOX_SECURITY_AUDIT_LOG_ENABLED: true
      BOX_SECURITY_DEV_MODE: true
      BOX_SETTINGS_MODE: read-write
      BOX_WEB_BASE_URL: http://localhost:8888
      BOX_WEB_PORT: 8888
    volumes:
      - ./init-bundle.json:/app/init-bundle.json:ro
