// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Attachment } from "../hl7-fhir-r4-core/Attachment";
import type { CodeableConcept } from "../hl7-fhir-r4-core/CodeableConcept";
import type { DomainResource } from "../hl7-fhir-r4-core/DomainResource";
import type { Identifier } from "../hl7-fhir-r4-core/Identifier";
import type { Reference } from "../hl7-fhir-r4-core/Reference";

export type { Attachment } from "../hl7-fhir-r4-core/Attachment";
export type { CodeableConcept } from "../hl7-fhir-r4-core/CodeableConcept";
export type { Identifier } from "../hl7-fhir-r4-core/Identifier";
export type { Reference } from "../hl7-fhir-r4-core/Reference";

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/BodyStructure
export interface BodyStructure extends DomainResource {
    resourceType: "BodyStructure";

    active?: boolean;
    _active?: Element;
    description?: string;
    _description?: Element;
    identifier?: Identifier[];
    image?: Attachment[];
    location?: CodeableConcept;
    locationQualifier?: CodeableConcept[];
    morphology?: CodeableConcept;
    patient: Reference<"Patient">;
}
export const isBodyStructure = (resource: unknown): resource is BodyStructure => {
    return resource !== null && typeof resource === "object" && (resource as {resourceType: string}).resourceType === "BodyStructure";
}
