// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { BackboneElement } from "../hl7-fhir-r4-core/BackboneElement";
import type { CodeableConcept } from "../hl7-fhir-r4-core/CodeableConcept";
import type { DomainResource } from "../hl7-fhir-r4-core/DomainResource";
import type { Identifier } from "../hl7-fhir-r4-core/Identifier";
import type { Reference } from "../hl7-fhir-r4-core/Reference";

export type { BackboneElement } from "../hl7-fhir-r4-core/BackboneElement";
export type { CodeableConcept } from "../hl7-fhir-r4-core/CodeableConcept";
export type { Identifier } from "../hl7-fhir-r4-core/Identifier";
export type { Reference } from "../hl7-fhir-r4-core/Reference";

export interface DocumentManifestRelated extends BackboneElement {
    identifier?: Identifier;
    ref?: Reference<"Resource">;
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/DocumentManifest
export interface DocumentManifest extends DomainResource {
    resourceType: "DocumentManifest";

    author?: Reference<"Device" | "Organization" | "Patient" | "Practitioner" | "PractitionerRole" | "RelatedPerson">[];
    content: Reference<"Resource">[];
    created?: string;
    _created?: Element;
    description?: string;
    _description?: Element;
    identifier?: Identifier[];
    masterIdentifier?: Identifier;
    recipient?: Reference<"Organization" | "Patient" | "Practitioner" | "PractitionerRole" | "RelatedPerson">[];
    related?: DocumentManifestRelated[];
    source?: string;
    _source?: Element;
    status: ("current" | "superseded" | "entered-in-error");
    _status?: Element;
    subject?: Reference<"Device" | "Group" | "Patient" | "Practitioner">;
    type?: CodeableConcept;
}
export const isDocumentManifest = (resource: unknown): resource is DocumentManifest => {
    return resource !== null && typeof resource === "object" && (resource as {resourceType: string}).resourceType === "DocumentManifest";
}
