// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { BackboneElement } from "../hl7-fhir-r4-core/BackboneElement";
import type { CodeableConcept } from "../hl7-fhir-r4-core/CodeableConcept";
import type { Provenance } from "../hl7-fhir-r4-core/Provenance";
import type { ProvenanceAgent } from "../hl7-fhir-r4-core/Provenance";
import type { Reference } from "../hl7-fhir-r4-core/Reference";
import type { Signature } from "../hl7-fhir-r4-core/Signature";

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/ehrsrle-provenance
export interface EHRS_FM_Record_Lifecycle_Event___Provenance {
    __profileUrl: "http://hl7.org/fhir/StructureDefinition/ehrsrle-provenance";

    target: Reference<"Resource" /* 'Resource' */ >[];
    recorded: string;
    policy?: string[];
    location?: Reference<'Location'>;
    reason?: CodeableConcept[];
    activity?: CodeableConcept;
    agent: ProvenanceAgent[];
    signature?: Signature[];
}

export const attach_EHRS_FM_Record_Lifecycle_Event___Provenance_to_Provenance = (resource: Provenance, profile: EHRS_FM_Record_Lifecycle_Event___Provenance): Provenance => {
    return {
        ...resource,
        meta: {
            profile: ['http://hl7.org/fhir/StructureDefinition/ehrsrle-provenance']
        },
        target: profile.target,
        recorded: profile.recorded,
        policy: profile.policy,
        location: profile.location,
        reason: profile.reason,
        activity: profile.activity,
        agent: profile.agent,
        signature: profile.signature,
    }
}

export const extract_EHRS_FM_Record_Lifecycle_Event___Provenance_from_Provenance = (resource: Provenance): EHRS_FM_Record_Lifecycle_Event___Provenance => {
    return {
        __profileUrl: 'http://hl7.org/fhir/StructureDefinition/ehrsrle-provenance',
        target: resource.target,
        recorded: resource.recorded,
        policy: resource.policy,
        location: resource.location,
        reason: resource.reason,
        activity: resource.activity,
        agent: resource.agent,
        signature: resource.signature,
    }
}
