// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/FiveWs
export type FiveWs = object;
export const isFiveWs = (resource: unknown): resource is FiveWs => {
    return resource !== null && typeof resource === "object" && (resource as {resourceType: string}).resourceType === "FiveWs";
}
