// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { BackboneElement } from "../hl7-fhir-r4-core/BackboneElement";
import type { CodeableConcept } from "../hl7-fhir-r4-core/CodeableConcept";
import type { DomainResource } from "../hl7-fhir-r4-core/DomainResource";
import type { Identifier } from "../hl7-fhir-r4-core/Identifier";
import type { Reference } from "../hl7-fhir-r4-core/Reference";

export type { BackboneElement } from "../hl7-fhir-r4-core/BackboneElement";
export type { CodeableConcept } from "../hl7-fhir-r4-core/CodeableConcept";
export type { Identifier } from "../hl7-fhir-r4-core/Identifier";
export type { Reference } from "../hl7-fhir-r4-core/Reference";

export interface ImmunizationRecommendationRecommendation extends BackboneElement {
    contraindicatedVaccineCode?: CodeableConcept[];
    dateCriterion?: ImmunizationRecommendationRecommendationDateCriterion[];
    description?: string;
    doseNumberPositiveInt?: number;
    doseNumberString?: string;
    forecastReason?: CodeableConcept[];
    forecastStatus: CodeableConcept;
    series?: string;
    seriesDosesPositiveInt?: number;
    seriesDosesString?: string;
    supportingImmunization?: Reference<"Immunization" | "ImmunizationEvaluation">[];
    supportingPatientInformation?: Reference<"Resource">[];
    targetDisease?: CodeableConcept;
    vaccineCode?: CodeableConcept[];
}

export interface ImmunizationRecommendationRecommendationDateCriterion extends BackboneElement {
    code: CodeableConcept;
    value: string;
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/ImmunizationRecommendation
export interface ImmunizationRecommendation extends DomainResource {
    resourceType: "ImmunizationRecommendation";

    authority?: Reference<"Organization">;
    date: string;
    _date?: Element;
    identifier?: Identifier[];
    patient: Reference<"Patient">;
    recommendation: ImmunizationRecommendationRecommendation[];
}
export const isImmunizationRecommendation = (resource: unknown): resource is ImmunizationRecommendation => {
    return resource !== null && typeof resource === "object" && (resource as {resourceType: string}).resourceType === "ImmunizationRecommendation";
}
