// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { CodeableConcept } from "../hl7-fhir-r4-core/CodeableConcept";
import type { ContactDetail } from "../hl7-fhir-r4-core/ContactDetail";
import type { DomainResource } from "../hl7-fhir-r4-core/DomainResource";
import type { UsageContext } from "../hl7-fhir-r4-core/UsageContext";

export type { CodeableConcept } from "../hl7-fhir-r4-core/CodeableConcept";
export type { ContactDetail } from "../hl7-fhir-r4-core/ContactDetail";
export type { UsageContext } from "../hl7-fhir-r4-core/UsageContext";

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/MetadataResource
export interface MetadataResource extends DomainResource {
    resourceType: "MetadataResource";

    contact?: ContactDetail[];
    date?: string;
    description?: string;
    experimental?: boolean;
    jurisdiction?: CodeableConcept[];
    name?: string;
    publisher?: string;
    status: ("draft" | "active" | "retired" | "unknown");
    title?: string;
    url?: string;
    useContext?: UsageContext[];
    version?: string;
}
export const isMetadataResource = (resource: unknown): resource is MetadataResource => {
    return resource !== null && typeof resource === "object" && (resource as {resourceType: string}).resourceType === "MetadataResource";
}
