// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Annotation } from "../hl7-fhir-r4-core/Annotation";
import type { BackboneElement } from "../hl7-fhir-r4-core/BackboneElement";
import type { CodeableConcept } from "../hl7-fhir-r4-core/CodeableConcept";
import type { DataRequirement } from "../hl7-fhir-r4-core/DataRequirement";
import type { Duration } from "../hl7-fhir-r4-core/Duration";
import type { EvidenceVariable } from "../hl7-fhir-r4-core/EvidenceVariable";
import type { EvidenceVariableCharacteristic } from "../hl7-fhir-r4-core/EvidenceVariable";
import type { Expression } from "../hl7-fhir-r4-core/Expression";
import type { Identifier } from "../hl7-fhir-r4-core/Identifier";
import type { Period } from "../hl7-fhir-r4-core/Period";
import type { Reference } from "../hl7-fhir-r4-core/Reference";
import type { Timing } from "../hl7-fhir-r4-core/Timing";
import type { TriggerDefinition } from "../hl7-fhir-r4-core/TriggerDefinition";
import type { UsageContext } from "../hl7-fhir-r4-core/UsageContext";

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/picoelement
export interface PICO_Element_Profile {
    __profileUrl: "http://hl7.org/fhir/StructureDefinition/picoelement";

    identifier?: Identifier[];
    title?: string;
    shortTitle?: string;
    date?: string;
    description?: string;
    note?: Annotation[];
    type?: ("dichotomous" | "continuous" | "descriptive");
    characteristic: EvidenceVariableCharacteristic[];
}

export const attach_PICO_Element_Profile_to_EvidenceVariable = (resource: EvidenceVariable, profile: PICO_Element_Profile): EvidenceVariable => {
    return {
        ...resource,
        meta: {
            profile: ['http://hl7.org/fhir/StructureDefinition/picoelement']
        },
        identifier: profile.identifier,
        title: profile.title,
        shortTitle: profile.shortTitle,
        date: profile.date,
        description: profile.description,
        note: profile.note,
        type: profile.type,
        characteristic: profile.characteristic,
    }
}

export const extract_PICO_Element_Profile_from_EvidenceVariable = (resource: EvidenceVariable): PICO_Element_Profile => {
    return {
        __profileUrl: 'http://hl7.org/fhir/StructureDefinition/picoelement',
        identifier: resource.identifier,
        title: resource.title,
        shortTitle: resource.shortTitle,
        date: resource.date,
        description: resource.description,
        note: resource.note,
        type: resource.type,
        characteristic: resource.characteristic,
    }
}
