// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Address } from "../hl7-fhir-r4-core/Address";
import type { Attachment } from "../hl7-fhir-r4-core/Attachment";
import type { BackboneElement } from "../hl7-fhir-r4-core/BackboneElement";
import type { CodeableConcept } from "../hl7-fhir-r4-core/CodeableConcept";
import type { ContactPoint } from "../hl7-fhir-r4-core/ContactPoint";
import type { DomainResource } from "../hl7-fhir-r4-core/DomainResource";
import type { HumanName } from "../hl7-fhir-r4-core/HumanName";
import type { Identifier } from "../hl7-fhir-r4-core/Identifier";
import type { Period } from "../hl7-fhir-r4-core/Period";
import type { Reference } from "../hl7-fhir-r4-core/Reference";

export type { Address } from "../hl7-fhir-r4-core/Address";
export type { Attachment } from "../hl7-fhir-r4-core/Attachment";
export type { BackboneElement } from "../hl7-fhir-r4-core/BackboneElement";
export type { CodeableConcept } from "../hl7-fhir-r4-core/CodeableConcept";
export type { ContactPoint } from "../hl7-fhir-r4-core/ContactPoint";
export type { HumanName } from "../hl7-fhir-r4-core/HumanName";
export type { Identifier } from "../hl7-fhir-r4-core/Identifier";
export type { Period } from "../hl7-fhir-r4-core/Period";
export type { Reference } from "../hl7-fhir-r4-core/Reference";

export interface PractitionerQualification extends BackboneElement {
    code: CodeableConcept;
    identifier?: Identifier[];
    issuer?: Reference<"Organization">;
    period?: Period;
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/Practitioner
export interface Practitioner extends DomainResource {
    resourceType: "Practitioner";

    active?: boolean;
    _active?: Element;
    address?: Address[];
    birthDate?: string;
    _birthDate?: Element;
    communication?: CodeableConcept[];
    gender?: ("male" | "female" | "other" | "unknown");
    _gender?: Element;
    identifier?: Identifier[];
    name?: HumanName[];
    photo?: Attachment[];
    qualification?: PractitionerQualification[];
    telecom?: ContactPoint[];
}
export const isPractitioner = (resource: unknown): resource is Practitioner => {
    return resource !== null && typeof resource === "object" && (resource as {resourceType: string}).resourceType === "Practitioner";
}
