// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Attachment } from "../hl7-fhir-r4-core/Attachment";
import type { BackboneElement } from "../hl7-fhir-r4-core/BackboneElement";
import type { Coding } from "../hl7-fhir-r4-core/Coding";
import type { DomainResource } from "../hl7-fhir-r4-core/DomainResource";
import type { Identifier } from "../hl7-fhir-r4-core/Identifier";
import type { Quantity } from "../hl7-fhir-r4-core/Quantity";
import type { Reference } from "../hl7-fhir-r4-core/Reference";

export type { Attachment } from "../hl7-fhir-r4-core/Attachment";
export type { BackboneElement } from "../hl7-fhir-r4-core/BackboneElement";
export type { Coding } from "../hl7-fhir-r4-core/Coding";
export type { Identifier } from "../hl7-fhir-r4-core/Identifier";
export type { Quantity } from "../hl7-fhir-r4-core/Quantity";
export type { Reference } from "../hl7-fhir-r4-core/Reference";

export interface QuestionnaireResponseItem extends BackboneElement {
    answer?: QuestionnaireResponseItemAnswer[];
    definition?: string;
    item?: QuestionnaireResponseItem[];
    linkId: string;
    text?: string;
}

export interface QuestionnaireResponseItemAnswer extends BackboneElement {
    item?: QuestionnaireResponseItem[];
    valueAttachment?: Attachment;
    valueBoolean?: boolean;
    valueCoding?: Coding;
    valueDate?: string;
    valueDateTime?: string;
    valueDecimal?: number;
    valueInteger?: number;
    valueQuantity?: Quantity;
    valueReference?: Reference<"Resource">;
    valueString?: string;
    valueTime?: string;
    valueUri?: string;
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/QuestionnaireResponse
export interface QuestionnaireResponse extends DomainResource {
    resourceType: "QuestionnaireResponse";

    author?: Reference<"Device" | "Organization" | "Patient" | "Practitioner" | "PractitionerRole" | "RelatedPerson">;
    authored?: string;
    _authored?: Element;
    basedOn?: Reference<"CarePlan" | "ServiceRequest">[];
    encounter?: Reference<"Encounter">;
    identifier?: Identifier;
    item?: QuestionnaireResponseItem[];
    partOf?: Reference<"Observation" | "Procedure">[];
    questionnaire?: string;
    _questionnaire?: Element;
    source?: Reference<"Patient" | "Practitioner" | "PractitionerRole" | "RelatedPerson">;
    status: ("in-progress" | "completed" | "amended" | "entered-in-error" | "stopped");
    _status?: Element;
    subject?: Reference<"Resource">;
}
export const isQuestionnaireResponse = (resource: unknown): resource is QuestionnaireResponse => {
    return resource !== null && typeof resource === "object" && (resource as {resourceType: string}).resourceType === "QuestionnaireResponse";
}
