// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/Request
export type Request = object;
export const isRequest = (resource: unknown): resource is Request => {
    return resource !== null && typeof resource === "object" && (resource as {resourceType: string}).resourceType === "Request";
}
