// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Annotation } from "../hl7-fhir-r4-core/Annotation";
import type { CodeableConcept } from "../hl7-fhir-r4-core/CodeableConcept";
import type { DomainResource } from "../hl7-fhir-r4-core/DomainResource";
import type { Identifier } from "../hl7-fhir-r4-core/Identifier";
import type { Period } from "../hl7-fhir-r4-core/Period";
import type { Quantity } from "../hl7-fhir-r4-core/Quantity";
import type { Range } from "../hl7-fhir-r4-core/Range";
import type { Ratio } from "../hl7-fhir-r4-core/Ratio";
import type { Reference } from "../hl7-fhir-r4-core/Reference";
import type { Timing } from "../hl7-fhir-r4-core/Timing";

export type { Annotation } from "../hl7-fhir-r4-core/Annotation";
export type { CodeableConcept } from "../hl7-fhir-r4-core/CodeableConcept";
export type { Identifier } from "../hl7-fhir-r4-core/Identifier";
export type { Period } from "../hl7-fhir-r4-core/Period";
export type { Quantity } from "../hl7-fhir-r4-core/Quantity";
export type { Range } from "../hl7-fhir-r4-core/Range";
export type { Ratio } from "../hl7-fhir-r4-core/Ratio";
export type { Reference } from "../hl7-fhir-r4-core/Reference";
export type { Timing } from "../hl7-fhir-r4-core/Timing";

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/ServiceRequest
export interface ServiceRequest extends DomainResource {
    resourceType: "ServiceRequest";

    asNeededBoolean?: boolean;
    _asNeededBoolean?: Element;
    asNeededCodeableConcept?: CodeableConcept;
    authoredOn?: string;
    _authoredOn?: Element;
    basedOn?: Reference<"CarePlan" | "MedicationRequest" | "ServiceRequest">[];
    bodySite?: CodeableConcept[];
    category?: CodeableConcept[];
    code?: CodeableConcept;
    doNotPerform?: boolean;
    _doNotPerform?: Element;
    encounter?: Reference<"Encounter">;
    identifier?: Identifier[];
    instantiatesCanonical?: string[];
    _instantiatesCanonical?: Element;
    instantiatesUri?: string[];
    _instantiatesUri?: Element;
    insurance?: Reference<"ClaimResponse" | "Coverage">[];
    intent: ("proposal" | "plan" | "directive" | "order" | "original-order" | "reflex-order" | "filler-order" | "instance-order" | "option");
    _intent?: Element;
    locationCode?: CodeableConcept[];
    locationReference?: Reference<"Location">[];
    note?: Annotation[];
    occurrenceDateTime?: string;
    _occurrenceDateTime?: Element;
    occurrencePeriod?: Period;
    occurrenceTiming?: Timing;
    orderDetail?: CodeableConcept[];
    patientInstruction?: string;
    _patientInstruction?: Element;
    performer?: Reference<"CareTeam" | "Device" | "HealthcareService" | "Organization" | "Patient" | "Practitioner" | "PractitionerRole" | "RelatedPerson">[];
    performerType?: CodeableConcept;
    priority?: ("routine" | "urgent" | "asap" | "stat");
    _priority?: Element;
    quantityQuantity?: Quantity;
    quantityRange?: Range;
    quantityRatio?: Ratio;
    reasonCode?: CodeableConcept[];
    reasonReference?: Reference<"Condition" | "DiagnosticReport" | "DocumentReference" | "Observation">[];
    relevantHistory?: Reference<"Provenance">[];
    replaces?: Reference<"ServiceRequest">[];
    requester?: Reference<"Device" | "Organization" | "Patient" | "Practitioner" | "PractitionerRole" | "RelatedPerson">;
    requisition?: Identifier;
    specimen?: Reference<"Specimen">[];
    status: ("draft" | "active" | "on-hold" | "revoked" | "completed" | "entered-in-error" | "unknown");
    _status?: Element;
    subject: Reference<"Device" | "Group" | "Location" | "Patient">;
    supportingInfo?: Reference<"Resource">[];
}
export const isServiceRequest = (resource: unknown): resource is ServiceRequest => {
    return resource !== null && typeof resource === "object" && (resource as {resourceType: string}).resourceType === "ServiceRequest";
}
