// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { ActivityDefinition } from "../hl7-fhir-r4-core/ActivityDefinition";
import type { CodeableConcept } from "../hl7-fhir-r4-core/CodeableConcept";
import type { ContactDetail } from "../hl7-fhir-r4-core/ContactDetail";
import type { Identifier } from "../hl7-fhir-r4-core/Identifier";
import type { UsageContext } from "../hl7-fhir-r4-core/UsageContext";

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/shareableactivitydefinition
export interface Shareable_ActivityDefinition {
    __profileUrl: "http://hl7.org/fhir/StructureDefinition/shareableactivitydefinition";

    url: string;
    identifier?: Identifier[];
    version: string;
    name: string;
    title?: string;
    experimental: boolean;
    date?: string;
    publisher: string;
    contact?: ContactDetail[];
    description: string;
    useContext?: UsageContext[];
    jurisdiction?: CodeableConcept[];
}

export const attach_Shareable_ActivityDefinition_to_ActivityDefinition = (resource: ActivityDefinition, profile: Shareable_ActivityDefinition): ActivityDefinition => {
    return {
        ...resource,
        meta: {
            profile: ['http://hl7.org/fhir/StructureDefinition/shareableactivitydefinition']
        },
        url: profile.url,
        identifier: profile.identifier,
        version: profile.version,
        name: profile.name,
        title: profile.title,
        experimental: profile.experimental,
        date: profile.date,
        publisher: profile.publisher,
        contact: profile.contact,
        description: profile.description,
        useContext: profile.useContext,
        jurisdiction: profile.jurisdiction,
    }
}

export const extract_Shareable_ActivityDefinition_from_ActivityDefinition = (resource: ActivityDefinition): Shareable_ActivityDefinition => {
    if (resource.url === undefined) {
        throw new Error("'url' is required for http://hl7.org/fhir/StructureDefinition/shareableactivitydefinition");
    }
    if (resource.version === undefined) {
        throw new Error("'version' is required for http://hl7.org/fhir/StructureDefinition/shareableactivitydefinition");
    }
    if (resource.name === undefined) {
        throw new Error("'name' is required for http://hl7.org/fhir/StructureDefinition/shareableactivitydefinition");
    }
    if (resource.experimental === undefined) {
        throw new Error("'experimental' is required for http://hl7.org/fhir/StructureDefinition/shareableactivitydefinition");
    }
    if (resource.publisher === undefined) {
        throw new Error("'publisher' is required for http://hl7.org/fhir/StructureDefinition/shareableactivitydefinition");
    }
    if (resource.description === undefined) {
        throw new Error("'description' is required for http://hl7.org/fhir/StructureDefinition/shareableactivitydefinition");
    }
    return {
        __profileUrl: 'http://hl7.org/fhir/StructureDefinition/shareableactivitydefinition',
        url: resource.url,
        identifier: resource.identifier,
        version: resource.version,
        name: resource.name,
        title: resource.title,
        experimental: resource.experimental,
        date: resource.date,
        publisher: resource.publisher,
        contact: resource.contact,
        description: resource.description,
        useContext: resource.useContext,
        jurisdiction: resource.jurisdiction,
    }
}
