// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Attachment } from "../hl7-fhir-r4-core/Attachment";
import type { BackboneElement } from "../hl7-fhir-r4-core/BackboneElement";
import type { CodeableConcept } from "../hl7-fhir-r4-core/CodeableConcept";
import type { DomainResource } from "../hl7-fhir-r4-core/DomainResource";
import type { Identifier } from "../hl7-fhir-r4-core/Identifier";

export type { Attachment } from "../hl7-fhir-r4-core/Attachment";
export type { BackboneElement } from "../hl7-fhir-r4-core/BackboneElement";
export type { CodeableConcept } from "../hl7-fhir-r4-core/CodeableConcept";
export type { Identifier } from "../hl7-fhir-r4-core/Identifier";

export interface SubstanceProteinSubunit extends BackboneElement {
    cTerminalModification?: string;
    cTerminalModificationId?: Identifier;
    length?: number;
    nTerminalModification?: string;
    nTerminalModificationId?: Identifier;
    sequence?: string;
    sequenceAttachment?: Attachment;
    subunit?: number;
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/SubstanceProtein
export interface SubstanceProtein extends DomainResource {
    resourceType: "SubstanceProtein";

    disulfideLinkage?: string[];
    _disulfideLinkage?: Element;
    numberOfSubunits?: number;
    _numberOfSubunits?: Element;
    sequenceType?: CodeableConcept;
    subunit?: SubstanceProteinSubunit[];
}
export const isSubstanceProtein = (resource: unknown): resource is SubstanceProtein => {
    return resource !== null && typeof resource === "object" && (resource as {resourceType: string}).resourceType === "SubstanceProtein";
}
