// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { BackboneElement } from "../hl7-fhir-r4-core/BackboneElement";
import type { CodeableConcept } from "../hl7-fhir-r4-core/CodeableConcept";
import type { DomainResource } from "../hl7-fhir-r4-core/DomainResource";
import type { Identifier } from "../hl7-fhir-r4-core/Identifier";
import type { Period } from "../hl7-fhir-r4-core/Period";
import type { Quantity } from "../hl7-fhir-r4-core/Quantity";
import type { Reference } from "../hl7-fhir-r4-core/Reference";
import type { Timing } from "../hl7-fhir-r4-core/Timing";

export type { BackboneElement } from "../hl7-fhir-r4-core/BackboneElement";
export type { CodeableConcept } from "../hl7-fhir-r4-core/CodeableConcept";
export type { Identifier } from "../hl7-fhir-r4-core/Identifier";
export type { Period } from "../hl7-fhir-r4-core/Period";
export type { Quantity } from "../hl7-fhir-r4-core/Quantity";
export type { Reference } from "../hl7-fhir-r4-core/Reference";
export type { Timing } from "../hl7-fhir-r4-core/Timing";

export interface SupplyDeliverySuppliedItem extends BackboneElement {
    itemCodeableConcept?: CodeableConcept;
    itemReference?: Reference<"Device" | "Medication" | "Substance">;
    quantity?: Quantity;
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/SupplyDelivery
export interface SupplyDelivery extends DomainResource {
    resourceType: "SupplyDelivery";

    basedOn?: Reference<"SupplyRequest">[];
    destination?: Reference<"Location">;
    identifier?: Identifier[];
    occurrenceDateTime?: string;
    _occurrenceDateTime?: Element;
    occurrencePeriod?: Period;
    occurrenceTiming?: Timing;
    partOf?: Reference<"Contract" | "SupplyDelivery">[];
    patient?: Reference<"Patient">;
    receiver?: Reference<"Practitioner" | "PractitionerRole">[];
    status?: ("in-progress" | "completed" | "abandoned" | "entered-in-error");
    _status?: Element;
    suppliedItem?: SupplyDeliverySuppliedItem;
    supplier?: Reference<"Organization" | "Practitioner" | "PractitionerRole">;
    type?: CodeableConcept;
}
export const isSupplyDelivery = (resource: unknown): resource is SupplyDelivery => {
    return resource !== null && typeof resource === "object" && (resource as {resourceType: string}).resourceType === "SupplyDelivery";
}
