// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Extension } from "../../hl7-fhir-r4-core/Extension";
import type { Reference } from "../../hl7-fhir-r4-core/Reference";

import {
    buildResource,
    validateRequired,
    validateExcluded,
    validateFixedValue,
    validateSliceCardinality,
    validateEnum,
    validateReference,
    validateChoiceRequired,
    validateMustSupport,
} from "../../profile-helpers";

export type ExtensionUKCoreEvidenceProfileRaw = {
    valueReference: Reference;
}

// CanonicalURL: https://fhir.hl7.org.uk/StructureDefinition/Extension-UKCore-Evidence (pkg: fhir.r4.ukcore.stu2#2.0.2)
export class ExtensionUKCoreEvidenceProfile {
    static readonly canonicalUrl = "https://fhir.hl7.org.uk/StructureDefinition/Extension-UKCore-Evidence";

    private resource: Extension;

    constructor (resource: Extension) {
        this.resource = resource;
    }

    static from (resource: Extension) : ExtensionUKCoreEvidenceProfile {
        const profile = new ExtensionUKCoreEvidenceProfile(resource);
        const { errors } = profile.validate();
        if (errors.length > 0) throw new Error(errors.join("; "))
        return profile;
    }

    static apply (resource: Extension) : ExtensionUKCoreEvidenceProfile {
        return new ExtensionUKCoreEvidenceProfile(resource);
    }

    static createResource (args: ExtensionUKCoreEvidenceProfileRaw) : Extension {
        const resource = buildResource<Extension>( {
            url: "https://fhir.hl7.org.uk/StructureDefinition/Extension-UKCore-Evidence",
            valueReference: args.valueReference,
        })
        return resource;
    }

    static create (args: ExtensionUKCoreEvidenceProfileRaw) : ExtensionUKCoreEvidenceProfile {
        return ExtensionUKCoreEvidenceProfile.apply(ExtensionUKCoreEvidenceProfile.createResource(args));
    }

    toResource () : Extension {
        return this.resource;
    }

    // Field accessors
    getValueReference () : Reference | undefined {
        return this.resource.valueReference as Reference | undefined;
    }

    setValueReference (value: Reference) : this {
        Object.assign(this.resource, { valueReference: value });
        return this;
    }

    getUrl () : string | undefined {
        return this.resource.url as string | undefined;
    }

    setUrl (value: string) : this {
        Object.assign(this.resource, { url: value });
        return this;
    }

    // Extensions
    // Slices
    // Validation
    validate(): { errors: string[]; warnings: string[] } {
        const profileName = "ExtensionUKCoreEvidence"
        const res = this.resource
        return {
            errors: [
                ...validateRequired(res, profileName, "url"),
                ...validateFixedValue(res, profileName, "url", ExtensionUKCoreEvidenceProfile.canonicalUrl),
                ...validateChoiceRequired(res, profileName, ["valueReference"]),
            ],
            warnings: [],
        }
    }

}

