// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { CodeableConcept } from "../../hl7-fhir-r4-core/CodeableConcept";
import type { Extension } from "../../hl7-fhir-r4-core/Extension";

import {
    buildResource,
    isRawExtensionInput,
    isExtension,
    getExtensionValue,
    pushExtension,
    validateRequired,
    validateExcluded,
    validateFixedValue,
    validateSliceCardinality,
    validateEnum,
    validateReference,
    validateChoiceRequired,
    validateMustSupport,
} from "../../profile-helpers";

export type ExtensionUKCoreAddressKeyProfileRaw = {
    extension?: Extension[];
}

export type ExtensionUKCoreAddressKeyProfileFlat = {
    type: CodeableConcept;
    value: string;
}

// CanonicalURL: https://fhir.hl7.org.uk/StructureDefinition/Extension-UKCore-AddressKey (pkg: fhir.r4.ukcore.stu2#2.0.2)
export class ExtensionUKCoreAddressKeyProfile {
    static readonly canonicalUrl = "https://fhir.hl7.org.uk/StructureDefinition/Extension-UKCore-AddressKey";

    private resource: Extension;

    constructor (resource: Extension) {
        this.resource = resource;
    }

    static from (resource: Extension) : ExtensionUKCoreAddressKeyProfile {
        const profile = new ExtensionUKCoreAddressKeyProfile(resource);
        const { errors } = profile.validate();
        if (errors.length > 0) throw new Error(errors.join("; "))
        return profile;
    }

    static apply (resource: Extension) : ExtensionUKCoreAddressKeyProfile {
        return new ExtensionUKCoreAddressKeyProfile(resource);
    }

    private static resolveInput (args: ExtensionUKCoreAddressKeyProfileRaw | ExtensionUKCoreAddressKeyProfileFlat) : Extension[] {
        if (isRawExtensionInput<ExtensionUKCoreAddressKeyProfileRaw>(args)) {
            return args.extension ?? [];
        } else {
            const result: Extension[] = [];
            if (args.type !== undefined) {
                result.push({ url: "type", valueCodeableConcept: args.type } as Extension);
            }
            if (args.value !== undefined) {
                result.push({ url: "value", valueString: args.value } as Extension);
            }
            return result;
        }
    }

    static createResource (args?: ExtensionUKCoreAddressKeyProfileRaw | ExtensionUKCoreAddressKeyProfileFlat) : Extension {
        const resolvedExtensions = ExtensionUKCoreAddressKeyProfile.resolveInput(args ?? {});

        const resource = buildResource<Extension>( {
            url: "https://fhir.hl7.org.uk/StructureDefinition/Extension-UKCore-AddressKey",
            extension: resolvedExtensions,
        })
        return resource;
    }

    static create (args?: ExtensionUKCoreAddressKeyProfileRaw | ExtensionUKCoreAddressKeyProfileFlat) : ExtensionUKCoreAddressKeyProfile {
        return ExtensionUKCoreAddressKeyProfile.apply(ExtensionUKCoreAddressKeyProfile.createResource(args));
    }

    toResource () : Extension {
        return this.resource;
    }

    // Field accessors
    getUrl () : string | undefined {
        return this.resource.url as string | undefined;
    }

    setUrl (value: string) : this {
        Object.assign(this.resource, { url: value });
        return this;
    }

    // Extensions
    public setType (value: CodeableConcept): this {
        pushExtension(this.resource, { url: "type", valueCodeableConcept: value } as Extension)
        return this
    }

    public getType(mode: 'flat'): CodeableConcept | undefined;
    public getType(mode: 'raw'): Extension | undefined;
    public getType(): CodeableConcept | undefined;
    public getType (mode: 'flat' | 'raw' = 'flat'): CodeableConcept | Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "type")
        if (!ext) return undefined
        if (mode === 'raw') return ext
        return getExtensionValue<CodeableConcept>(ext, "valueCodeableConcept")
    }

    public setValue (value: string): this {
        pushExtension(this.resource, { url: "value", valueString: value } as Extension)
        return this
    }

    public getValue(mode: 'flat'): string | undefined;
    public getValue(mode: 'raw'): Extension | undefined;
    public getValue(): string | undefined;
    public getValue (mode: 'flat' | 'raw' = 'flat'): string | Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "value")
        if (!ext) return undefined
        if (mode === 'raw') return ext
        return getExtensionValue<string>(ext, "valueString")
    }

    // Slices
    // Validation
    validate(): { errors: string[]; warnings: string[] } {
        const profileName = "ExtensionUKCoreAddressKey"
        const res = this.resource
        return {
            errors: [
                ...validateRequired(res, profileName, "url"),
                ...validateFixedValue(res, profileName, "url", ExtensionUKCoreAddressKeyProfile.canonicalUrl),
            ],
            warnings: [],
        }
    }

}

