// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { CodeableConcept } from "../../hl7-fhir-r4-core/CodeableConcept";
import type { Extension } from "../../hl7-fhir-r4-core/Extension";

import {
    buildResource,
    validateRequired,
    validateExcluded,
    validateFixedValue,
    validateSliceCardinality,
    validateEnum,
    validateReference,
    validateChoiceRequired,
    validateMustSupport,
} from "../../profile-helpers";

export type ExtensionUKCoreNHSNumberUnavailableReasonProfileRaw = {
    valueCodeableConcept: CodeableConcept;
}

// CanonicalURL: https://fhir.hl7.org.uk/StructureDefinition/Extension-UKCore-NHSNumberUnavailableReason (pkg: fhir.r4.ukcore.stu2#2.0.2)
export class ExtensionUKCoreNHSNumberUnavailableReasonProfile {
    static readonly canonicalUrl = "https://fhir.hl7.org.uk/StructureDefinition/Extension-UKCore-NHSNumberUnavailableReason";

    private resource: Extension;

    constructor (resource: Extension) {
        this.resource = resource;
    }

    static from (resource: Extension) : ExtensionUKCoreNHSNumberUnavailableReasonProfile {
        const profile = new ExtensionUKCoreNHSNumberUnavailableReasonProfile(resource);
        const { errors } = profile.validate();
        if (errors.length > 0) throw new Error(errors.join("; "))
        return profile;
    }

    static apply (resource: Extension) : ExtensionUKCoreNHSNumberUnavailableReasonProfile {
        return new ExtensionUKCoreNHSNumberUnavailableReasonProfile(resource);
    }

    static createResource (args: ExtensionUKCoreNHSNumberUnavailableReasonProfileRaw) : Extension {
        const resource = buildResource<Extension>( {
            url: "https://fhir.hl7.org.uk/StructureDefinition/Extension-UKCore-NHSNumberUnavailableReason",
            valueCodeableConcept: args.valueCodeableConcept,
        })
        return resource;
    }

    static create (args: ExtensionUKCoreNHSNumberUnavailableReasonProfileRaw) : ExtensionUKCoreNHSNumberUnavailableReasonProfile {
        return ExtensionUKCoreNHSNumberUnavailableReasonProfile.apply(ExtensionUKCoreNHSNumberUnavailableReasonProfile.createResource(args));
    }

    toResource () : Extension {
        return this.resource;
    }

    // Field accessors
    getValueCodeableConcept () : CodeableConcept | undefined {
        return this.resource.valueCodeableConcept as CodeableConcept | undefined;
    }

    setValueCodeableConcept (value: CodeableConcept) : this {
        Object.assign(this.resource, { valueCodeableConcept: value });
        return this;
    }

    getUrl () : string | undefined {
        return this.resource.url as string | undefined;
    }

    setUrl (value: string) : this {
        Object.assign(this.resource, { url: value });
        return this;
    }

    // Extensions
    // Slices
    // Validation
    validate(): { errors: string[]; warnings: string[] } {
        const profileName = "ExtensionUKCoreNHSNumberUnavailableReason"
        const res = this.resource
        return {
            errors: [
                ...validateRequired(res, profileName, "url"),
                ...validateFixedValue(res, profileName, "url", ExtensionUKCoreNHSNumberUnavailableReasonProfile.canonicalUrl),
                ...validateChoiceRequired(res, profileName, ["valueCodeableConcept"]),
            ],
            warnings: [],
        }
    }

}

