// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Identifier } from "../../hl7-fhir-r4-core/Identifier";
import type { Location } from "../../hl7-fhir-r4-core/Location";

// CanonicalURL: https://fhir.hl7.org.uk/StructureDefinition/UKCore-Location
export type UKCoreLocation_Identifier_OdsSiteCodeSliceInput = Omit<Identifier, "system">;

import { applySliceMatch, matchesSlice, extractSliceSimplified } from "../../profile-helpers";

export class UKCoreLocationProfile {
    private resource: Location

    constructor (resource: Location) {
        this.resource = resource
    }

    toResource () : Location {
        return this.resource
    }

    public setOdsSiteCode (input?: UKCoreLocation_Identifier_OdsSiteCodeSliceInput): this {
        const match = {"system":"https://fhir.nhs.uk/Id/ods-site-code"} as Record<string, unknown>
        const value = applySliceMatch((input ?? {}) as Record<string, unknown>, match) as unknown as Identifier
        const list = (this.resource.identifier ??= [])
        const index = list.findIndex((item) => matchesSlice(item, match))
        if (index === -1) {
            list.push(value)
        } else {
            list[index] = value
        }
        return this
    }

    public getOdsSiteCode (): UKCoreLocation_Identifier_OdsSiteCodeSliceInput | undefined {
        const match = {"system":"https://fhir.nhs.uk/Id/ods-site-code"} as Record<string, unknown>
        const list = this.resource.identifier
        if (!list) return undefined
        const item = list.find((item) => matchesSlice(item, match))
        if (!item) return undefined
        return extractSliceSimplified(item as unknown as Record<string, unknown>, ["system"]) as UKCoreLocation_Identifier_OdsSiteCodeSliceInput
    }

    public getOdsSiteCodeRaw (): Identifier | undefined {
        const match = {"system":"https://fhir.nhs.uk/Id/ods-site-code"} as Record<string, unknown>
        const list = this.resource.identifier
        if (!list) return undefined
        const item = list.find((item) => matchesSlice(item, match))
        return item
    }

}

