// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { CodeableConcept } from "../../hl7-fhir-r4-core/CodeableConcept";
import type { Extension } from "../../hl7-fhir-r4-core/Extension";
import type { FamilyMemberHistory } from "../../hl7-fhir-r4-core/FamilyMemberHistory";
import type { Reference } from "../../hl7-fhir-r4-core/Reference";

// CanonicalURL: https://fhir.hl7.org.uk/StructureDefinition/UKCore-FamilyMemberHistory
export type UKCoreFamilyMemberHistory_ParticipantR5Input = {
    function?: CodeableConcept;
    actor: Reference;
}

import { extractComplexExtension } from "../../profile-helpers";

export class UKCoreFamilyMemberHistoryProfile {
    private resource: FamilyMemberHistory

    constructor (resource: FamilyMemberHistory) {
        this.resource = resource
    }

    toResource () : FamilyMemberHistory {
        return this.resource
    }

    public setAssociatedEncounter (value: Reference): this {
        const list = (this.resource.extension ??= [])
        list.push({ url: "https://fhir.hl7.org.uk/StructureDefinition/Extension-UKCore-AssociatedEncounter", valueReference: value })
        return this
    }

    public setParticipantR5 (input: UKCoreFamilyMemberHistory_ParticipantR5Input): this {
        const subExtensions: Extension[] = []
        if (input.function !== undefined) {
            subExtensions.push({ url: "function", valueCodeableConcept: input.function })
        }
        if (input.actor !== undefined) {
            subExtensions.push({ url: "actor", valueReference: input.actor })
        }
        const list = (this.resource.extension ??= [])
        list.push({ url: "http://hl7.org/fhir/5.0/StructureDefinition/extension-FamilyMemberHistory.participant", extension: subExtensions })
        return this
    }

    public getAssociatedEncounter (): Reference | undefined {
        const ext = this.resource.extension?.find(e => e.url === "https://fhir.hl7.org.uk/StructureDefinition/Extension-UKCore-AssociatedEncounter")
        return ext?.valueReference
    }

    public getAssociatedEncounterExtension (): Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "https://fhir.hl7.org.uk/StructureDefinition/Extension-UKCore-AssociatedEncounter")
        return ext
    }

    public getParticipantR5 (): UKCoreFamilyMemberHistory_ParticipantR5Input | undefined {
        const ext = this.resource.extension?.find(e => e.url === "http://hl7.org/fhir/5.0/StructureDefinition/extension-FamilyMemberHistory.participant")
        if (!ext) return undefined
        const config = [{ name: "function", valueField: "valueCodeableConcept", isArray: false }, { name: "actor", valueField: "valueReference", isArray: false }]
        return extractComplexExtension(ext as unknown as { extension?: Array<{ url?: string; [key: string]: unknown }> }, config) as UKCoreFamilyMemberHistory_ParticipantR5Input
    }

    public getParticipantR5Extension (): Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "http://hl7.org/fhir/5.0/StructureDefinition/extension-FamilyMemberHistory.participant")
        return ext
    }

}

