// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Extension } from "../../hl7-fhir-r4-core/Extension";
import type { Observation } from "../../hl7-fhir-r4-core/Observation";
import type { Reference } from "../../hl7-fhir-r4-core/Reference";

// CanonicalURL: https://fhir.hl7.org.uk/StructureDefinition/UKCore-Observation
export type UKCoreObservation_TriggeredByR5Input = {
    observation: Reference;
    type: string;
    reason?: string;
}

import { extractComplexExtension } from "../../profile-helpers";

export class UKCoreObservationProfile {
    private resource: Observation

    constructor (resource: Observation) {
        this.resource = resource
    }

    toResource () : Observation {
        return this.resource
    }

    public setTriggeredByR5 (input: UKCoreObservation_TriggeredByR5Input): this {
        const subExtensions: Extension[] = []
        if (input.observation !== undefined) {
            subExtensions.push({ url: "observation", valueReference: input.observation })
        }
        if (input.type !== undefined) {
            subExtensions.push({ url: "type", valueCode: input.type })
        }
        if (input.reason !== undefined) {
            subExtensions.push({ url: "reason", valueString: input.reason })
        }
        const list = (this.resource.extension ??= [])
        list.push({ url: "http://hl7.org/fhir/5.0/StructureDefinition/extension-Observation.triggeredBy", extension: subExtensions })
        return this
    }

    public setBodyStructureR5 (value: Reference): this {
        const list = (this.resource.extension ??= [])
        list.push({ url: "http://hl7.org/fhir/5.0/StructureDefinition/extension-Observation.bodyStructure", valueReference: value })
        return this
    }

    public getTriggeredByR5 (): UKCoreObservation_TriggeredByR5Input | undefined {
        const ext = this.resource.extension?.find(e => e.url === "http://hl7.org/fhir/5.0/StructureDefinition/extension-Observation.triggeredBy")
        if (!ext) return undefined
        const config = [{ name: "observation", valueField: "valueReference", isArray: false }, { name: "type", valueField: "valueCode", isArray: false }, { name: "reason", valueField: "valueString", isArray: false }]
        return extractComplexExtension(ext as unknown as { extension?: Array<{ url?: string; [key: string]: unknown }> }, config) as UKCoreObservation_TriggeredByR5Input
    }

    public getTriggeredByR5Extension (): Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "http://hl7.org/fhir/5.0/StructureDefinition/extension-Observation.triggeredBy")
        return ext
    }

    public getBodyStructureR5 (): Reference | undefined {
        const ext = this.resource.extension?.find(e => e.url === "http://hl7.org/fhir/5.0/StructureDefinition/extension-Observation.bodyStructure")
        return ext?.valueReference
    }

    public getBodyStructureR5Extension (): Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "http://hl7.org/fhir/5.0/StructureDefinition/extension-Observation.bodyStructure")
        return ext
    }

}

