// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { PractitionerRole } from "../../hl7-fhir-r4-core/PractitionerRole";

// CanonicalURL: https://fhir.hl7.org.uk/StructureDefinition/UKCore-PractitionerRole
export class UKCorePractitionerRoleProfile {
    private resource: PractitionerRole

    constructor (resource: PractitionerRole) {
        this.resource = resource
    }

    toResource () : PractitionerRole {
        return this.resource
    }

}

