// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Schedule } from "../../hl7-fhir-r4-core/Schedule";

// CanonicalURL: https://fhir.hl7.org.uk/StructureDefinition/UKCore-Schedule
export class UKCoreScheduleProfile {
    private resource: Schedule

    constructor (resource: Schedule) {
        this.resource = resource
    }

    toResource () : Schedule {
        return this.resource
    }

}

