// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { CodeableConcept } from "../../hl7-fhir-r4-core/CodeableConcept";
import type { Extension } from "../../hl7-fhir-r4-core/Extension";
import type { MedicationStatement } from "../../hl7-fhir-r4-core/MedicationStatement";

// CanonicalURL: https://fhir.hl7.org.uk/StructureDefinition/UKCore-MedicationStatement
export class UKCoreMedicationStatementProfile {
    private resource: MedicationStatement

    constructor (resource: MedicationStatement) {
        this.resource = resource
    }

    toResource () : MedicationStatement {
        return this.resource
    }

    public setPharmacistVerifiedIndicator (value: boolean): this {
        const list = (this.resource.extension ??= [])
        list.push({ url: "https://fhir.hl7.org.uk/StructureDefinition/Extension-UKCore-PharmacistVerifiedIndicator", valueBoolean: value })
        return this
    }

    public setMedicationPrescribingOrganizationType (value: CodeableConcept): this {
        const list = (this.resource.extension ??= [])
        list.push({ url: "https://fhir.hl7.org.uk/StructureDefinition/Extension-UKCore-MedicationPrescribingOrganizationType", valueCodeableConcept: value })
        return this
    }

    public setMedicationStatementLastIssueDate (value: string): this {
        const list = (this.resource.extension ??= [])
        list.push({ url: "https://fhir.hl7.org.uk/StructureDefinition/Extension-UKCore-MedicationStatementLastIssueDate", valueDateTime: value })
        return this
    }

    public getPharmacistVerifiedIndicator (): boolean | undefined {
        const ext = this.resource.extension?.find(e => e.url === "https://fhir.hl7.org.uk/StructureDefinition/Extension-UKCore-PharmacistVerifiedIndicator")
        return ext?.valueBoolean
    }

    public getPharmacistVerifiedIndicatorExtension (): Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "https://fhir.hl7.org.uk/StructureDefinition/Extension-UKCore-PharmacistVerifiedIndicator")
        return ext
    }

    public getMedicationPrescribingOrganizationType (): CodeableConcept | undefined {
        const ext = this.resource.extension?.find(e => e.url === "https://fhir.hl7.org.uk/StructureDefinition/Extension-UKCore-MedicationPrescribingOrganizationType")
        return ext?.valueCodeableConcept
    }

    public getMedicationPrescribingOrganizationTypeExtension (): Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "https://fhir.hl7.org.uk/StructureDefinition/Extension-UKCore-MedicationPrescribingOrganizationType")
        return ext
    }

    public getMedicationStatementLastIssueDate (): string | undefined {
        const ext = this.resource.extension?.find(e => e.url === "https://fhir.hl7.org.uk/StructureDefinition/Extension-UKCore-MedicationStatementLastIssueDate")
        return ext?.valueDateTime
    }

    public getMedicationStatementLastIssueDateExtension (): Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "https://fhir.hl7.org.uk/StructureDefinition/Extension-UKCore-MedicationStatementLastIssueDate")
        return ext
    }

}

