// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Procedure } from "../../hl7-fhir-r4-core/Procedure";

// CanonicalURL: https://fhir.hl7.org.uk/StructureDefinition/UKCore-Procedure
export class UKCoreProcedureProfile {
    private resource: Procedure

    constructor (resource: Procedure) {
        this.resource = resource
    }

    toResource () : Procedure {
        return this.resource
    }

}

