// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { CodeableConcept } from "../../hl7-fhir-r4-core/CodeableConcept";
import type { Extension } from "../../hl7-fhir-r4-core/Extension";
import type { Reference } from "../../hl7-fhir-r4-core/Reference";
import type { Specimen } from "../../hl7-fhir-r4-core/Specimen";

// CanonicalURL: https://fhir.hl7.org.uk/StructureDefinition/UKCore-Specimen
import { getOrCreateObjectAtPath } from "../../profile-helpers";

export class UKCoreSpecimenProfile {
    private resource: Specimen

    constructor (resource: Specimen) {
        this.resource = resource
    }

    toResource () : Specimen {
        return this.resource
    }

    public setSampleCategory (value: CodeableConcept): this {
        const list = (this.resource.extension ??= [])
        list.push({ url: "https://fhir.hl7.org.uk/StructureDefinition/Extension-UKCore-SampleCategory", valueCodeableConcept: value })
        return this
    }

    public setSpecialHandling (value: CodeableConcept): this {
        const target = getOrCreateObjectAtPath(this.resource as unknown as Record<string, unknown>, ["collection"])
        if (!Array.isArray(target.extension)) target.extension = [] as Extension[]
        (target.extension as Extension[]).push({ url: "http://hl7.org/fhir/StructureDefinition/specimen-specialHandling", valueCodeableConcept: value })
        return this
    }

    public setBodySiteReference (value: Reference): this {
        const target = getOrCreateObjectAtPath(this.resource as unknown as Record<string, unknown>, ["collection","bodySite"])
        if (!Array.isArray(target.extension)) target.extension = [] as Extension[]
        (target.extension as Extension[]).push({ url: "https://fhir.hl7.org.uk/StructureDefinition/Extension-UKCore-BodySiteReference", valueReference: value })
        return this
    }

    public setCollectionCollectorR5 (value: Reference): this {
        const target = getOrCreateObjectAtPath(this.resource as unknown as Record<string, unknown>, ["collection","collector"])
        if (!Array.isArray(target.extension)) target.extension = [] as Extension[]
        (target.extension as Extension[]).push({ url: "http://hl7.org/fhir/5.0/StructureDefinition/extension-Specimen.collection.collector", valueReference: value })
        return this
    }

    public getSampleCategory (): CodeableConcept | undefined {
        const ext = this.resource.extension?.find(e => e.url === "https://fhir.hl7.org.uk/StructureDefinition/Extension-UKCore-SampleCategory")
        return ext?.valueCodeableConcept
    }

    public getSampleCategoryExtension (): Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "https://fhir.hl7.org.uk/StructureDefinition/Extension-UKCore-SampleCategory")
        return ext
    }

    public getSpecialHandling (): CodeableConcept | undefined {
        const target = getOrCreateObjectAtPath(this.resource as unknown as Record<string, unknown>, ["collection"])
        const ext = (target.extension as Extension[] | undefined)?.find(e => e.url === "http://hl7.org/fhir/StructureDefinition/specimen-specialHandling")
        return ext?.valueCodeableConcept
    }

    public getSpecialHandlingExtension (): Extension | undefined {
        const target = getOrCreateObjectAtPath(this.resource as unknown as Record<string, unknown>, ["collection"])
        const ext = (target.extension as Extension[] | undefined)?.find(e => e.url === "http://hl7.org/fhir/StructureDefinition/specimen-specialHandling")
        return ext
    }

    public getBodySiteReference (): Reference | undefined {
        const target = getOrCreateObjectAtPath(this.resource as unknown as Record<string, unknown>, ["collection","bodySite"])
        const ext = (target.extension as Extension[] | undefined)?.find(e => e.url === "https://fhir.hl7.org.uk/StructureDefinition/Extension-UKCore-BodySiteReference")
        return ext?.valueReference
    }

    public getBodySiteReferenceExtension (): Extension | undefined {
        const target = getOrCreateObjectAtPath(this.resource as unknown as Record<string, unknown>, ["collection","bodySite"])
        const ext = (target.extension as Extension[] | undefined)?.find(e => e.url === "https://fhir.hl7.org.uk/StructureDefinition/Extension-UKCore-BodySiteReference")
        return ext
    }

    public getCollectionCollectorR5 (): Reference | undefined {
        const target = getOrCreateObjectAtPath(this.resource as unknown as Record<string, unknown>, ["collection","collector"])
        const ext = (target.extension as Extension[] | undefined)?.find(e => e.url === "http://hl7.org/fhir/5.0/StructureDefinition/extension-Specimen.collection.collector")
        return ext?.valueReference
    }

    public getCollectionCollectorR5Extension (): Extension | undefined {
        const target = getOrCreateObjectAtPath(this.resource as unknown as Record<string, unknown>, ["collection","collector"])
        const ext = (target.extension as Extension[] | undefined)?.find(e => e.url === "http://hl7.org/fhir/5.0/StructureDefinition/extension-Specimen.collection.collector")
        return ext
    }

}

