// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { CodeableConcept } from "../../hl7-fhir-r4-core/CodeableConcept";
import type { Extension } from "../../hl7-fhir-r4-core/Extension";
import type { Immunization } from "../../hl7-fhir-r4-core/Immunization";

// CanonicalURL: https://fhir.hl7.org.uk/StructureDefinition/UKCore-Immunization
export class UKCoreImmunizationProfile {
    private resource: Immunization

    constructor (resource: Immunization) {
        this.resource = resource
    }

    toResource () : Immunization {
        return this.resource
    }

    public setParentPresent (value: boolean): this {
        const list = (this.resource.extension ??= [])
        list.push({ url: "https://fhir.hl7.org.uk/StructureDefinition/Extension-UKCore-ParentPresent", valueBoolean: value })
        return this
    }

    public setVaccinationProcedure (value: CodeableConcept): this {
        const list = (this.resource.extension ??= [])
        list.push({ url: "https://fhir.hl7.org.uk/StructureDefinition/Extension-UKCore-VaccinationProcedure", valueCodeableConcept: value })
        return this
    }

    public getParentPresent (): boolean | undefined {
        const ext = this.resource.extension?.find(e => e.url === "https://fhir.hl7.org.uk/StructureDefinition/Extension-UKCore-ParentPresent")
        return ext?.valueBoolean
    }

    public getParentPresentExtension (): Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "https://fhir.hl7.org.uk/StructureDefinition/Extension-UKCore-ParentPresent")
        return ext
    }

    public getVaccinationProcedure (): CodeableConcept | undefined {
        const ext = this.resource.extension?.find(e => e.url === "https://fhir.hl7.org.uk/StructureDefinition/Extension-UKCore-VaccinationProcedure")
        return ext?.valueCodeableConcept
    }

    public getVaccinationProcedureExtension (): Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "https://fhir.hl7.org.uk/StructureDefinition/Extension-UKCore-VaccinationProcedure")
        return ext
    }

}

