// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { MedicationAdministration } from "../../hl7-fhir-r4-core/MedicationAdministration";

// CanonicalURL: https://fhir.hl7.org.uk/StructureDefinition/UKCore-MedicationAdministration
export class UKCoreMedicationAdministrationProfile {
    private resource: MedicationAdministration

    constructor (resource: MedicationAdministration) {
        this.resource = resource
    }

    toResource () : MedicationAdministration {
        return this.resource
    }

}

