// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Annotation } from "../../hl7-fhir-r4-core/Annotation";
import type { CodeableConcept } from "../../hl7-fhir-r4-core/CodeableConcept";
import type { DiagnosticReport } from "../../hl7-fhir-r4-core/DiagnosticReport";
import type { Extension } from "../../hl7-fhir-r4-core/Extension";
import type { Reference } from "../../hl7-fhir-r4-core/Reference";

// CanonicalURL: https://fhir.hl7.org.uk/StructureDefinition/UKCore-DiagnosticReport-Lab
export interface UKCoreDiagnosticReportLab extends DiagnosticReport {
    category: CodeableConcept[];
    subject: Reference<"Patient">;
}

export type UKCoreDiagnosticReportLab_SupportingInfoR5Input = {
    type: CodeableConcept;
    reference: Reference;
}

export type UKCoreDiagnosticReportLab_Category_LaboratorySliceInput = Omit<CodeableConcept, "coding">;

import { applySliceMatch, matchesSlice, getOrCreateObjectAtPath, extractComplexExtension, extractSliceSimplified } from "../../profile-helpers";

export class UKCoreDiagnosticReportLabProfile {
    private resource: DiagnosticReport

    constructor (resource: DiagnosticReport) {
        this.resource = resource
    }

    toResource () : DiagnosticReport {
        return this.resource
    }

    toProfile () : UKCoreDiagnosticReportLab {
        return this.resource as UKCoreDiagnosticReportLab
    }

    public setCompositionReferenceR5 (value: Reference): this {
        const list = (this.resource.extension ??= [])
        list.push({ url: "http://hl7.org/fhir/5.0/StructureDefinition/extension-DiagnosticReport.composition", valueReference: value })
        return this
    }

    public setNoteR5 (value: Annotation): this {
        const list = (this.resource.extension ??= [])
        list.push({ url: "http://hl7.org/fhir/5.0/StructureDefinition/extension-DiagnosticReport.note", valueAnnotation: value })
        return this
    }

    public setSupportingInfoR5 (input: UKCoreDiagnosticReportLab_SupportingInfoR5Input): this {
        const subExtensions: Extension[] = []
        if (input.type !== undefined) {
            subExtensions.push({ url: "type", valueCodeableConcept: input.type })
        }
        if (input.reference !== undefined) {
            subExtensions.push({ url: "reference", valueReference: input.reference })
        }
        const list = (this.resource.extension ??= [])
        list.push({ url: "http://hl7.org/fhir/5.0/StructureDefinition/extension-DiagnosticReport.supportingInfo", extension: subExtensions })
        return this
    }

    public setExtensionPerformerDeviceReference (value: Reference): this {
        const target = getOrCreateObjectAtPath(this.resource as unknown as Record<string, unknown>, ["performer"])
        if (!Array.isArray(target.extension)) target.extension = [] as Extension[]
        (target.extension as Extension[]).push({ url: "https://fhir.hl7.org.uk/StructureDefinition/Extension-UKCore-DeviceReference", valueReference: value })
        return this
    }

    public setExtensionResultsInterpreterDeviceReference (value: Reference): this {
        const target = getOrCreateObjectAtPath(this.resource as unknown as Record<string, unknown>, ["resultsInterpreter"])
        if (!Array.isArray(target.extension)) target.extension = [] as Extension[]
        (target.extension as Extension[]).push({ url: "https://fhir.hl7.org.uk/StructureDefinition/Extension-UKCore-DeviceReference", valueReference: value })
        return this
    }

    public setLaboratory (input?: UKCoreDiagnosticReportLab_Category_LaboratorySliceInput): this {
        const match = {"coding":{"code":"LAB"}} as Record<string, unknown>
        const value = applySliceMatch((input ?? {}) as Record<string, unknown>, match) as unknown as CodeableConcept
        const list = (this.resource.category ??= [])
        const index = list.findIndex((item) => matchesSlice(item, match))
        if (index === -1) {
            list.push(value)
        } else {
            list[index] = value
        }
        return this
    }

    public getCompositionReferenceR5 (): Reference | undefined {
        const ext = this.resource.extension?.find(e => e.url === "http://hl7.org/fhir/5.0/StructureDefinition/extension-DiagnosticReport.composition")
        return ext?.valueReference
    }

    public getCompositionReferenceR5Extension (): Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "http://hl7.org/fhir/5.0/StructureDefinition/extension-DiagnosticReport.composition")
        return ext
    }

    public getNoteR5 (): Annotation | undefined {
        const ext = this.resource.extension?.find(e => e.url === "http://hl7.org/fhir/5.0/StructureDefinition/extension-DiagnosticReport.note")
        return ext?.valueAnnotation
    }

    public getNoteR5Extension (): Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "http://hl7.org/fhir/5.0/StructureDefinition/extension-DiagnosticReport.note")
        return ext
    }

    public getSupportingInfoR5 (): UKCoreDiagnosticReportLab_SupportingInfoR5Input | undefined {
        const ext = this.resource.extension?.find(e => e.url === "http://hl7.org/fhir/5.0/StructureDefinition/extension-DiagnosticReport.supportingInfo")
        if (!ext) return undefined
        const config = [{ name: "type", valueField: "valueCodeableConcept", isArray: false }, { name: "reference", valueField: "valueReference", isArray: false }]
        return extractComplexExtension(ext as unknown as { extension?: Array<{ url?: string; [key: string]: unknown }> }, config) as UKCoreDiagnosticReportLab_SupportingInfoR5Input
    }

    public getSupportingInfoR5Extension (): Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "http://hl7.org/fhir/5.0/StructureDefinition/extension-DiagnosticReport.supportingInfo")
        return ext
    }

    public getDeviceReference (): Reference | undefined {
        const target = getOrCreateObjectAtPath(this.resource as unknown as Record<string, unknown>, ["performer"])
        const ext = (target.extension as Extension[] | undefined)?.find(e => e.url === "https://fhir.hl7.org.uk/StructureDefinition/Extension-UKCore-DeviceReference")
        return ext?.valueReference
    }

    public getDeviceReferenceExtension (): Extension | undefined {
        const target = getOrCreateObjectAtPath(this.resource as unknown as Record<string, unknown>, ["performer"])
        const ext = (target.extension as Extension[] | undefined)?.find(e => e.url === "https://fhir.hl7.org.uk/StructureDefinition/Extension-UKCore-DeviceReference")
        return ext
    }

    public getLaboratory (): UKCoreDiagnosticReportLab_Category_LaboratorySliceInput | undefined {
        const match = {"coding":{"code":"LAB"}} as Record<string, unknown>
        const list = this.resource.category
        if (!list) return undefined
        const item = list.find((item) => matchesSlice(item, match))
        if (!item) return undefined
        return extractSliceSimplified(item as unknown as Record<string, unknown>, ["coding"]) as UKCoreDiagnosticReportLab_Category_LaboratorySliceInput
    }

    public getLaboratoryRaw (): CodeableConcept | undefined {
        const match = {"coding":{"code":"LAB"}} as Record<string, unknown>
        const list = this.resource.category
        if (!list) return undefined
        const item = list.find((item) => matchesSlice(item, match))
        return item
    }

}

