// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { CodeableConcept } from "../../hl7-fhir-r4-core/CodeableConcept";
import type { Condition } from "../../hl7-fhir-r4-core/Condition";
import type { Extension } from "../../hl7-fhir-r4-core/Extension";

// CanonicalURL: https://fhir.hl7.org.uk/StructureDefinition/UKCore-Condition
export class UKCoreConditionProfile {
    private resource: Condition

    constructor (resource: Condition) {
        this.resource = resource
    }

    toResource () : Condition {
        return this.resource
    }

    public setConditionEpisode (value: CodeableConcept): this {
        const list = (this.resource.extension ??= [])
        list.push({ url: "https://fhir.hl7.org.uk/StructureDefinition/Extension-UKCore-ConditionEpisode", valueCodeableConcept: value })
        return this
    }

    public getConditionEpisode (): CodeableConcept | undefined {
        const ext = this.resource.extension?.find(e => e.url === "https://fhir.hl7.org.uk/StructureDefinition/Extension-UKCore-ConditionEpisode")
        return ext?.valueCodeableConcept
    }

    public getConditionEpisodeExtension (): Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "https://fhir.hl7.org.uk/StructureDefinition/Extension-UKCore-ConditionEpisode")
        return ext
    }

}

