POST /fhir/SearchParameter
Content-Type: application/json
Accept: application/json

{
  "url": "http://example.org/fhir/SearchParameter/Account-coverage",
  "id": "Account-coverage",
  "base": [
    "Account"
  ],
  "expression": "Acccount.coverage.coverage",
  "name": "coverage",
  "status": "active",
  "type": "reference",
  "version": "1.0.0",
  "resourceType": "SearchParameter",
  "code": "coverage",
  "description": "All Coverages for a given Account"
}