POST /fhir/SearchParameter
Content-Type: application/json
Accept: application/json

{
  "url": "http://example.org/fhir/SearchParameter/Invoice-charge-item",
  "id": "Invoice-charge-item",
  "base": [
    "Invoice"
  ],
  "expression": "Invoice.lineItem.chargeItem.ofType(Reference)",
  "name": "charge-item",
  "status": "active",
  "type": "reference",
  "version": "1.0.0",
  "resourceType": "SearchParameter",
  "code": "charge-item",
  "description": "All ChargeItems for a given invoice"
}