POST /fhir/AidboxSubscriptionTopic
content-type: application/json
accept: application/json

{
  "resourceType": "AidboxSubscriptionTopic",
  "url": "http://example.org/FHIR/R5/SubscriptionTopic/Invoice-topic",
  "status": "active",
  "trigger": [
    {
      "resource": "Invoice",
      "supportedInteraction": ["create"]
    }
  ]
}