POST /fhir/AidboxTopicDestination
content-type: application/json
accept: application/json

{
  "resourceType": "AidboxTopicDestination",
  "meta": {
    "profile": [
      "http://aidbox.app/StructureDefinition/aidboxtopicdestination-webhook-at-least-once"
    ]
  },
  "kind": "webhook-at-least-once",
  "id": "hl7-v2-webhook-destination",
  "topic": "http://example.org/FHIR/R5/SubscriptionTopic/Invoice-topic",
  "parameter": [
    {
      "name": "endpoint",
      "valueUrl": "PUT_APP_ENDPOINT_URL_HERE/webhook"
    },
    {
      "name": "timeout",
      "valueUnsignedInt": 30
    },
    {
      "name": "maxMessagesInBatch",
      "valueUnsignedInt": 1
    },
    {
      "name": "header",
      "valueString": "User-Agent: Aidbox Server"
    },
    {
      "name": "header",
      "valueString": "Authorization: PUT_SECRET_HERE"
    }
  ]
}