// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { ContactDetail } from './ContactDetail';
import { Element } from './Element';

export interface Contributor extends Element {
    contact?: ContactDetail[];
    name: string;
    _name?: Element;
    type: 'author' | 'editor' | 'reviewer' | 'endorser';
    _type?: Element;
}

