// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { ContactPoint } from './ContactPoint';
import { Element } from './Element';

export interface ContactDetail extends Element {
    name?: string;
    _name?: Element;
    telecom?: ContactPoint[];
}

