// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { BackboneElement } from './BackboneElement';
import { CodeableConcept } from './CodeableConcept';
import { ContactDetail } from './ContactDetail';
import { DomainResource } from './DomainResource';
import { Expression } from './Expression';
import { Identifier } from './Identifier';
import { Period } from './Period';
import { Reference } from './Reference';
import { RelatedArtifact } from './RelatedArtifact';
import { UsageContext } from './UsageContext';


export interface MeasureGroup extends BackboneElement {
    code?: CodeableConcept;
    description?: string;
    population?: MeasureGroupPopulation[];
    stratifier?: MeasureGroupStratifier[];
}

export interface MeasureGroupPopulation extends BackboneElement {
    code?: CodeableConcept;
    criteria: Expression;
    description?: string;
}

export interface MeasureGroupStratifier extends BackboneElement {
    code?: CodeableConcept;
    component?: MeasureGroupStratifierComponent[];
    criteria?: Expression;
    description?: string;
}

export interface MeasureGroupStratifierComponent extends BackboneElement {
    code?: CodeableConcept;
    criteria: Expression;
    description?: string;
}

export interface MeasureSupplementalData extends BackboneElement {
    code?: CodeableConcept;
    criteria: Expression;
    description?: string;
    usage?: CodeableConcept[];
}

export interface Measure extends DomainResource {
    approvalDate?: string;
    _approvalDate?: Element;
    author?: ContactDetail[];
    clinicalRecommendationStatement?: string;
    _clinicalRecommendationStatement?: Element;
    compositeScoring?: CodeableConcept;
    contact?: ContactDetail[];
    copyright?: string;
    _copyright?: Element;
    date?: string;
    _date?: Element;
    definition?: string[];
    _definition?: Element;
    description?: string;
    _description?: Element;
    disclaimer?: string;
    _disclaimer?: Element;
    editor?: ContactDetail[];
    effectivePeriod?: Period;
    endorser?: ContactDetail[];
    experimental?: boolean;
    _experimental?: Element;
    group?: MeasureGroup[];
    guidance?: string;
    _guidance?: Element;
    identifier?: Identifier[];
    improvementNotation?: CodeableConcept;
    jurisdiction?: CodeableConcept[];
    lastReviewDate?: string;
    _lastReviewDate?: Element;
    library?: string[];
    _library?: Element;
    name?: string;
    _name?: Element;
    publisher?: string;
    _publisher?: Element;
    purpose?: string;
    _purpose?: Element;
    rateAggregation?: string;
    _rateAggregation?: Element;
    rationale?: string;
    _rationale?: Element;
    relatedArtifact?: RelatedArtifact[];
    reviewer?: ContactDetail[];
    riskAdjustment?: string;
    _riskAdjustment?: Element;
    scoring?: CodeableConcept;
    status: 'draft' | 'active' | 'retired' | 'unknown';
    _status?: Element;
    subjectCodeableConcept?: CodeableConcept;
    subjectReference?: Reference<'Group'>;
    subtitle?: string;
    _subtitle?: Element;
    supplementalData?: MeasureSupplementalData[];
    title?: string;
    _title?: Element;
    topic?: CodeableConcept[];
    type?: CodeableConcept[];
    url?: string;
    _url?: Element;
    usage?: string;
    _usage?: Element;
    useContext?: UsageContext[];
    version?: string;
    _version?: Element;
}

