// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { CodeableConcept } from './CodeableConcept';
import { ContactDetail } from './ContactDetail';
import { DomainResource } from './DomainResource';
import { UsageContext } from './UsageContext';

export interface MetadataResource extends DomainResource {
    contact?: ContactDetail[];
    date?: string;
    description?: string;
    experimental?: boolean;
    jurisdiction?: CodeableConcept[];
    name?: string;
    publisher?: string;
    status: 'draft' | 'active' | 'retired' | 'unknown';
    title?: string;
    url?: string;
    useContext?: UsageContext[];
    version?: string;
}

