export const mockPatients = [
  { key: '1', name: 'John Doe', age: 32, gender: 'Male', diagnosis: 'Hypertension', lastVisit: '2024-03-05' },
  { key: '2', name: 'Jane Smith', age: 28, gender: 'Female', diagnosis: 'Diabetes', lastVisit: '2024-02-25' },
  { key: '3', name: 'Mark Johnson', age: 45, gender: 'Male', diagnosis: 'Asthma', lastVisit: '2024-03-01' },
  { key: '4', name: 'Emily Brown', age: 36, gender: 'Female', diagnosis: 'Allergy', lastVisit: '2024-02-18' },
  { key: '5', name: 'Michael Wilson', age: 50, gender: 'Male', diagnosis: 'Heart Disease', lastVisit: '2024-01-20' },
  { key: '6', name: 'Sophia Martinez', age: 41, gender: 'Female', diagnosis: 'Migraine', lastVisit: '2024-02-10' },
  { key: '7', name: 'Daniel Taylor', age: 29, gender: 'Male', diagnosis: 'Back Pain', lastVisit: '2024-02-15' },
  { key: '8', name: 'Olivia Anderson', age: 33, gender: 'Female', diagnosis: 'Depression', lastVisit: '2024-03-02' },
  { key: '9', name: 'William Thomas', age: 55, gender: 'Male', diagnosis: 'Arthritis', lastVisit: '2024-01-30' },
  { key: '10', name: 'Ava Jackson', age: 27, gender: 'Female', diagnosis: 'Anxiety', lastVisit: '2024-03-03' },
  { key: '11', name: 'James White', age: 60, gender: 'Male', diagnosis: 'Parkinson’s Disease', lastVisit: '2024-02-05' },
  { key: '12', name: 'Mia Harris', age: 39, gender: 'Female', diagnosis: 'Hypertension', lastVisit: '2024-02-12' },
  { key: '13', name: 'Benjamin Martin', age: 48, gender: 'Male', diagnosis: 'Obesity', lastVisit: '2024-02-22' },
  { key: '14', name: 'Charlotte Thompson', age: 35, gender: 'Female', diagnosis: 'Hyperthyroidism', lastVisit: '2024-02-28' },
  { key: '15', name: 'Ethan Garcia', age: 31, gender: 'Male', diagnosis: 'Insomnia', lastVisit: '2024-03-04' },
  { key: '16', name: 'Amelia Martinez', age: 44, gender: 'Female', diagnosis: 'Diabetes', lastVisit: '2024-02-17' },
  { key: '17', name: 'Alexander Clark', age: 38, gender: 'Male', diagnosis: 'High Cholesterol', lastVisit: '2024-02-08' },
  { key: '18', name: 'Isabella Rodriguez', age: 30, gender: 'Female', diagnosis: 'Acid Reflux', lastVisit: '2024-03-06' },
  { key: '19', name: 'Mason Lewis', age: 26, gender: 'Male', diagnosis: 'Bronchitis', lastVisit: '2024-01-25' },
  { key: '20', name: 'Sophia Walker', age: 50, gender: 'Female', diagnosis: 'Stroke', lastVisit: '2024-02-14' }
]