# WARNING: This file is autogenerated by @atomic-ehr/codegen.
# GitHub: https://github.com/atomic-ehr/codegen
# Any manual changes made to this file may be overwritten.

from fhir_types.hl7_fhir_r4_core.base import (
    Address, Age, Annotation, Attachment, BackboneElement, CodeableConcept, Coding, ContactDetail, ContactPoint, \
    Contributor, Count, DataRequirement, Distance, Dosage, Duration, Element, Expression, Extension, HumanName, \
    Identifier, Meta, Money, Narrative, ParameterDefinition, Period, Quantity, Range, Ratio, Reference, RelatedArtifact, \
    SampledData, Signature, Timing, TriggerDefinition, UsageContext
)

from fhir_types.hl7_fhir_r4_core.bundle import (
    Bundle, BundleEntry, BundleEntryRequest, BundleEntryResponse, BundleEntrySearch, BundleLink
)
from fhir_types.hl7_fhir_r4_core.domain_resource import DomainResource
from fhir_types.hl7_fhir_r4_core.observation import (
    Observation, ObservationComponent, ObservationReferenceRange
)
from fhir_types.hl7_fhir_r4_core.patient import (
    Patient, PatientCommunication, PatientContact, PatientLink
)
from fhir_types.hl7_fhir_r4_core.resource import Resource

Address.model_rebuild()
Age.model_rebuild()
Annotation.model_rebuild()
Attachment.model_rebuild()
BackboneElement.model_rebuild()
Bundle.model_rebuild()
BundleEntry.model_rebuild()
BundleEntryRequest.model_rebuild()
BundleEntryResponse.model_rebuild()
BundleEntrySearch.model_rebuild()
BundleLink.model_rebuild()
CodeableConcept.model_rebuild()
Coding.model_rebuild()
ContactDetail.model_rebuild()
ContactPoint.model_rebuild()
Contributor.model_rebuild()
Count.model_rebuild()
DataRequirement.model_rebuild()
Distance.model_rebuild()
DomainResource.model_rebuild()
Dosage.model_rebuild()
Duration.model_rebuild()
Element.model_rebuild()
Expression.model_rebuild()
Extension.model_rebuild()
HumanName.model_rebuild()
Identifier.model_rebuild()
Meta.model_rebuild()
Money.model_rebuild()
Narrative.model_rebuild()
Observation.model_rebuild()
ObservationComponent.model_rebuild()
ObservationReferenceRange.model_rebuild()
ParameterDefinition.model_rebuild()
Patient.model_rebuild()
PatientCommunication.model_rebuild()
PatientContact.model_rebuild()
PatientLink.model_rebuild()
Period.model_rebuild()
Quantity.model_rebuild()
Range.model_rebuild()
Ratio.model_rebuild()
Reference.model_rebuild()
RelatedArtifact.model_rebuild()
Resource.model_rebuild()
SampledData.model_rebuild()
Signature.model_rebuild()
Timing.model_rebuild()
TriggerDefinition.model_rebuild()
UsageContext.model_rebuild()

import fhir_types.hl7_fhir_r4_core.profiles  # noqa: F401
