FROM node:20-slim

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update -y
RUN apt-get install -y rsync
RUN npm install -g corepack && corepack enable

WORKDIR /usr/src/app-cache

COPY package.json .
RUN pnpm install

WORKDIR /usr/src/app

EXPOSE 4000
