volumes:
  postgres_data: {}
services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.6
    volumes:
      - ./keycloak.json:/opt/keycloak/data/import/keycloak.json
      - ./oidc-script-based-protocol-mapper.jar:/opt/keycloak/providers/oidc-script-based-protocol-mapper.jar
    ports:
      - 8888:8888
    environment:
      KC_HTTP_PORT: 8888
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    command: start-dev --features="scripts" --import-realm
  postgres:
    image: postgres:18
    volumes:
      - postgres_data:/var/lib/postgresql/data:delegated
    command:
      - postgres
      - -c
      - shared_preload_libraries=pg_stat_statements
    environment:
      POSTGRES_USER: aidbox
      POSTGRES_PORT: "5432"
      POSTGRES_DB: aidbox
      POSTGRES_PASSWORD: FtUjm2H_vM
  aidbox:
    image: healthsamurai/aidboxone:edge
    pull_policy: always
    depends_on:
      - postgres
    ports:
      - 8080:8080
    volumes:
      - ./init-bundle.json:/tmp/init-bundle.json
    environment:
      BOX_ADMIN_PASSWORD: EZROoZ8j0U
      BOX_BOOTSTRAP_FHIR_PACKAGES: hl7.fhir.r4.core#4.0.1
      BOX_COMPATIBILITY_VALIDATION_JSON__SCHEMA_REGEX: "#{:fhir-datetime}"
      BOX_DB_DATABASE: aidbox
      BOX_DB_HOST: postgres
      BOX_DB_PASSWORD: FtUjm2H_vM
      BOX_DB_PORT: "5432"
      BOX_DB_USER: aidbox
      BOX_FHIR_BUNDLE_EXECUTION_VALIDATION_MODE: limited
      BOX_FHIR_COMPLIANT_MODE: true
      BOX_FHIR_CORRECT_AIDBOX_FORMAT: true
      BOX_FHIR_CREATEDAT_URL: https://aidbox.app/ex/createdAt
      BOX_FHIR_SCHEMA_VALIDATION: true
      BOX_FHIR_SEARCH_AUTHORIZE_INLINE_REQUESTS: true
      BOX_FHIR_SEARCH_CHAIN_SUBSELECT: true
      BOX_FHIR_SEARCH_COMPARISONS: true
      BOX_FHIR_TERMINOLOGY_ENGINE: hybrid
      BOX_FHIR_TERMINOLOGY_ENGINE_HYBRID_EXTERNAL_TX_SERVER: https://tx.health-samurai.io/fhir
      BOX_FHIR_TERMINOLOGY_SERVICE_BASE_URL: https://tx.health-samurai.io/fhir
      BOX_MODULE_SDC_STRICT_ACCESS_CONTROL: true
      BOX_ROOT_CLIENT_SECRET: 99OSnTureh
      BOX_RUNME_UUID: 6b1ea95b-36dd-4c94-8e87-983e5042c9ca
      BOX_SEARCH_INCLUDE_CONFORMANT: true
      BOX_SECURITY_AUDIT_LOG_ENABLED: true
      BOX_SECURITY_DEV_MODE: true
      BOX_SETTINGS_MODE: read-write
      BOX_WEB_BASE_URL: http://localhost:8080
      BOX_WEB_PORT: 8080
      BOX_INIT_BUNDLE: file:///tmp/init-bundle.json
    healthcheck:
      test: curl -f http://localhost:8080/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 90
      start_period: 30s
  bun-app:
    build: .
    ports:
      - 3000:3000
    environment:
      KEYCLOAK_URL: http://keycloak:8888
      KEYCLOAK_PUBLIC_URL: http://localhost:8888
      KEYCLOAK_REALM: master
      KEYCLOAK_CLIENT_ID: my-app
      KEYCLOAK_CLIENT_SECRET: BuBdhaiyKbk0Llb2YMRSF9LKyXjkASTP
      APP_URL: http://localhost:3000
      AIDBOX_FHIR_BASE: http://aidbox:8080/fhir
      APP_PORT: 3000
    depends_on:
      - keycloak
      - aidbox
