volumes:
  postgres_data: {}

services:
  postgres:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data:delegated
    command:
      - postgres
      - -c
      - shared_preload_libraries=pg_stat_statements
    environment:
      POSTGRES_USER: aidbox
      POSTGRES_PORT: '5432'
      POSTGRES_DB: aidbox
      POSTGRES_PASSWORD: hb1NnSed7w
  aidbox:
    image: healthsamurai/aidboxone:edge
    pull_policy: always
    depends_on:
      - postgres
    ports:
      - 8080:8080
    volumes:
      - ./init-bundle:/app/init-bundle:ro
    environment:
      BOX_ADMIN_PASSWORD: uN6jhgu8eo
      BOX_BOOTSTRAP_FHIR_PACKAGES: hl7.fhir.r4.core#4.0.1
      BOX_COMPATIBILITY_VALIDATION_JSON__SCHEMA_REGEX: '#{:fhir-datetime}'
      BOX_DB_DATABASE: aidbox
      BOX_DB_HOST: postgres
      BOX_DB_PASSWORD: hb1NnSed7w
      BOX_DB_PORT: '5432'
      BOX_DB_USER: aidbox
      BOX_FHIR_COMPLIANT_MODE: true
      BOX_FHIR_CORRECT_AIDBOX_FORMAT: true
      BOX_FHIR_CREATEDAT_URL: https://aidbox.app/ex/createdAt
      BOX_FHIR_SCHEMA_VALIDATION: true
      BOX_FHIR_SEARCH_AUTHORIZE_INLINE_REQUESTS: true
      BOX_FHIR_SEARCH_CHAIN_SUBSELECT: true
      BOX_FHIR_SEARCH_COMPARISONS: true
      BOX_FHIR_TERMINOLOGY_ENGINE: hybrid
      BOX_FHIR_TERMINOLOGY_ENGINE_HYBRID_EXTERNAL_TX_SERVER: https://tx.health-samurai.io/fhir
      BOX_FHIR_TERMINOLOGY_SERVICE_BASE_URL: https://tx.health-samurai.io/fhir
      BOX_MODULE_SDC_STRICT_ACCESS_CONTROL: true
      BOX_ROOT_CLIENT_SECRET: qNbQS6sw82
      BOX_RUNME_UUID: 7c429b2a-14af-4859-ae12-7e23e46be07d
      BOX_SEARCH_INCLUDE_CONFORMANT: true
      BOX_SECURITY_AUDIT_LOG_ENABLED: true
      BOX_SECURITY_DEV_MODE: true
      BOX_SETTINGS_MODE: read-write
      BOX_WEB_BASE_URL: http://localhost:8080
      BOX_WEB_PORT: 8080
      BOX_INIT_BUNDLE: file:///app/init-bundle/bundle.json
    healthcheck:
      test: curl -f http://localhost:8080/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 90
      start_period: 30s

  health-cards-app:
    build: .
    ports:
      - 3000:3000
    depends_on:
      aidbox:
        condition: service_healthy
    environment:
      # Server Configuration
      PORT: 3000
      NODE_ENV: production
      
      # Aidbox Configuration
      AIDBOX_BASE_URL: http://aidbox:8080/fhir
      AIDBOX_CLIENT_ID: health-cards-client
      AIDBOX_CLIENT_SECRET: secret
      
      # Health Cards Configuration
      HEALTH_CARDS_ISSUER: https://example.org/health-cards
      HEALTH_CARDS_KEY_PATH: ./keys/private-key.pem
    volumes:
      - ./keys:/app/keys:ro
