// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { Element } from './Element';
import { Period } from './Period';

export interface ContactPoint extends Element {
    period?: Period;
    rank?: number;
    _rank?: Element;
    system?: 'phone' | 'fax' | 'email' | 'pager' | 'url' | 'sms' | 'other';
    _system?: Element;
    use?: 'home' | 'work' | 'temp' | 'old' | 'mobile';
    _use?: Element;
    value?: string;
    _value?: Element;
}

