// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { Address } from './Address';
import { BackboneElement } from './BackboneElement';
import { CodeableConcept } from './CodeableConcept';
import { Coding } from './Coding';
import { ContactPoint } from './ContactPoint';
import { DomainResource } from './DomainResource';
import { Identifier } from './Identifier';
import { Reference } from './Reference';


export interface LocationHoursOfOperation extends BackboneElement {
    allDay?: boolean;
    closingTime?: string;
    daysOfWeek?: 'mon' | 'tue' | 'wed' | 'thu' | 'fri' | 'sat' | 'sun'[];
    openingTime?: string;
}

export interface LocationPosition extends BackboneElement {
    altitude?: number;
    latitude: number;
    longitude: number;
}

export interface Location extends DomainResource {
    address?: Address;
    alias?: string[];
    _alias?: Element;
    availabilityExceptions?: string;
    _availabilityExceptions?: Element;
    description?: string;
    _description?: Element;
    endpoint?: Reference<'Endpoint'>[];
    hoursOfOperation?: LocationHoursOfOperation[];
    identifier?: Identifier[];
    managingOrganization?: Reference<'Organization'>;
    mode?: 'instance' | 'kind';
    _mode?: Element;
    name?: string;
    _name?: Element;
    operationalStatus?: Coding;
    partOf?: Reference<'Location'>;
    physicalType?: CodeableConcept;
    position?: LocationPosition;
    status?: 'active' | 'suspended' | 'inactive';
    _status?: Element;
    telecom?: ContactPoint[];
    type?: CodeableConcept[];
}

