// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { BackboneElement } from './BackboneElement';
import { CodeableConcept } from './CodeableConcept';
import { DomainResource } from './DomainResource';
import { Population } from './Population';
import { Quantity } from './Quantity';
import { Reference } from './Reference';


export interface MedicinalProductIndicationOtherTherapy extends BackboneElement {
    medicationCodeableConcept?: CodeableConcept;
    medicationReference?: Reference<'Medication' | 'MedicinalProduct' | 'Substance' | 'SubstanceSpecification'>;
    therapyRelationshipType: CodeableConcept;
}

export interface MedicinalProductIndication extends DomainResource {
    comorbidity?: CodeableConcept[];
    diseaseStatus?: CodeableConcept;
    diseaseSymptomProcedure?: CodeableConcept;
    duration?: Quantity;
    intendedEffect?: CodeableConcept;
    otherTherapy?: MedicinalProductIndicationOtherTherapy[];
    population?: Population[];
    subject?: Reference<'Medication' | 'MedicinalProduct'>[];
    undesirableEffect?: Reference<'MedicinalProductUndesirableEffect'>[];
}

