// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { BackboneElement } from './BackboneElement';
import { CodeableConcept } from './CodeableConcept';
import { Range } from './Range';

export interface Population extends BackboneElement {
    ageCodeableConcept?: CodeableConcept;
    ageRange?: Range;
    gender?: CodeableConcept;
    physiologicalCondition?: CodeableConcept;
    race?: CodeableConcept;
}

