// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { Element } from './Element';

export interface Quantity extends Element {
    code?: string;
    _code?: Element;
    comparator?: '<' | '<=' | '>=' | '>';
    _comparator?: Element;
    system?: string;
    _system?: Element;
    unit?: string;
    _unit?: Element;
    value?: number;
    _value?: Element;
}

