/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const program: string;
const required: string;
const name: string;

export {
	program,
	required,
	name
};

export default {
	program,
	required,
	name
};
