/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const button: string;
const icon: string;
const container: string;

export {
	button,
	icon,
	container
};

export default {
	button,
	icon,
	container
};
