/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const wrapper: string;
const faded: string;
const button: string;
const placeholder: string;
const search: string;
const incompatible: string;
const shortcut: string;
const dropdown: string;

export {
	wrapper,
	faded,
	button,
	placeholder,
	search,
	incompatible,
	shortcut,
	dropdown
};

export default {
	wrapper,
	faded,
	button,
	placeholder,
	search,
	incompatible,
	shortcut,
	dropdown
};
