/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const header: string;
const search: string;
const name: string;
const args: string;
const arg: string;
const arrow: string;
const body: string;
const dropdown: string;
const button: string;

export {
	header,
	search,
	name,
	args,
	arg,
	arrow,
	body,
	dropdown,
	button
};

export default {
	header,
	search,
	name,
	args,
	arg,
	arrow,
	body,
	dropdown,
	button
};
