/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const container: string;
const extended: string;
const title: string;
const binding: string;
const define: string;

export {
	container,
	extended,
	title,
	binding,
	define
};

export default {
	container,
	extended,
	title,
	binding,
	define
};
