/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const button: string;
const wrapper: string;

export {
	button,
	wrapper
};

export default {
	button,
	wrapper
};
