/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const button: string;
const equals: string;
const empty: string;
const arrow: string;
const error: string;
const popover: string;

export {
	button,
	equals,
	empty,
	arrow,
	error,
	popover
};

export default {
	button,
	equals,
	empty,
	arrow,
	error,
	popover
};
