---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ips-app
  namespace: ips
  labels:
    service: ips-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ips-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ips-app
    spec:
      containers:
        - name: ips-app
          image: ghcr.io/aidbox/examples-ips-ig-cl:main
          imagePullPolicy: Always
          ports:
            - name: api
              containerPort: 4000
              protocol: TCP
          envFrom:
            - configMapRef:
                name: ips-app
            - secretRef:
                name: ips-app
      restartPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
---
apiVersion: v1
kind: Service
metadata:
  name: ips-app
  namespace: ips
  labels:
    service: ips-app
spec:
  ports:
    - name: ips-app
      protocol: TCP
      port: 4000
      targetPort: 4000
  selector:
    app.kubernetes.io/name: ips-app
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ips-app
  namespace: ips
data:
  AIDBOX_BASE_URL: http://aidbox-api.aidbox.svc:80
  APP_PORT: "4000"
  APP_URL: http://ips-app.ips.svc.cluster.local:4000
  APP_CALLBACK_URL: /aidbox
  APP_ID: ips-app
---
apiVersion: v1
kind: Secret
metadata:
  name: ips-app
  namespace: ips
data:
  AIDBOX_CLIENT_SECRET:
  AIDBOX_CLIENT_ID:
  APP_SECRET:
type: Opaque
