# WARNING: This file is autogenerated by @atomic-ehr/codegen.
# GitHub: https://github.com/atomic-ehr/codegen
# Any manual changes made to this file may be overwritten.

from __future__ import annotations

from typing import cast

from fhir_types.hl7_fhir_r4_core.base import Extension
from fhir_types.profile_helpers import (
    build_resource, validate_choice_required, validate_fixed_value, validate_required
)


class OwnPrefixExtension:
    """The prefix portion (e.g. voorvoegsel) of the family name that is derived from the person's own surname, as distinguished from any portion that is derived from the surname of the person's partner or spouse.

    CanonicalURL: http://hl7.org/fhir/StructureDefinition/humanname-own-prefix
    """

    canonical_url: str = "http://hl7.org/fhir/StructureDefinition/humanname-own-prefix"

    def __init__(self, resource: Extension) -> None:
        self._resource = resource

    @classmethod
    def from_resource(cls, resource: Extension) -> "OwnPrefixExtension":
        profile = cls(resource)
        result = profile.validate()
        if result["errors"]:
            raise ValueError("; ".join(result["errors"]))
        return profile

    @classmethod
    def apply(cls, resource: Extension) -> "OwnPrefixExtension":
        return cls(resource)

    @classmethod
    def create_resource(cls, *, valueString: str) -> Extension:
        return build_resource(Extension, url="http://hl7.org/fhir/StructureDefinition/humanname-own-prefix", valueString=valueString)

    @classmethod
    def create(cls, *, valueString: str) -> "OwnPrefixExtension":
        return cls.apply(cls.create_resource(valueString=valueString))

    def to_resource(self) -> Extension:
        return self._resource

    def get_value_string(self) -> str | None:
        return cast('str | None', getattr(self._resource, "valueString", None))

    def set_value_string(self, value: str) -> "OwnPrefixExtension":
        setattr(self._resource, "valueString", value)
        return self

    def get_url(self) -> str | None:
        return cast('str | None', getattr(self._resource, "url", None))

    def set_url(self, value: str) -> "OwnPrefixExtension":
        setattr(self._resource, "url", value)
        return self

    def validate(self) -> dict[str, list[str]]:
        profile_name = "OwnPrefixExtension"
        errors: list[str] = []
        warnings: list[str] = []
        errors.extend(validate_required(self._resource, profile_name, "url"))
        errors.extend(validate_fixed_value(self._resource, profile_name, "url", "http://hl7.org/fhir/StructureDefinition/humanname-own-prefix"))
        errors.extend(validate_choice_required(self._resource, profile_name, ["valueString"]))
        return {"errors": errors, "warnings": warnings}

