# WARNING: This file is autogenerated by @atomic-ehr/codegen.
# GitHub: https://github.com/atomic-ehr/codegen
# Any manual changes made to this file may be overwritten.

from __future__ import annotations

from typing import cast

from fhir_types.hl7_fhir_r4_core.base import Extension
from fhir_types.hl7_fhir_r4_core.base import Address
from fhir_types.profile_helpers import (
    build_resource, validate_choice_required, validate_fixed_value, validate_required
)


class BirthPlaceExtension:
    """The registered place of birth of the patient. A sytem may use the address.text if they don't store the birthPlace address in discrete elements.

    CanonicalURL: http://hl7.org/fhir/StructureDefinition/patient-birthPlace
    """

    canonical_url: str = "http://hl7.org/fhir/StructureDefinition/patient-birthPlace"

    def __init__(self, resource: Extension) -> None:
        self._resource = resource

    @classmethod
    def from_resource(cls, resource: Extension) -> "BirthPlaceExtension":
        profile = cls(resource)
        result = profile.validate()
        if result["errors"]:
            raise ValueError("; ".join(result["errors"]))
        return profile

    @classmethod
    def apply(cls, resource: Extension) -> "BirthPlaceExtension":
        return cls(resource)

    @classmethod
    def create_resource(cls, *, valueAddress: Address) -> Extension:
        return build_resource(Extension, url="http://hl7.org/fhir/StructureDefinition/patient-birthPlace", valueAddress=valueAddress)

    @classmethod
    def create(cls, *, valueAddress: Address) -> "BirthPlaceExtension":
        return cls.apply(cls.create_resource(valueAddress=valueAddress))

    def to_resource(self) -> Extension:
        return self._resource

    def get_value_address(self) -> Address | None:
        return cast('Address | None', getattr(self._resource, "valueAddress", None))

    def set_value_address(self, value: Address) -> "BirthPlaceExtension":
        setattr(self._resource, "valueAddress", value)
        return self

    def get_url(self) -> str | None:
        return cast('str | None', getattr(self._resource, "url", None))

    def set_url(self, value: str) -> "BirthPlaceExtension":
        setattr(self._resource, "url", value)
        return self

    def validate(self) -> dict[str, list[str]]:
        profile_name = "BirthPlaceExtension"
        errors: list[str] = []
        warnings: list[str] = []
        errors.extend(validate_required(self._resource, profile_name, "url"))
        errors.extend(validate_fixed_value(self._resource, profile_name, "url", "http://hl7.org/fhir/StructureDefinition/patient-birthPlace"))
        errors.extend(validate_choice_required(self._resource, profile_name, ["valueAddress"]))
        return {"errors": errors, "warnings": warnings}

