# WARNING: This file is autogenerated by @atomic-ehr/codegen.
# GitHub: https://github.com/atomic-ehr/codegen
# Any manual changes made to this file may be overwritten.

from __future__ import annotations

from typing import cast

from fhir_types.hl7_fhir_r4_core.base import Extension
from fhir_types.profile_helpers import (
    build_resource, validate_choice_required, validate_fixed_value, validate_required
)


class BirthTimeExtension:
    """The time of day that the Patient was born. This includes the date to ensure that the timezone information can be communicated effectively.

    CanonicalURL: http://hl7.org/fhir/StructureDefinition/patient-birthTime
    """

    canonical_url: str = "http://hl7.org/fhir/StructureDefinition/patient-birthTime"

    def __init__(self, resource: Extension) -> None:
        self._resource = resource

    @classmethod
    def from_resource(cls, resource: Extension) -> "BirthTimeExtension":
        profile = cls(resource)
        result = profile.validate()
        if result["errors"]:
            raise ValueError("; ".join(result["errors"]))
        return profile

    @classmethod
    def apply(cls, resource: Extension) -> "BirthTimeExtension":
        return cls(resource)

    @classmethod
    def create_resource(cls, *, valueDateTime: str) -> Extension:
        return build_resource(Extension, url="http://hl7.org/fhir/StructureDefinition/patient-birthTime", valueDateTime=valueDateTime)

    @classmethod
    def create(cls, *, valueDateTime: str) -> "BirthTimeExtension":
        return cls.apply(cls.create_resource(valueDateTime=valueDateTime))

    def to_resource(self) -> Extension:
        return self._resource

    def get_value_date_time(self) -> str | None:
        return cast('str | None', getattr(self._resource, "valueDateTime", None))

    def set_value_date_time(self, value: str) -> "BirthTimeExtension":
        setattr(self._resource, "valueDateTime", value)
        return self

    def get_url(self) -> str | None:
        return cast('str | None', getattr(self._resource, "url", None))

    def set_url(self, value: str) -> "BirthTimeExtension":
        setattr(self._resource, "url", value)
        return self

    def validate(self) -> dict[str, list[str]]:
        profile_name = "BirthTimeExtension"
        errors: list[str] = []
        warnings: list[str] = []
        errors.extend(validate_required(self._resource, profile_name, "url"))
        errors.extend(validate_fixed_value(self._resource, profile_name, "url", "http://hl7.org/fhir/StructureDefinition/patient-birthTime"))
        errors.extend(validate_choice_required(self._resource, profile_name, ["valueDateTime"]))
        return {"errors": errors, "warnings": warnings}

