// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { BackboneElement } from "../hl7-fhir-r4-core/BackboneElement";
import type { CodeableConcept } from "../hl7-fhir-r4-core/CodeableConcept";
import type { DomainResource } from "../hl7-fhir-r4-core/DomainResource";
import type { Identifier } from "../hl7-fhir-r4-core/Identifier";
import type { Period } from "../hl7-fhir-r4-core/Period";
import type { Reference } from "../hl7-fhir-r4-core/Reference";

import type { Element } from "../hl7-fhir-r4-core/Element";
export type { BackboneElement } from "../hl7-fhir-r4-core/BackboneElement";
export type { CodeableConcept } from "../hl7-fhir-r4-core/CodeableConcept";
export type { Identifier } from "../hl7-fhir-r4-core/Identifier";
export type { Period } from "../hl7-fhir-r4-core/Period";
export type { Reference } from "../hl7-fhir-r4-core/Reference";

export interface AppointmentParticipant extends BackboneElement {
    actor?: Reference<"Device" | "HealthcareService" | "Location" | "Patient" | "Practitioner" | "PractitionerRole" | "RelatedPerson">;
    period?: Period;
    required?: ("required" | "optional" | "information-only");
    status: ("accepted" | "declined" | "tentative" | "needs-action");
    type?: CodeableConcept[];
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/Appointment
export interface Appointment extends DomainResource {
    resourceType: "Appointment";

    appointmentType?: CodeableConcept;
    basedOn?: Reference<"ServiceRequest">[];
    cancelationReason?: CodeableConcept;
    comment?: string;
    _comment?: Element;
    created?: string;
    _created?: Element;
    description?: string;
    _description?: Element;
    end?: string;
    _end?: Element;
    identifier?: Identifier[];
    minutesDuration?: number;
    _minutesDuration?: Element;
    participant: AppointmentParticipant[];
    patientInstruction?: string;
    _patientInstruction?: Element;
    priority?: number;
    _priority?: Element;
    reasonCode?: CodeableConcept[];
    reasonReference?: Reference<"Condition" | "ImmunizationRecommendation" | "Observation" | "Procedure">[];
    requestedPeriod?: Period[];
    serviceCategory?: CodeableConcept[];
    serviceType?: CodeableConcept[];
    slot?: Reference<"Slot">[];
    specialty?: CodeableConcept[];
    start?: string;
    _start?: Element;
    status: ("proposed" | "pending" | "booked" | "arrived" | "fulfilled" | "cancelled" | "noshow" | "entered-in-error" | "checked-in" | "waitlist");
    _status?: Element;
    supportingInformation?: Reference<"Resource">[];
}
export const isAppointment = (resource: unknown): resource is Appointment => {
    return resource !== null && typeof resource === "object" && (resource as {resourceType: string}).resourceType === "Appointment";
}
