# WARNING: This file is autogenerated by @atomic-ehr/codegen.
# GitHub: https://github.com/atomic-ehr/codegen
# Any manual changes made to this file may be overwritten.

from __future__ import annotations
from pydantic import BaseModel, ConfigDict, Field, PositiveInt
from typing import Any, Generic, List as PyList, Literal
from typing_extensions import TypeVar

T = TypeVar('T', bound=str, default=str)


class Element(BaseModel):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    extension: PyList[Extension] | None = Field(None, alias="extension", serialization_alias="extension")
    id: str | None = Field(None, alias="id", serialization_alias="id")
    idExtension: Element | None = Field(None, alias="_id", serialization_alias="_id")


class Address(Element):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    city: str | None = Field(None, alias="city", serialization_alias="city")
    cityExtension: Element | None = Field(None, alias="_city", serialization_alias="_city")
    country: str | None = Field(None, alias="country", serialization_alias="country")
    countryExtension: Element | None = Field(None, alias="_country", serialization_alias="_country")
    district: str | None = Field(None, alias="district", serialization_alias="district")
    districtExtension: Element | None = Field(None, alias="_district", serialization_alias="_district")
    line: PyList[str] | None = Field(None, alias="line", serialization_alias="line")
    lineExtension: PyList[Element | None] | None = Field(None, alias="_line", serialization_alias="_line")
    period: Period | None = Field(None, alias="period", serialization_alias="period")
    postalCode: str | None = Field(None, alias="postalCode", serialization_alias="postalCode")
    postalCodeExtension: Element | None = Field(None, alias="_postalCode", serialization_alias="_postalCode")
    state: str | None = Field(None, alias="state", serialization_alias="state")
    stateExtension: Element | None = Field(None, alias="_state", serialization_alias="_state")
    text: str | None = Field(None, alias="text", serialization_alias="text")
    textExtension: Element | None = Field(None, alias="_text", serialization_alias="_text")
    type: Literal["postal", "physical", "both"] | None = Field(None, alias="type", serialization_alias="type")
    typeExtension: Element | None = Field(None, alias="_type", serialization_alias="_type")
    use: Literal["home", "work", "temp", "old", "billing"] | None = Field(None, alias="use", serialization_alias="use")
    useExtension: Element | None = Field(None, alias="_use", serialization_alias="_use")


class Quantity(Element):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    code: str | None = Field(None, alias="code", serialization_alias="code")
    codeExtension: Element | None = Field(None, alias="_code", serialization_alias="_code")
    comparator: Literal["<", "<=", ">=", ">"] | None = Field(None, alias="comparator", serialization_alias="comparator")
    comparatorExtension: Element | None = Field(None, alias="_comparator", serialization_alias="_comparator")
    system: str | None = Field(None, alias="system", serialization_alias="system")
    systemExtension: Element | None = Field(None, alias="_system", serialization_alias="_system")
    unit: str | None = Field(None, alias="unit", serialization_alias="unit")
    unitExtension: Element | None = Field(None, alias="_unit", serialization_alias="_unit")
    value: float | None = Field(None, alias="value", serialization_alias="value")
    valueExtension: Element | None = Field(None, alias="_value", serialization_alias="_value")


class Age(Quantity):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    pass


class Annotation(Element):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    authorReference: Reference | None = Field(None, alias="authorReference", serialization_alias="authorReference")
    authorString: str | None = Field(None, alias="authorString", serialization_alias="authorString")
    authorStringExtension: Element | None = Field(None, alias="_authorString", serialization_alias="_authorString")
    text: str = Field(alias="text", serialization_alias="text")
    textExtension: Element | None = Field(None, alias="_text", serialization_alias="_text")
    time: str | None = Field(None, alias="time", serialization_alias="time")
    timeExtension: Element | None = Field(None, alias="_time", serialization_alias="_time")


class Attachment(Element):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    contentType: str | None = Field(None, alias="contentType", serialization_alias="contentType")
    contentTypeExtension: Element | None = Field(None, alias="_contentType", serialization_alias="_contentType")
    creation: str | None = Field(None, alias="creation", serialization_alias="creation")
    creationExtension: Element | None = Field(None, alias="_creation", serialization_alias="_creation")
    data: str | None = Field(None, alias="data", serialization_alias="data")
    dataExtension: Element | None = Field(None, alias="_data", serialization_alias="_data")
    hash: str | None = Field(None, alias="hash", serialization_alias="hash")
    hashExtension: Element | None = Field(None, alias="_hash", serialization_alias="_hash")
    language: str | None = Field(None, alias="language", serialization_alias="language")
    languageExtension: Element | None = Field(None, alias="_language", serialization_alias="_language")
    size: int | None = Field(None, alias="size", serialization_alias="size")
    sizeExtension: Element | None = Field(None, alias="_size", serialization_alias="_size")
    title: str | None = Field(None, alias="title", serialization_alias="title")
    titleExtension: Element | None = Field(None, alias="_title", serialization_alias="_title")
    url: str | None = Field(None, alias="url", serialization_alias="url")
    urlExtension: Element | None = Field(None, alias="_url", serialization_alias="_url")


class BackboneElement(Element):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    modifierExtension: PyList[Extension] | None = Field(None, alias="modifierExtension", serialization_alias="modifierExtension")


class CodeableConcept(Element, Generic[T]):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    coding: PyList[Coding[T]] | None = Field(None, alias="coding", serialization_alias="coding")
    text: str | None = Field(None, alias="text", serialization_alias="text")
    textExtension: Element | None = Field(None, alias="_text", serialization_alias="_text")


class Coding(Element, Generic[T]):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    code: T | None = Field(None, alias="code", serialization_alias="code")
    codeExtension: Element | None = Field(None, alias="_code", serialization_alias="_code")
    display: str | None = Field(None, alias="display", serialization_alias="display")
    displayExtension: Element | None = Field(None, alias="_display", serialization_alias="_display")
    system: str | None = Field(None, alias="system", serialization_alias="system")
    systemExtension: Element | None = Field(None, alias="_system", serialization_alias="_system")
    userSelected: bool | None = Field(None, alias="userSelected", serialization_alias="userSelected")
    userSelectedExtension: Element | None = Field(None, alias="_userSelected", serialization_alias="_userSelected")
    version: str | None = Field(None, alias="version", serialization_alias="version")
    versionExtension: Element | None = Field(None, alias="_version", serialization_alias="_version")


class ContactDetail(Element):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    name: str | None = Field(None, alias="name", serialization_alias="name")
    nameExtension: Element | None = Field(None, alias="_name", serialization_alias="_name")
    telecom: PyList[ContactPoint] | None = Field(None, alias="telecom", serialization_alias="telecom")


class ContactPoint(Element):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    period: Period | None = Field(None, alias="period", serialization_alias="period")
    rank: PositiveInt | None = Field(None, alias="rank", serialization_alias="rank")
    rankExtension: Element | None = Field(None, alias="_rank", serialization_alias="_rank")
    system: Literal["phone", "fax", "email", "pager", "url", "sms", "other"] | None = Field(None, alias="system", serialization_alias="system")
    systemExtension: Element | None = Field(None, alias="_system", serialization_alias="_system")
    use: Literal["home", "work", "temp", "old", "mobile"] | None = Field(None, alias="use", serialization_alias="use")
    useExtension: Element | None = Field(None, alias="_use", serialization_alias="_use")
    value: str | None = Field(None, alias="value", serialization_alias="value")
    valueExtension: Element | None = Field(None, alias="_value", serialization_alias="_value")


class Contributor(Element):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    contact: PyList[ContactDetail] | None = Field(None, alias="contact", serialization_alias="contact")
    name: str = Field(alias="name", serialization_alias="name")
    nameExtension: Element | None = Field(None, alias="_name", serialization_alias="_name")
    type: Literal["author", "editor", "reviewer", "endorser"] = Field(alias="type", serialization_alias="type")
    typeExtension: Element | None = Field(None, alias="_type", serialization_alias="_type")


class Count(Quantity):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    pass


class DataRequirementCodeFilter(Element):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    code: PyList[Coding] | None = Field(None, alias="code", serialization_alias="code")
    path: str | None = Field(None, alias="path", serialization_alias="path")
    searchParam: str | None = Field(None, alias="searchParam", serialization_alias="searchParam")
    valueSet: str | None = Field(None, alias="valueSet", serialization_alias="valueSet")

class DataRequirementDateFilter(Element):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    path: str | None = Field(None, alias="path", serialization_alias="path")
    searchParam: str | None = Field(None, alias="searchParam", serialization_alias="searchParam")
    valueDateTime: str | None = Field(None, alias="valueDateTime", serialization_alias="valueDateTime")
    valueDuration: Duration | None = Field(None, alias="valueDuration", serialization_alias="valueDuration")
    valuePeriod: Period | None = Field(None, alias="valuePeriod", serialization_alias="valuePeriod")

class DataRequirementSort(Element):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    direction: Literal["ascending", "descending"] = Field(alias="direction", serialization_alias="direction")
    path: str = Field(alias="path", serialization_alias="path")


class DataRequirement(Element):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    codeFilter: PyList[DataRequirementCodeFilter] | None = Field(None, alias="codeFilter", serialization_alias="codeFilter")
    dateFilter: PyList[DataRequirementDateFilter] | None = Field(None, alias="dateFilter", serialization_alias="dateFilter")
    limit: PositiveInt | None = Field(None, alias="limit", serialization_alias="limit")
    limitExtension: Element | None = Field(None, alias="_limit", serialization_alias="_limit")
    mustSupport: PyList[str] | None = Field(None, alias="mustSupport", serialization_alias="mustSupport")
    mustSupportExtension: PyList[Element | None] | None = Field(None, alias="_mustSupport", serialization_alias="_mustSupport")
    profile: PyList[str] | None = Field(None, alias="profile", serialization_alias="profile")
    profileExtension: PyList[Element | None] | None = Field(None, alias="_profile", serialization_alias="_profile")
    sort: PyList[DataRequirementSort] | None = Field(None, alias="sort", serialization_alias="sort")
    subjectCodeableConcept: CodeableConcept | None = Field(None, alias="subjectCodeableConcept", serialization_alias="subjectCodeableConcept")
    subjectReference: Reference | None = Field(None, alias="subjectReference", serialization_alias="subjectReference")
    type: str = Field(alias="type", serialization_alias="type")
    typeExtension: Element | None = Field(None, alias="_type", serialization_alias="_type")


class Distance(Quantity):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    pass


class DosageDoseAndRate(Element):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    doseQuantity: Quantity | None = Field(None, alias="doseQuantity", serialization_alias="doseQuantity")
    doseRange: Range | None = Field(None, alias="doseRange", serialization_alias="doseRange")
    rateQuantity: Quantity | None = Field(None, alias="rateQuantity", serialization_alias="rateQuantity")
    rateRange: Range | None = Field(None, alias="rateRange", serialization_alias="rateRange")
    rateRatio: Ratio | None = Field(None, alias="rateRatio", serialization_alias="rateRatio")
    type: CodeableConcept | None = Field(None, alias="type", serialization_alias="type")


class Dosage(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    additionalInstruction: PyList[CodeableConcept] | None = Field(None, alias="additionalInstruction", serialization_alias="additionalInstruction")
    asNeededBoolean: bool | None = Field(None, alias="asNeededBoolean", serialization_alias="asNeededBoolean")
    asNeededBooleanExtension: Element | None = Field(None, alias="_asNeededBoolean", serialization_alias="_asNeededBoolean")
    asNeededCodeableConcept: CodeableConcept | None = Field(None, alias="asNeededCodeableConcept", serialization_alias="asNeededCodeableConcept")
    doseAndRate: PyList[DosageDoseAndRate] | None = Field(None, alias="doseAndRate", serialization_alias="doseAndRate")
    maxDosePerAdministration: Quantity | None = Field(None, alias="maxDosePerAdministration", serialization_alias="maxDosePerAdministration")
    maxDosePerLifetime: Quantity | None = Field(None, alias="maxDosePerLifetime", serialization_alias="maxDosePerLifetime")
    maxDosePerPeriod: Ratio | None = Field(None, alias="maxDosePerPeriod", serialization_alias="maxDosePerPeriod")
    method: CodeableConcept | None = Field(None, alias="method", serialization_alias="method")
    patientInstruction: str | None = Field(None, alias="patientInstruction", serialization_alias="patientInstruction")
    patientInstructionExtension: Element | None = Field(None, alias="_patientInstruction", serialization_alias="_patientInstruction")
    route: CodeableConcept | None = Field(None, alias="route", serialization_alias="route")
    sequence: int | None = Field(None, alias="sequence", serialization_alias="sequence")
    sequenceExtension: Element | None = Field(None, alias="_sequence", serialization_alias="_sequence")
    site: CodeableConcept | None = Field(None, alias="site", serialization_alias="site")
    text: str | None = Field(None, alias="text", serialization_alias="text")
    textExtension: Element | None = Field(None, alias="_text", serialization_alias="_text")
    timing: Timing | None = Field(None, alias="timing", serialization_alias="timing")


class Duration(Quantity):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    pass


class Expression(Element):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    description: str | None = Field(None, alias="description", serialization_alias="description")
    descriptionExtension: Element | None = Field(None, alias="_description", serialization_alias="_description")
    expression: str | None = Field(None, alias="expression", serialization_alias="expression")
    expressionExtension: Element | None = Field(None, alias="_expression", serialization_alias="_expression")
    language: str = Field(alias="language", serialization_alias="language")
    languageExtension: Element | None = Field(None, alias="_language", serialization_alias="_language")
    name: str | None = Field(None, alias="name", serialization_alias="name")
    nameExtension: Element | None = Field(None, alias="_name", serialization_alias="_name")
    reference: str | None = Field(None, alias="reference", serialization_alias="reference")
    referenceExtension: Element | None = Field(None, alias="_reference", serialization_alias="_reference")


class Extension(Element):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    url: str = Field(alias="url", serialization_alias="url")
    urlExtension: Element | None = Field(None, alias="_url", serialization_alias="_url")
    valueAddress: Address | None = Field(None, alias="valueAddress", serialization_alias="valueAddress")
    valueAge: Age | None = Field(None, alias="valueAge", serialization_alias="valueAge")
    valueAnnotation: Annotation | None = Field(None, alias="valueAnnotation", serialization_alias="valueAnnotation")
    valueAttachment: Attachment | None = Field(None, alias="valueAttachment", serialization_alias="valueAttachment")
    valueBase64binary: str | None = Field(None, alias="valueBase64Binary", serialization_alias="valueBase64Binary")
    valueBase64binaryExtension: Element | None = Field(None, alias="_valueBase64Binary", serialization_alias="_valueBase64Binary")
    valueBoolean: bool | None = Field(None, alias="valueBoolean", serialization_alias="valueBoolean")
    valueBooleanExtension: Element | None = Field(None, alias="_valueBoolean", serialization_alias="_valueBoolean")
    valueCanonical: str | None = Field(None, alias="valueCanonical", serialization_alias="valueCanonical")
    valueCanonicalExtension: Element | None = Field(None, alias="_valueCanonical", serialization_alias="_valueCanonical")
    valueCode: str | None = Field(None, alias="valueCode", serialization_alias="valueCode")
    valueCodeExtension: Element | None = Field(None, alias="_valueCode", serialization_alias="_valueCode")
    valueCodeableConcept: CodeableConcept | None = Field(None, alias="valueCodeableConcept", serialization_alias="valueCodeableConcept")
    valueCoding: Coding | None = Field(None, alias="valueCoding", serialization_alias="valueCoding")
    valueContactDetail: ContactDetail | None = Field(None, alias="valueContactDetail", serialization_alias="valueContactDetail")
    valueContactPoint: ContactPoint | None = Field(None, alias="valueContactPoint", serialization_alias="valueContactPoint")
    valueContributor: Contributor | None = Field(None, alias="valueContributor", serialization_alias="valueContributor")
    valueCount: Count | None = Field(None, alias="valueCount", serialization_alias="valueCount")
    valueDataRequirement: DataRequirement | None = Field(None, alias="valueDataRequirement", serialization_alias="valueDataRequirement")
    valueDate: str | None = Field(None, alias="valueDate", serialization_alias="valueDate")
    valueDateExtension: Element | None = Field(None, alias="_valueDate", serialization_alias="_valueDate")
    valueDateTime: str | None = Field(None, alias="valueDateTime", serialization_alias="valueDateTime")
    valueDateTimeExtension: Element | None = Field(None, alias="_valueDateTime", serialization_alias="_valueDateTime")
    valueDecimal: float | None = Field(None, alias="valueDecimal", serialization_alias="valueDecimal")
    valueDecimalExtension: Element | None = Field(None, alias="_valueDecimal", serialization_alias="_valueDecimal")
    valueDistance: Distance | None = Field(None, alias="valueDistance", serialization_alias="valueDistance")
    valueDosage: Dosage | None = Field(None, alias="valueDosage", serialization_alias="valueDosage")
    valueDuration: Duration | None = Field(None, alias="valueDuration", serialization_alias="valueDuration")
    valueExpression: Expression | None = Field(None, alias="valueExpression", serialization_alias="valueExpression")
    valueHumanName: HumanName | None = Field(None, alias="valueHumanName", serialization_alias="valueHumanName")
    valueId: str | None = Field(None, alias="valueId", serialization_alias="valueId")
    valueIdExtension: Element | None = Field(None, alias="_valueId", serialization_alias="_valueId")
    valueIdentifier: Identifier | None = Field(None, alias="valueIdentifier", serialization_alias="valueIdentifier")
    valueInstant: str | None = Field(None, alias="valueInstant", serialization_alias="valueInstant")
    valueInstantExtension: Element | None = Field(None, alias="_valueInstant", serialization_alias="_valueInstant")
    valueInteger: int | None = Field(None, alias="valueInteger", serialization_alias="valueInteger")
    valueIntegerExtension: Element | None = Field(None, alias="_valueInteger", serialization_alias="_valueInteger")
    valueMarkdown: str | None = Field(None, alias="valueMarkdown", serialization_alias="valueMarkdown")
    valueMarkdownExtension: Element | None = Field(None, alias="_valueMarkdown", serialization_alias="_valueMarkdown")
    valueMeta: Meta | None = Field(None, alias="valueMeta", serialization_alias="valueMeta")
    valueMoney: Money | None = Field(None, alias="valueMoney", serialization_alias="valueMoney")
    valueOid: str | None = Field(None, alias="valueOid", serialization_alias="valueOid")
    valueOidExtension: Element | None = Field(None, alias="_valueOid", serialization_alias="_valueOid")
    valueParameterDefinition: ParameterDefinition | None = Field(None, alias="valueParameterDefinition", serialization_alias="valueParameterDefinition")
    valuePeriod: Period | None = Field(None, alias="valuePeriod", serialization_alias="valuePeriod")
    valuePositiveInt: PositiveInt | None = Field(None, alias="valuePositiveInt", serialization_alias="valuePositiveInt")
    valuePositiveIntExtension: Element | None = Field(None, alias="_valuePositiveInt", serialization_alias="_valuePositiveInt")
    valueQuantity: Quantity | None = Field(None, alias="valueQuantity", serialization_alias="valueQuantity")
    valueRange: Range | None = Field(None, alias="valueRange", serialization_alias="valueRange")
    valueRatio: Ratio | None = Field(None, alias="valueRatio", serialization_alias="valueRatio")
    valueReference: Reference | None = Field(None, alias="valueReference", serialization_alias="valueReference")
    valueRelatedArtifact: RelatedArtifact | None = Field(None, alias="valueRelatedArtifact", serialization_alias="valueRelatedArtifact")
    valueSampledData: SampledData | None = Field(None, alias="valueSampledData", serialization_alias="valueSampledData")
    valueSignature: Signature | None = Field(None, alias="valueSignature", serialization_alias="valueSignature")
    valueString: str | None = Field(None, alias="valueString", serialization_alias="valueString")
    valueStringExtension: Element | None = Field(None, alias="_valueString", serialization_alias="_valueString")
    valueTime: str | None = Field(None, alias="valueTime", serialization_alias="valueTime")
    valueTimeExtension: Element | None = Field(None, alias="_valueTime", serialization_alias="_valueTime")
    valueTiming: Timing | None = Field(None, alias="valueTiming", serialization_alias="valueTiming")
    valueTriggerDefinition: TriggerDefinition | None = Field(None, alias="valueTriggerDefinition", serialization_alias="valueTriggerDefinition")
    valueUnsignedInt: int | None = Field(None, alias="valueUnsignedInt", serialization_alias="valueUnsignedInt")
    valueUnsignedIntExtension: Element | None = Field(None, alias="_valueUnsignedInt", serialization_alias="_valueUnsignedInt")
    valueUri: str | None = Field(None, alias="valueUri", serialization_alias="valueUri")
    valueUriExtension: Element | None = Field(None, alias="_valueUri", serialization_alias="_valueUri")
    valueUrl: str | None = Field(None, alias="valueUrl", serialization_alias="valueUrl")
    valueUrlExtension: Element | None = Field(None, alias="_valueUrl", serialization_alias="_valueUrl")
    valueUsageContext: UsageContext | None = Field(None, alias="valueUsageContext", serialization_alias="valueUsageContext")
    valueUuid: str | None = Field(None, alias="valueUuid", serialization_alias="valueUuid")
    valueUuidExtension: Element | None = Field(None, alias="_valueUuid", serialization_alias="_valueUuid")

    def __eq__(self, other: object) -> bool:
        if not isinstance(other, Extension):
            return NotImplemented
        return self.model_dump(by_alias=True, exclude_none=True) == other.model_dump(by_alias=True, exclude_none=True)

    def __hash__(self) -> int:
        return hash(self.url)


class HumanName(Element):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    family: str | None = Field(None, alias="family", serialization_alias="family")
    familyExtension: Element | None = Field(None, alias="_family", serialization_alias="_family")
    given: PyList[str] | None = Field(None, alias="given", serialization_alias="given")
    givenExtension: PyList[Element | None] | None = Field(None, alias="_given", serialization_alias="_given")
    period: Period | None = Field(None, alias="period", serialization_alias="period")
    prefix: PyList[str] | None = Field(None, alias="prefix", serialization_alias="prefix")
    prefixExtension: PyList[Element | None] | None = Field(None, alias="_prefix", serialization_alias="_prefix")
    suffix: PyList[str] | None = Field(None, alias="suffix", serialization_alias="suffix")
    suffixExtension: PyList[Element | None] | None = Field(None, alias="_suffix", serialization_alias="_suffix")
    text: str | None = Field(None, alias="text", serialization_alias="text")
    textExtension: Element | None = Field(None, alias="_text", serialization_alias="_text")
    use: Literal["usual", "official", "temp", "nickname", "anonymous", "old", "maiden"] | None = Field(None, alias="use", serialization_alias="use")
    useExtension: Element | None = Field(None, alias="_use", serialization_alias="_use")


class Identifier(Element):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    assigner: Reference | None = Field(None, alias="assigner", serialization_alias="assigner")
    period: Period | None = Field(None, alias="period", serialization_alias="period")
    system: str | None = Field(None, alias="system", serialization_alias="system")
    systemExtension: Element | None = Field(None, alias="_system", serialization_alias="_system")
    type: CodeableConcept[Literal["DL", "PPN", "BRN", "MR", "MCN", "EN", "TAX", "NIIP", "PRN", "MD", "DR", "ACSN", "UDI", "SNO", "SB", "PLAC", "FILL", "JHN"] | str] | None = Field(None, alias="type", serialization_alias="type")
    use: Literal["usual", "official", "temp", "secondary", "old"] | None = Field(None, alias="use", serialization_alias="use")
    useExtension: Element | None = Field(None, alias="_use", serialization_alias="_use")
    value: str | None = Field(None, alias="value", serialization_alias="value")
    valueExtension: Element | None = Field(None, alias="_value", serialization_alias="_value")


class Meta(Element):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    lastUpdated: str | None = Field(None, alias="lastUpdated", serialization_alias="lastUpdated")
    lastUpdatedExtension: Element | None = Field(None, alias="_lastUpdated", serialization_alias="_lastUpdated")
    profile: PyList[str] | None = Field(None, alias="profile", serialization_alias="profile")
    profileExtension: PyList[Element | None] | None = Field(None, alias="_profile", serialization_alias="_profile")
    security: PyList[Coding] | None = Field(None, alias="security", serialization_alias="security")
    source: str | None = Field(None, alias="source", serialization_alias="source")
    sourceExtension: Element | None = Field(None, alias="_source", serialization_alias="_source")
    tag: PyList[Coding] | None = Field(None, alias="tag", serialization_alias="tag")
    versionId: str | None = Field(None, alias="versionId", serialization_alias="versionId")
    versionIdExtension: Element | None = Field(None, alias="_versionId", serialization_alias="_versionId")


class Money(Element):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    currency: str | None = Field(None, alias="currency", serialization_alias="currency")
    currencyExtension: Element | None = Field(None, alias="_currency", serialization_alias="_currency")
    value: float | None = Field(None, alias="value", serialization_alias="value")
    valueExtension: Element | None = Field(None, alias="_value", serialization_alias="_value")


class Narrative(Element):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    div: str = Field(alias="div", serialization_alias="div")
    divExtension: Element | None = Field(None, alias="_div", serialization_alias="_div")
    status: Literal["generated", "extensions", "additional", "empty"] = Field(alias="status", serialization_alias="status")
    statusExtension: Element | None = Field(None, alias="_status", serialization_alias="_status")


class ParameterDefinition(Element):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    documentation: str | None = Field(None, alias="documentation", serialization_alias="documentation")
    documentationExtension: Element | None = Field(None, alias="_documentation", serialization_alias="_documentation")
    max: str | None = Field(None, alias="max", serialization_alias="max")
    maxExtension: Element | None = Field(None, alias="_max", serialization_alias="_max")
    min: int | None = Field(None, alias="min", serialization_alias="min")
    minExtension: Element | None = Field(None, alias="_min", serialization_alias="_min")
    name: str | None = Field(None, alias="name", serialization_alias="name")
    nameExtension: Element | None = Field(None, alias="_name", serialization_alias="_name")
    profile: str | None = Field(None, alias="profile", serialization_alias="profile")
    profileExtension: Element | None = Field(None, alias="_profile", serialization_alias="_profile")
    type: str = Field(alias="type", serialization_alias="type")
    typeExtension: Element | None = Field(None, alias="_type", serialization_alias="_type")
    use: Literal["in", "out"] = Field(alias="use", serialization_alias="use")
    useExtension: Element | None = Field(None, alias="_use", serialization_alias="_use")


class Period(Element):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    end: str | None = Field(None, alias="end", serialization_alias="end")
    endExtension: Element | None = Field(None, alias="_end", serialization_alias="_end")
    start: str | None = Field(None, alias="start", serialization_alias="start")
    startExtension: Element | None = Field(None, alias="_start", serialization_alias="_start")


class Range(Element):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    high: Quantity | None = Field(None, alias="high", serialization_alias="high")
    low: Quantity | None = Field(None, alias="low", serialization_alias="low")


class Ratio(Element):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    denominator: Quantity | None = Field(None, alias="denominator", serialization_alias="denominator")
    numerator: Quantity | None = Field(None, alias="numerator", serialization_alias="numerator")


class Reference(Element):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    display: str | None = Field(None, alias="display", serialization_alias="display")
    displayExtension: Element | None = Field(None, alias="_display", serialization_alias="_display")
    identifier: Identifier | None = Field(None, alias="identifier", serialization_alias="identifier")
    reference: str | None = Field(None, alias="reference", serialization_alias="reference")
    referenceExtension: Element | None = Field(None, alias="_reference", serialization_alias="_reference")
    type: str | None = Field(None, alias="type", serialization_alias="type")
    typeExtension: Element | None = Field(None, alias="_type", serialization_alias="_type")


class RelatedArtifact(Element):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    citation: str | None = Field(None, alias="citation", serialization_alias="citation")
    citationExtension: Element | None = Field(None, alias="_citation", serialization_alias="_citation")
    display: str | None = Field(None, alias="display", serialization_alias="display")
    displayExtension: Element | None = Field(None, alias="_display", serialization_alias="_display")
    document: Attachment | None = Field(None, alias="document", serialization_alias="document")
    label: str | None = Field(None, alias="label", serialization_alias="label")
    labelExtension: Element | None = Field(None, alias="_label", serialization_alias="_label")
    resource: str | None = Field(None, alias="resource", serialization_alias="resource")
    resourceExtension: Element | None = Field(None, alias="_resource", serialization_alias="_resource")
    type: Literal["documentation", "justification", "citation", "predecessor", "successor", "derived-from", "depends-on", "composed-of"] = Field(alias="type", serialization_alias="type")
    typeExtension: Element | None = Field(None, alias="_type", serialization_alias="_type")
    url: str | None = Field(None, alias="url", serialization_alias="url")
    urlExtension: Element | None = Field(None, alias="_url", serialization_alias="_url")


class SampledData(Element):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    data: str | None = Field(None, alias="data", serialization_alias="data")
    dataExtension: Element | None = Field(None, alias="_data", serialization_alias="_data")
    dimensions: PositiveInt = Field(alias="dimensions", serialization_alias="dimensions")
    dimensionsExtension: Element | None = Field(None, alias="_dimensions", serialization_alias="_dimensions")
    factor: float | None = Field(None, alias="factor", serialization_alias="factor")
    factorExtension: Element | None = Field(None, alias="_factor", serialization_alias="_factor")
    lowerLimit: float | None = Field(None, alias="lowerLimit", serialization_alias="lowerLimit")
    lowerLimitExtension: Element | None = Field(None, alias="_lowerLimit", serialization_alias="_lowerLimit")
    origin: Quantity = Field(alias="origin", serialization_alias="origin")
    period: float = Field(alias="period", serialization_alias="period")
    periodExtension: Element | None = Field(None, alias="_period", serialization_alias="_period")
    upperLimit: float | None = Field(None, alias="upperLimit", serialization_alias="upperLimit")
    upperLimitExtension: Element | None = Field(None, alias="_upperLimit", serialization_alias="_upperLimit")


class Signature(Element):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    data: str | None = Field(None, alias="data", serialization_alias="data")
    dataExtension: Element | None = Field(None, alias="_data", serialization_alias="_data")
    onBehalfOf: Reference | None = Field(None, alias="onBehalfOf", serialization_alias="onBehalfOf")
    sigFormat: str | None = Field(None, alias="sigFormat", serialization_alias="sigFormat")
    sigFormatExtension: Element | None = Field(None, alias="_sigFormat", serialization_alias="_sigFormat")
    targetFormat: str | None = Field(None, alias="targetFormat", serialization_alias="targetFormat")
    targetFormatExtension: Element | None = Field(None, alias="_targetFormat", serialization_alias="_targetFormat")
    type: PyList[Coding[Literal["1.2.840.10065.1.12.1.1", "1.2.840.10065.1.12.1.2", "1.2.840.10065.1.12.1.3", "1.2.840.10065.1.12.1.4", "1.2.840.10065.1.12.1.5", "1.2.840.10065.1.12.1.6", "1.2.840.10065.1.12.1.7", "1.2.840.10065.1.12.1.8", "1.2.840.10065.1.12.1.9", "1.2.840.10065.1.12.1.10", "1.2.840.10065.1.12.1.11", "1.2.840.10065.1.12.1.12", "1.2.840.10065.1.12.1.13", "1.2.840.10065.1.12.1.14", "1.2.840.10065.1.12.1.15", "1.2.840.10065.1.12.1.16", "1.2.840.10065.1.12.1.17", "1.2.840.10065.1.12.1.18"] | str]] = Field(alias="type", serialization_alias="type")
    when: str = Field(alias="when", serialization_alias="when")
    whenExtension: Element | None = Field(None, alias="_when", serialization_alias="_when")
    who: Reference = Field(alias="who", serialization_alias="who")


class TimingRepeat(Element):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    boundsDuration: Duration | None = Field(None, alias="boundsDuration", serialization_alias="boundsDuration")
    boundsPeriod: Period | None = Field(None, alias="boundsPeriod", serialization_alias="boundsPeriod")
    boundsRange: Range | None = Field(None, alias="boundsRange", serialization_alias="boundsRange")
    count: PositiveInt | None = Field(None, alias="count", serialization_alias="count")
    countMax: PositiveInt | None = Field(None, alias="countMax", serialization_alias="countMax")
    dayOfWeek: PyList[Literal["mon", "tue", "wed", "thu", "fri", "sat", "sun"]] | None = Field(None, alias="dayOfWeek", serialization_alias="dayOfWeek")
    duration: float | None = Field(None, alias="duration", serialization_alias="duration")
    durationMax: float | None = Field(None, alias="durationMax", serialization_alias="durationMax")
    durationUnit: Literal["s", "min", "h", "d", "wk", "mo", "a"] | None = Field(None, alias="durationUnit", serialization_alias="durationUnit")
    frequency: PositiveInt | None = Field(None, alias="frequency", serialization_alias="frequency")
    frequencyMax: PositiveInt | None = Field(None, alias="frequencyMax", serialization_alias="frequencyMax")
    offset: int | None = Field(None, alias="offset", serialization_alias="offset")
    period: float | None = Field(None, alias="period", serialization_alias="period")
    periodMax: float | None = Field(None, alias="periodMax", serialization_alias="periodMax")
    periodUnit: Literal["s", "min", "h", "d", "wk", "mo", "a"] | None = Field(None, alias="periodUnit", serialization_alias="periodUnit")
    timeOfDay: PyList[str] | None = Field(None, alias="timeOfDay", serialization_alias="timeOfDay")
    when: PyList[Literal["MORN", "MORN.early", "MORN.late", "NOON", "AFT", "AFT.early", "AFT.late", "EVE", "EVE.early", "EVE.late", "NIGHT", "PHS", "HS", "WAKE", "C", "CM", "CD", "CV", "AC", "ACM", "ACD", "ACV", "PC", "PCM", "PCD", "PCV"]] | None = Field(None, alias="when", serialization_alias="when")


class Timing(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    code: CodeableConcept[Literal["BID", "TID", "QID", "AM", "PM", "QD", "QOD", "Q1H", "Q2H", "Q3H", "Q4H", "Q6H", "Q8H", "BED", "WK", "MO"] | str] | None = Field(None, alias="code", serialization_alias="code")
    event: PyList[str] | None = Field(None, alias="event", serialization_alias="event")
    eventExtension: PyList[Element | None] | None = Field(None, alias="_event", serialization_alias="_event")
    repeat: TimingRepeat | None = Field(None, alias="repeat", serialization_alias="repeat")


class TriggerDefinition(Element):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    condition: Expression | None = Field(None, alias="condition", serialization_alias="condition")
    data: PyList[DataRequirement] | None = Field(None, alias="data", serialization_alias="data")
    name: str | None = Field(None, alias="name", serialization_alias="name")
    nameExtension: Element | None = Field(None, alias="_name", serialization_alias="_name")
    timingDate: str | None = Field(None, alias="timingDate", serialization_alias="timingDate")
    timingDateExtension: Element | None = Field(None, alias="_timingDate", serialization_alias="_timingDate")
    timingDateTime: str | None = Field(None, alias="timingDateTime", serialization_alias="timingDateTime")
    timingDateTimeExtension: Element | None = Field(None, alias="_timingDateTime", serialization_alias="_timingDateTime")
    timingReference: Reference | None = Field(None, alias="timingReference", serialization_alias="timingReference")
    timingTiming: Timing | None = Field(None, alias="timingTiming", serialization_alias="timingTiming")
    type: Literal["named-event", "periodic", "data-changed", "data-added", "data-modified", "data-removed", "data-accessed", "data-access-ended"] = Field(alias="type", serialization_alias="type")
    typeExtension: Element | None = Field(None, alias="_type", serialization_alias="_type")


class UsageContext(Element):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    code: Coding[Literal["gender", "age", "focus", "user", "workflow", "task", "venue", "species", "program"] | str] = Field(alias="code", serialization_alias="code")
    valueCodeableConcept: CodeableConcept | None = Field(None, alias="valueCodeableConcept", serialization_alias="valueCodeableConcept")
    valueQuantity: Quantity | None = Field(None, alias="valueQuantity", serialization_alias="valueQuantity")
    valueRange: Range | None = Field(None, alias="valueRange", serialization_alias="valueRange")
    valueReference: Reference | None = Field(None, alias="valueReference", serialization_alias="valueReference")


