services:
  postgres:
    image: "${PGIMAGE}"
    pull_policy: always
    ports:
      - "${PGHOSTPORT}:5432"
    volumes:
      - "./pgdata:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER:     "${PGUSER}"
      POSTGRES_PASSWORD: "${PGPASSWORD}"
      POSTGRES_DB:       "${PGDATABASE}"

  aidbox:
    image: "${AIDBOX_IMAGE}"
    pull_policy: always
    depends_on: ["postgres"]
    ports:
      - "${AIDBOX_PORT}:${AIDBOX_PORT}"
    env_file:
      - .env
    environment:
      PGPORT: 5432
      PGHOST: postgres

  redis:
    image: redis
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - "./redisdata:/data"

#  app:
#    image: aidbox-forms-smart-launch-2
#    pull_policy: never
#    env_file:
#      - .env
#    environment:
#      REDIS_URL: "redis://redis:6379/0"
#      AIDBOX_BASE_URL: http://aidbox:8888
#      PGHOST: postgres
#    ports:
#      - "3001:3000"
