{
 "title": "Aidbox dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Instance",
    "query": {
     "query": "label_values(http_server_request_duration_seconds_count, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "HTTP RPS",
   "type": "stat",
   "description": "> Shows the count of requests per second",
   "gridPos": { "x": 0, "y": 0, "w": 3, "h": 3 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "stat",
   "description": "> Shows the average HTTP request duration",
   "gridPos": { "x": 3, "y": 0, "w": 3, "h": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(http_server_request_duration_seconds_sum{}[$__rate_interval]))/sum(rate(http_server_request_duration_seconds_count{}[$__rate_interval])))",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Durattion P99",
   "type": "stat",
   "description": "> 99th Percentile of http request du ration",
   "gridPos": { "x": 6, "y": 0, "w": 3, "h": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,sum(rate(http_server_request_duration_seconds_bucket{}[$__rate_interval])) by (le))",
     "legendFormat": "d99"
    }
   ]
  },
  {
   "title": "HTTP Queue wait P99",
   "type": "stat",
   "description": "> 99th Percentile of HTTP queue wait time",
   "gridPos": { "x": 9, "y": 0, "w": 3, "h": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,sum(rate(http_server_request_wait_seconds_bucket{}[$__rate_interval])) by (le))",
     "legendFormat": "wait99"
    }
   ]
  },
  {
   "title": "HTTP wait queue",
   "type": "stat",
   "description": "> HTTP wait queue size",
   "gridPos": { "x": 12, "y": 0, "w": 3, "h": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "httpkit_queue_count{instance=\"$Instance\"}",
     "legendFormat": "HTTP queue"
    }
   ]
  },
  {
   "title": "PG read/write ration",
   "type": "stat",
   "description": "> Shows the ratio of the number of SELECT queries to data modification queries",
   "gridPos": { "x": 15, "y": 0, "w": 3, "h": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(rate(pg_requests_total{instance=\"$Instance\"}[$__range])/(rate(pg_updates_total{instance=\"$Instance\"}[$__range])+rate(pg_inserts_total{instance=\"$Instance\"}[$__range])+rate(pg_deletes_total{instance=\"$Instance\"}[$__range])))",
     "legendFormat": "read/write"
    }
   ]
  },
  {
   "title": "DB Size",
   "type": "stat",
   "description": "> Shows the current size of the database",
   "gridPos": { "x": 18, "y": 0, "w": 3, "h": 3 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(db_size_bytes{instance=\"$Instance\"})"
    }
   ]
  },
  {
   "title": "Requests per minute",
   "type": "stat",
   "description": "> Show count requests in [1m] window",
   "gridPos": { "x": 21, "y": 0, "w": 3, "h": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{}[1m]))"
    }
   ]
  },
  {
   "title": "Requests Per Second",
   "type": "timeseries",
   "description": "> `box req` - shows how many requests per second are processed on average.\n\n> `>0.5  sec` - Shows how many requests are processed on average for an interval of more than 0.5 seconds.\n\n> `db req` - shows the average number of all read requests to the database per second",
   "gridPos": { "x": 0, "y": 2, "w": 12, "h": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{}[$__rate_interval]))",
     "legendFormat": "box req"
    },
    {
     "expr": "(sum(rate(http_server_request_duration_seconds_bucket{le=\"+Inf\"}[$__rate_interval]))-sum(rate(http_server_request_duration_seconds_bucket{le=\"0.5\"}[$__rate_interval])))",
     "legendFormat": "> 0.5 sec"
    },
    {
     "expr": "rate(pg_requests_total{instance=\"$Instance\"}[$__rate_interval])",
     "legendFormat": "db req"
    }
   ]
  },
  {
   "title": "Requests summary",
   "type": "table",
   "description": "> Shows information about routes. Contains information about the endpoint, average query execution time, 99th percentile, number of queries, and the amount of time to execute a query in a given interval",
   "gridPos": { "x": 0, "y": 12, "w": 24, "h": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "(sum(increase(http_server_request_duration_seconds_sum{}[$__range])) by (route)>0)",
     "legendFormat": "Total time"
    },
    {
     "expr": "(sum(increase(http_server_request_duration_seconds_count{}[$__range])) by (route)>0)",
     "legendFormat": "Count"
    },
    {
     "expr": "((sum(increase(http_server_request_duration_seconds_sum{}[$__range])) by (route)/sum(increase(http_server_request_duration_seconds_count{}[$__range])) by (route))>0)",
     "legendFormat": "Mean"
    },
    {
     "expr": "(histogram_quantile(0.99,sum(rate(http_server_request_duration_seconds_bucket{}[$__range])) by (le,route))>0)",
     "legendFormat": "99 percentile"
    }
   ]
  },
  {
   "title": "Request distribution by time",
   "type": "piechart",
   "description": "> Shows the top 30 longest requests in percentage terms by Endpoint",
   "gridPos": { "x": 12, "y": 2, "w": 6, "h": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum((topk(30,increase(http_server_request_duration_seconds_sum{}[$__range]))>0)) by (route)",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Request distribution by calls",
   "type": "piechart",
   "description": "> Request distribution by calls count ",
   "gridPos": { "x": 18, "y": 2, "w": 6, "h": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(topk(30,increase(http_server_request_duration_seconds_count{}[$__range]))>0)",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "description": "> Shows the number of requests processed with `4xx` and `5xx` errors",
   "gridPos": { "x": 12, "y": 7, "w": 6, "h": 5 },
   "targets": [
    {
     "expr": "sum(increase(http_server_request_duration_seconds_count{status=~\"4..\"}[$__rate_interval]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(increase(http_server_request_duration_seconds_count{status=~\"5..\"}[$__rate_interval]))",
     "legendFormat": "5xx"
    },
    {
     "expr": "rate(hikari_timeout_total{}[$__rate_interval])",
     "legendFormat": "db conn err"
    },
    {}
   ]
  },
  {
   "title": "Response statuses",
   "type": "piechart",
   "description": "> Shows the rate of change in the number of requests with different statuses",
   "gridPos": { "x": 18, "y": 7, "w": 6, "h": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(increase(http_server_request_duration_seconds_count{}[$__range])) by (status)>0)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "timeseries",
   "description": "> Shows the JVM memory usage",
   "gridPos": { "x": 0, "y": 7, "w": 12, "h": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_runtime_jvm_memory_usage_bytes{instance=\"$Instance\",type=\"heap\"}",
     "legendFormat": "heap"
    },
    {
     "expr": "process_runtime_jvm_memory_usage_bytes{instance=\"$Instance\",type=\"non-heap\"}",
     "legendFormat": "non-heap"
    },
    {
     "expr": "process_runtime_jvm_memory_size_max_bytes{instance=\"$Instance\"}",
     "legendFormat": "max"
    }
   ]
  }
 ]
}