// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { BackboneElement } from './BackboneElement';
import { CodeableConcept } from './CodeableConcept';
import { DomainResource } from './DomainResource';
import { Identifier } from './Identifier';
import { Period } from './Period';
import { Reference } from './Reference';


export interface AccountCoverage extends BackboneElement {
    coverage: Reference<'Coverage'>;
    priority?: number;
}

export interface AccountGuarantor extends BackboneElement {
    onHold?: boolean;
    party: Reference<'Organization' | 'Patient' | 'RelatedPerson'>;
    period?: Period;
}

export interface Account extends DomainResource {
    coverage?: AccountCoverage[];
    description?: string;
    _description?: Element;
    guarantor?: AccountGuarantor[];
    identifier?: Identifier[];
    name?: string;
    _name?: Element;
    owner?: Reference<'Organization'>;
    partOf?: Reference<'Account'>;
    servicePeriod?: Period;
    status: 'active' | 'inactive' | 'entered-in-error' | 'on-hold' | 'unknown';
    _status?: Element;
    subject?: Reference<'Device' | 'HealthcareService' | 'Location' | 'Organization' | 'Patient' | 'Practitioner' | 'PractitionerRole'>[];
    type?: CodeableConcept;
}

