// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { BackboneElement } from './BackboneElement';
import { CodeableConcept } from './CodeableConcept';
import { ContactDetail } from './ContactDetail';
import { DomainResource } from './DomainResource';
import { Identifier } from './Identifier';
import { Money } from './Money';
import { Period } from './Period';
import { Reference } from './Reference';
import { UsageContext } from './UsageContext';


export interface ChargeItemDefinitionApplicability extends BackboneElement {
    description?: string;
    expression?: string;
    language?: string;
}

export interface ChargeItemDefinitionPropertyGroup extends BackboneElement {
    applicability?: ChargeItemDefinitionApplicability[];
    priceComponent?: ChargeItemDefinitionPropertyGroupPriceComponent[];
}

export interface ChargeItemDefinitionPropertyGroupPriceComponent extends BackboneElement {
    amount?: Money;
    code?: CodeableConcept;
    factor?: number;
    type: 'base' | 'surcharge' | 'deduction' | 'discount' | 'tax' | 'informational';
}

export interface ChargeItemDefinition extends DomainResource {
    applicability?: ChargeItemDefinitionApplicability[];
    approvalDate?: string;
    _approvalDate?: Element;
    code?: CodeableConcept;
    contact?: ContactDetail[];
    copyright?: string;
    _copyright?: Element;
    date?: string;
    _date?: Element;
    derivedFromUri?: string[];
    _derivedFromUri?: Element;
    description?: string;
    _description?: Element;
    effectivePeriod?: Period;
    experimental?: boolean;
    _experimental?: Element;
    identifier?: Identifier[];
    instance?: Reference<'Device' | 'Medication' | 'Substance'>[];
    jurisdiction?: CodeableConcept[];
    lastReviewDate?: string;
    _lastReviewDate?: Element;
    partOf?: string[];
    _partOf?: Element;
    propertyGroup?: ChargeItemDefinitionPropertyGroup[];
    publisher?: string;
    _publisher?: Element;
    replaces?: string[];
    _replaces?: Element;
    status: 'draft' | 'active' | 'retired' | 'unknown';
    _status?: Element;
    title?: string;
    _title?: Element;
    url: string;
    _url?: Element;
    useContext?: UsageContext[];
    version?: string;
    _version?: Element;
}

