// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { Annotation } from './Annotation';
import { BackboneElement } from './BackboneElement';
import { CodeableConcept } from './CodeableConcept';
import { ContactDetail } from './ContactDetail';
import { DomainResource } from './DomainResource';
import { Identifier } from './Identifier';
import { Period } from './Period';
import { Reference } from './Reference';
import { RelatedArtifact } from './RelatedArtifact';
import { UsageContext } from './UsageContext';


export interface EffectEvidenceSynthesisCertainty extends BackboneElement {
    certaintySubcomponent?: EffectEvidenceSynthesisCertaintyCertaintySubcomponent[];
    note?: Annotation[];
    rating?: CodeableConcept[];
}

export interface EffectEvidenceSynthesisCertaintyCertaintySubcomponent extends BackboneElement {
    note?: Annotation[];
    rating?: CodeableConcept[];
    type?: CodeableConcept;
}

export interface EffectEvidenceSynthesisEffectEstimate extends BackboneElement {
    description?: string;
    precisionEstimate?: EffectEvidenceSynthesisEffectEstimatePrecisionEstimate[];
    type?: CodeableConcept;
    unitOfMeasure?: CodeableConcept;
    value?: number;
    variantState?: CodeableConcept;
}

export interface EffectEvidenceSynthesisEffectEstimatePrecisionEstimate extends BackboneElement {
    from?: number;
    level?: number;
    to?: number;
    type?: CodeableConcept;
}

export interface EffectEvidenceSynthesisResultsByExposure extends BackboneElement {
    description?: string;
    exposureState?: 'exposure' | 'exposure-alternative';
    riskEvidenceSynthesis: Reference<'RiskEvidenceSynthesis'>;
    variantState?: CodeableConcept;
}

export interface EffectEvidenceSynthesisSampleSize extends BackboneElement {
    description?: string;
    numberOfParticipants?: number;
    numberOfStudies?: number;
}

export interface EffectEvidenceSynthesis extends DomainResource {
    approvalDate?: string;
    _approvalDate?: Element;
    author?: ContactDetail[];
    certainty?: EffectEvidenceSynthesisCertainty[];
    contact?: ContactDetail[];
    copyright?: string;
    _copyright?: Element;
    date?: string;
    _date?: Element;
    description?: string;
    _description?: Element;
    editor?: ContactDetail[];
    effectEstimate?: EffectEvidenceSynthesisEffectEstimate[];
    effectivePeriod?: Period;
    endorser?: ContactDetail[];
    exposure: Reference<'EvidenceVariable'>;
    exposureAlternative: Reference<'EvidenceVariable'>;
    identifier?: Identifier[];
    jurisdiction?: CodeableConcept[];
    lastReviewDate?: string;
    _lastReviewDate?: Element;
    name?: string;
    _name?: Element;
    note?: Annotation[];
    outcome: Reference<'EvidenceVariable'>;
    population: Reference<'EvidenceVariable'>;
    publisher?: string;
    _publisher?: Element;
    relatedArtifact?: RelatedArtifact[];
    resultsByExposure?: EffectEvidenceSynthesisResultsByExposure[];
    reviewer?: ContactDetail[];
    sampleSize?: EffectEvidenceSynthesisSampleSize;
    status: 'draft' | 'active' | 'retired' | 'unknown';
    _status?: Element;
    studyType?: CodeableConcept;
    synthesisType?: CodeableConcept;
    title?: string;
    _title?: Element;
    topic?: CodeableConcept[];
    url?: string;
    _url?: Element;
    useContext?: UsageContext[];
    version?: string;
    _version?: Element;
}

