// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { CodeableConcept } from './CodeableConcept';
import { Element } from './Element';
import { Period } from './Period';
import { Reference } from './Reference';

export interface Identifier extends Element {
    assigner?: Reference<'Organization'>;
    period?: Period;
    system?: string;
    _system?: Element;
    type?: CodeableConcept;
    use?: 'usual' | 'official' | 'temp' | 'secondary' | 'old';
    _use?: Element;
    value?: string;
    _value?: Element;
}

