// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { BackboneElement } from './BackboneElement';
import { CodeableConcept } from './CodeableConcept';
import { Coding } from './Coding';
import { ContactPoint } from './ContactPoint';
import { DomainResource } from './DomainResource';
import { Reference } from './Reference';


export interface MessageHeaderDestination extends BackboneElement {
    endpoint: string;
    name?: string;
    receiver?: Reference<'Organization' | 'Practitioner' | 'PractitionerRole'>;
    target?: Reference<'Device'>;
}

export interface MessageHeaderResponse extends BackboneElement {
    code: 'ok' | 'transient-error' | 'fatal-error';
    details?: Reference<'OperationOutcome'>;
    identifier: string;
}

export interface MessageHeaderSource extends BackboneElement {
    contact?: ContactPoint;
    endpoint: string;
    name?: string;
    software?: string;
    version?: string;
}

export interface MessageHeader extends DomainResource {
    author?: Reference<'Practitioner' | 'PractitionerRole'>;
    definition?: string;
    _definition?: Element;
    destination?: MessageHeaderDestination[];
    enterer?: Reference<'Practitioner' | 'PractitionerRole'>;
    eventCoding?: Coding;
    eventUri?: string;
    _eventUri?: Element;
    focus?: Reference<'Resource'>[];
    reason?: CodeableConcept;
    response?: MessageHeaderResponse;
    responsible?: Reference<'Organization' | 'Practitioner' | 'PractitionerRole'>;
    sender?: Reference<'Organization' | 'Practitioner' | 'PractitionerRole'>;
    source: MessageHeaderSource;
}

