// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { CodeableConcept } from './CodeableConcept';
import { ContactPoint } from './ContactPoint';
import { DomainResource } from './DomainResource';
import { Identifier } from './Identifier';
import { Period } from './Period';
import { Reference } from './Reference';

export interface OrganizationAffiliation extends DomainResource {
    active?: boolean;
    _active?: Element;
    code?: CodeableConcept[];
    endpoint?: Reference<'Endpoint'>[];
    healthcareService?: Reference<'HealthcareService'>[];
    identifier?: Identifier[];
    location?: Reference<'Location'>[];
    network?: Reference<'Organization'>[];
    organization?: Reference<'Organization'>;
    participatingOrganization?: Reference<'Organization'>;
    period?: Period;
    specialty?: CodeableConcept[];
    telecom?: ContactPoint[];
}

