// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import { BackboneElement } from './BackboneElement';
import { CodeableConcept } from './CodeableConcept';
import { DomainResource } from './DomainResource';
import { Identifier } from './Identifier';
import { Period } from './Period';
import { Quantity } from './Quantity';
import { Reference } from './Reference';
import { Timing } from './Timing';


export interface SupplyDeliverySuppliedItem extends BackboneElement {
    itemCodeableConcept?: CodeableConcept;
    itemReference?: Reference<'Device' | 'Medication' | 'Substance'>;
    quantity?: Quantity;
}

export interface SupplyDelivery extends DomainResource {
    basedOn?: Reference<'SupplyRequest'>[];
    destination?: Reference<'Location'>;
    identifier?: Identifier[];
    occurrenceDateTime?: string;
    _occurrenceDateTime?: Element;
    occurrencePeriod?: Period;
    occurrenceTiming?: Timing;
    partOf?: Reference<'Contract' | 'SupplyDelivery'>[];
    patient?: Reference<'Patient'>;
    receiver?: Reference<'Practitioner' | 'PractitionerRole'>[];
    status?: 'in-progress' | 'completed' | 'abandoned' | 'entered-in-error';
    _status?: Element;
    suppliedItem?: SupplyDeliverySuppliedItem;
    supplier?: Reference<'Organization' | 'Practitioner' | 'PractitionerRole'>;
    type?: CodeableConcept;
}

