// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { BackboneElement } from "../hl7-fhir-r4-core/BackboneElement";
import type { Identifier } from "../hl7-fhir-r4-core/Identifier";
import type { Resource } from "../hl7-fhir-r4-core/Resource";
import type { Signature } from "../hl7-fhir-r4-core/Signature";

import type { Element } from "../hl7-fhir-r4-core/Element";
export type { BackboneElement } from "../hl7-fhir-r4-core/BackboneElement";
export type { Identifier } from "../hl7-fhir-r4-core/Identifier";
export type { Signature } from "../hl7-fhir-r4-core/Signature";

export interface BundleEntry extends BackboneElement {
    fullUrl?: string;
    link?: BundleLink[];
    request?: BundleEntryRequest;
    resource?: Resource;
    response?: BundleEntryResponse;
    search?: BundleEntrySearch;
}

export interface BundleEntryRequest extends BackboneElement {
    ifMatch?: string;
    ifModifiedSince?: string;
    ifNoneExist?: string;
    ifNoneMatch?: string;
    method: ("GET" | "HEAD" | "POST" | "PUT" | "DELETE" | "PATCH");
    url: string;
}

export interface BundleEntryResponse extends BackboneElement {
    etag?: string;
    lastModified?: string;
    location?: string;
    outcome?: Resource;
    status: string;
}

export interface BundleEntrySearch extends BackboneElement {
    mode?: ("match" | "include" | "outcome");
    score?: number;
}

export interface BundleLink extends BackboneElement {
    relation: string;
    url: string;
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/Bundle (pkg: hl7.fhir.r4.core#4.0.1)
export interface Bundle extends Resource {
    resourceType: "Bundle";

    entry?: BundleEntry[];
    identifier?: Identifier;
    link?: BundleLink[];
    signature?: Signature;
    timestamp?: string;
    _timestamp?: Element;
    total?: number;
    _total?: Element;
    type: ("document" | "message" | "transaction" | "transaction-response" | "batch" | "batch-response" | "history" | "searchset" | "collection");
    _type?: Element;
}
export const isBundle = (resource: unknown): resource is Bundle => {
    return resource !== null && typeof resource === "object" && (resource as {resourceType: string}).resourceType === "Bundle";
}
