// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Extension } from "../hl7-fhir-r4-core/Extension";
import type { Narrative } from "../hl7-fhir-r4-core/Narrative";
import type { Resource } from "../hl7-fhir-r4-core/Resource";

export type { Extension } from "../hl7-fhir-r4-core/Extension";
export type { Narrative } from "../hl7-fhir-r4-core/Narrative";

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/DomainResource (pkg: hl7.fhir.r4.core#4.0.1)
export interface DomainResource extends Resource {
    resourceType: "DomainResource" | "Observation" | "OperationOutcome" | "Patient";

    contained?: Resource[];
    extension?: Extension[];
    modifierExtension?: Extension[];
    text?: Narrative;
}
export const isDomainResource = (resource: unknown): resource is DomainResource => {
    return resource !== null && typeof resource === "object" && (resource as {resourceType: string}).resourceType === "DomainResource";
}
