// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Meta } from "../hl7-fhir-r4-core/Meta";

import type { Element } from "../hl7-fhir-r4-core/Element";
export type { Meta } from "../hl7-fhir-r4-core/Meta";

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/Resource (pkg: hl7.fhir.r4.core#4.0.1)
export interface Resource {
    resourceType: "Bundle" | "DomainResource" | "Observation" | "OperationOutcome" | "Patient" | "Resource";

    id?: string;
    _id?: Element;
    implicitRules?: string;
    _implicitRules?: Element;
    language?: ("ar" | "bn" | "cs" | "da" | "de" | "de-AT" | "de-CH" | "de-DE" | "el" | "en" | "en-AU" | "en-CA" | "en-GB" | "en-IN" | "en-NZ" | "en-SG" | "en-US" | "es" | "es-AR" | "es-ES" | "es-UY" | "fi" | "fr" | "fr-BE" | "fr-CH" | "fr-FR" | "fy" | "fy-NL" | "hi" | "hr" | "it" | "it-CH" | "it-IT" | "ja" | "ko" | "nl" | "nl-BE" | "nl-NL" | "no" | "no-NO" | "pa" | "pl" | "pt" | "pt-BR" | "ru" | "ru-RU" | "sr" | "sr-RS" | "sv" | "sv-SE" | "te" | "zh" | "zh-CN" | "zh-HK" | "zh-SG" | "zh-TW" | string);
    _language?: Element;
    meta?: Meta;
}
export const isResource = (resource: unknown): resource is Resource => {
    return resource !== null && typeof resource === "object" && (resource as {resourceType: string}).resourceType === "Resource";
}
