apiVersion: 1

datasources:
  - name: aidbox-logs
    type: elasticsearch
    access: proxy
    database: "*"
    url: http://es:9200
    jsonData:
      interval: Daily
      timeField: "ts"
      esVersion: "8.17.2"
      logMessageField: message
      logLevelField: fields.level
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
