// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Element } from "../hl7-fhir-r4-core/Element";

export type { Element } from "../hl7-fhir-r4-core/Element";

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/Money (pkg: hl7.fhir.r4.core#4.0.1)
export interface Money extends Element {
    currency?: string;
    _currency?: Element;
    value?: number;
    _value?: Element;
}
