// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Age } from "../hl7-fhir-r4-core/Age";
import type { Annotation } from "../hl7-fhir-r4-core/Annotation";
import type { BackboneElement } from "../hl7-fhir-r4-core/BackboneElement";
import type { CodeableConcept } from "../hl7-fhir-r4-core/CodeableConcept";
import type { DomainResource } from "../hl7-fhir-r4-core/DomainResource";
import type { Identifier } from "../hl7-fhir-r4-core/Identifier";
import type { Period } from "../hl7-fhir-r4-core/Period";
import type { Range } from "../hl7-fhir-r4-core/Range";
import type { Reference } from "../hl7-fhir-r4-core/Reference";

export type { Age } from "../hl7-fhir-r4-core/Age";
export type { Annotation } from "../hl7-fhir-r4-core/Annotation";
export type { BackboneElement } from "../hl7-fhir-r4-core/BackboneElement";
export type { CodeableConcept } from "../hl7-fhir-r4-core/CodeableConcept";
export type { Identifier } from "../hl7-fhir-r4-core/Identifier";
export type { Period } from "../hl7-fhir-r4-core/Period";
export type { Range } from "../hl7-fhir-r4-core/Range";
export type { Reference } from "../hl7-fhir-r4-core/Reference";

export interface AllergyIntoleranceReaction extends BackboneElement {
    description?: string;
    exposureRoute?: CodeableConcept;
    manifestation: CodeableConcept[];
    note?: Annotation[];
    onset?: string;
    severity?: ("mild" | "moderate" | "severe");
    substance?: CodeableConcept;
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/AllergyIntolerance
export interface AllergyIntolerance extends DomainResource {
    resourceType: "AllergyIntolerance";

    asserter?: Reference<"Patient" | "Practitioner" | "PractitionerRole" | "RelatedPerson">;
    category?: ("food" | "medication" | "environment" | "biologic")[];
    _category?: Element;
    clinicalStatus?: CodeableConcept;
    code?: CodeableConcept;
    criticality?: ("low" | "high" | "unable-to-assess");
    _criticality?: Element;
    encounter?: Reference<"Encounter">;
    identifier?: Identifier[];
    lastOccurrence?: string;
    _lastOccurrence?: Element;
    note?: Annotation[];
    onsetAge?: Age;
    onsetDateTime?: string;
    _onsetDateTime?: Element;
    onsetPeriod?: Period;
    onsetRange?: Range;
    onsetString?: string;
    _onsetString?: Element;
    patient: Reference<"Patient">;
    reaction?: AllergyIntoleranceReaction[];
    recordedDate?: string;
    _recordedDate?: Element;
    recorder?: Reference<"Patient" | "Practitioner" | "PractitionerRole" | "RelatedPerson">;
    type?: ("allergy" | "intolerance");
    _type?: Element;
    verificationStatus?: CodeableConcept;
}
export const isAllergyIntolerance = (resource: unknown): resource is AllergyIntolerance => {
    return resource !== null && typeof resource === "object" && (resource as {resourceType: string}).resourceType === "AllergyIntolerance";
}
