// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { CodeableConcept } from "../hl7-fhir-r4-core/CodeableConcept";
import type { DomainResource } from "../hl7-fhir-r4-core/DomainResource";
import type { Identifier } from "../hl7-fhir-r4-core/Identifier";
import type { Reference } from "../hl7-fhir-r4-core/Reference";

export type { CodeableConcept } from "../hl7-fhir-r4-core/CodeableConcept";
export type { Identifier } from "../hl7-fhir-r4-core/Identifier";
export type { Reference } from "../hl7-fhir-r4-core/Reference";

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/AppointmentResponse
export interface AppointmentResponse extends DomainResource {
    resourceType: "AppointmentResponse";

    actor?: Reference<"Device" | "HealthcareService" | "Location" | "Patient" | "Practitioner" | "PractitionerRole" | "RelatedPerson">;
    appointment: Reference<"Appointment">;
    comment?: string;
    _comment?: Element;
    end?: string;
    _end?: Element;
    identifier?: Identifier[];
    participantStatus: ("accepted" | "declined" | "tentative" | "needs-action");
    _participantStatus?: Element;
    participantType?: CodeableConcept[];
    start?: string;
    _start?: Element;
}
export const isAppointmentResponse = (resource: unknown): resource is AppointmentResponse => {
    return resource !== null && typeof resource === "object" && (resource as {resourceType: string}).resourceType === "AppointmentResponse";
}
