// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { BackboneElement } from "../hl7-fhir-r4-core/BackboneElement";
import type { CodeableConcept } from "../hl7-fhir-r4-core/CodeableConcept";
import type { Coding } from "../hl7-fhir-r4-core/Coding";
import type { DomainResource } from "../hl7-fhir-r4-core/DomainResource";
import type { Period } from "../hl7-fhir-r4-core/Period";
import type { Reference } from "../hl7-fhir-r4-core/Reference";

export type { BackboneElement } from "../hl7-fhir-r4-core/BackboneElement";
export type { CodeableConcept } from "../hl7-fhir-r4-core/CodeableConcept";
export type { Coding } from "../hl7-fhir-r4-core/Coding";
export type { Period } from "../hl7-fhir-r4-core/Period";
export type { Reference } from "../hl7-fhir-r4-core/Reference";

export interface AuditEventAgent extends BackboneElement {
    altId?: string;
    location?: Reference<"Location">;
    media?: Coding;
    name?: string;
    network?: AuditEventAgentNetwork;
    policy?: string[];
    purposeOfUse?: CodeableConcept[];
    requestor: boolean;
    role?: CodeableConcept[];
    type?: CodeableConcept;
    who?: Reference<"Device" | "Organization" | "Patient" | "Practitioner" | "PractitionerRole" | "RelatedPerson">;
}

export interface AuditEventAgentNetwork extends BackboneElement {
    address?: string;
    type?: ("1" | "2" | "3" | "4" | "5");
}

export interface AuditEventEntity extends BackboneElement {
    description?: string;
    detail?: AuditEventEntityDetail[];
    lifecycle?: Coding;
    name?: string;
    query?: string;
    role?: Coding;
    securityLabel?: Coding[];
    type?: Coding;
    what?: Reference<"Resource">;
}

export interface AuditEventEntityDetail extends BackboneElement {
    type: string;
    valueBase64Binary?: string;
    valueString?: string;
}

export interface AuditEventSource extends BackboneElement {
    observer: Reference<"Device" | "Organization" | "Patient" | "Practitioner" | "PractitionerRole" | "RelatedPerson">;
    site?: string;
    type?: Coding[];
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/AuditEvent
export interface AuditEvent extends DomainResource {
    resourceType: "AuditEvent";

    action?: ("C" | "R" | "U" | "D" | "E");
    _action?: Element;
    agent: AuditEventAgent[];
    entity?: AuditEventEntity[];
    outcome?: ("0" | "4" | "8" | "12");
    _outcome?: Element;
    outcomeDesc?: string;
    _outcomeDesc?: Element;
    period?: Period;
    purposeOfEvent?: CodeableConcept[];
    recorded: string;
    _recorded?: Element;
    source: AuditEventSource;
    subtype?: Coding[];
    type: Coding;
}
export const isAuditEvent = (resource: unknown): resource is AuditEvent => {
    return resource !== null && typeof resource === "object" && (resource as {resourceType: string}).resourceType === "AuditEvent";
}
