// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { CodeableConcept } from "../hl7-fhir-r4-core/CodeableConcept";
import type { DomainResource } from "../hl7-fhir-r4-core/DomainResource";
import type { Identifier } from "../hl7-fhir-r4-core/Identifier";
import type { Reference } from "../hl7-fhir-r4-core/Reference";

export type { CodeableConcept } from "../hl7-fhir-r4-core/CodeableConcept";
export type { Identifier } from "../hl7-fhir-r4-core/Identifier";
export type { Reference } from "../hl7-fhir-r4-core/Reference";

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/Basic
export interface Basic extends DomainResource {
    resourceType: "Basic";

    author?: Reference<"Organization" | "Patient" | "Practitioner" | "PractitionerRole" | "RelatedPerson">;
    code: CodeableConcept;
    created?: string;
    _created?: Element;
    identifier?: Identifier[];
    subject?: Reference<"Resource">;
}
export const isBasic = (resource: unknown): resource is Basic => {
    return resource !== null && typeof resource === "object" && (resource as {resourceType: string}).resourceType === "Basic";
}
