// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { BackboneElement } from "../hl7-fhir-r4-core/BackboneElement";
import type { CodeableConcept } from "../hl7-fhir-r4-core/CodeableConcept";
import type { DomainResource } from "../hl7-fhir-r4-core/DomainResource";
import type { Identifier } from "../hl7-fhir-r4-core/Identifier";
import type { Period } from "../hl7-fhir-r4-core/Period";
import type { Reference } from "../hl7-fhir-r4-core/Reference";

export type { BackboneElement } from "../hl7-fhir-r4-core/BackboneElement";
export type { CodeableConcept } from "../hl7-fhir-r4-core/CodeableConcept";
export type { Identifier } from "../hl7-fhir-r4-core/Identifier";
export type { Period } from "../hl7-fhir-r4-core/Period";
export type { Reference } from "../hl7-fhir-r4-core/Reference";

export interface BiologicallyDerivedProductCollection extends BackboneElement {
    collectedDateTime?: string;
    collectedPeriod?: Period;
    collector?: Reference<"Practitioner" | "PractitionerRole">;
    source?: Reference<"Organization" | "Patient">;
}

export interface BiologicallyDerivedProductManipulation extends BackboneElement {
    description?: string;
    timeDateTime?: string;
    timePeriod?: Period;
}

export interface BiologicallyDerivedProductProcessing extends BackboneElement {
    additive?: Reference<"Substance">;
    description?: string;
    procedure?: CodeableConcept;
    timeDateTime?: string;
    timePeriod?: Period;
}

export interface BiologicallyDerivedProductStorage extends BackboneElement {
    description?: string;
    duration?: Period;
    scale?: ("farenheit" | "celsius" | "kelvin");
    temperature?: number;
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/BiologicallyDerivedProduct
export interface BiologicallyDerivedProduct extends DomainResource {
    resourceType: "BiologicallyDerivedProduct";

    collection?: BiologicallyDerivedProductCollection;
    identifier?: Identifier[];
    manipulation?: BiologicallyDerivedProductManipulation;
    parent?: Reference<"BiologicallyDerivedProduct">[];
    processing?: BiologicallyDerivedProductProcessing[];
    productCategory?: ("organ" | "tissue" | "fluid" | "cells" | "biologicalAgent");
    _productCategory?: Element;
    productCode?: CodeableConcept;
    quantity?: number;
    _quantity?: Element;
    request?: Reference<"ServiceRequest">[];
    status?: ("available" | "unavailable");
    _status?: Element;
    storage?: BiologicallyDerivedProductStorage[];
}
export const isBiologicallyDerivedProduct = (resource: unknown): resource is BiologicallyDerivedProduct => {
    return resource !== null && typeof resource === "object" && (resource as {resourceType: string}).resourceType === "BiologicallyDerivedProduct";
}
