// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { BackboneElement } from "../hl7-fhir-r4-core/BackboneElement";
import type { CodeableConcept } from "../hl7-fhir-r4-core/CodeableConcept";
import type { Identifier } from "../hl7-fhir-r4-core/Identifier";
import type { Reference } from "../hl7-fhir-r4-core/Reference";
import type { RelatedArtifact } from "../hl7-fhir-r4-core/RelatedArtifact";
import type { RequestGroup } from "../hl7-fhir-r4-core/RequestGroup";
import type { RequestGroupAction } from "../hl7-fhir-r4-core/RequestGroup";
import type { RequestGroupActionCondition } from "../hl7-fhir-r4-core/RequestGroup";

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/cdshooksrequestgroup
export interface CDS_Hooks_RequestGroup {
    __profileUrl: "http://hl7.org/fhir/StructureDefinition/cdshooksrequestgroup";

    identifier: Identifier[];
    instantiatesUri: string[];
    priority?: ("routine" | "urgent" | "asap" | "stat");
    subject?: Reference<'Group' | 'Patient'>;
    authoredOn?: string;
    author?: Reference<'Device' | 'Practitioner' | 'PractitionerRole'>;
    action?: RequestGroupAction[];
}

export const attach_CDS_Hooks_RequestGroup_to_RequestGroup = (resource: RequestGroup, profile: CDS_Hooks_RequestGroup): RequestGroup => {
    return {
        ...resource,
        meta: {
            profile: ['http://hl7.org/fhir/StructureDefinition/cdshooksrequestgroup']
        },
        identifier: profile.identifier,
        instantiatesUri: profile.instantiatesUri,
        priority: profile.priority,
        subject: profile.subject,
        authoredOn: profile.authoredOn,
        author: profile.author,
        action: profile.action,
    }
}

export const extract_CDS_Hooks_RequestGroup_from_RequestGroup = (resource: RequestGroup): CDS_Hooks_RequestGroup => {
    if (resource.identifier === undefined) {
        throw new Error("'identifier' is required for http://hl7.org/fhir/StructureDefinition/cdshooksrequestgroup");
    }
    if (resource.instantiatesUri === undefined) {
        throw new Error("'instantiatesUri' is required for http://hl7.org/fhir/StructureDefinition/cdshooksrequestgroup");
    }
    return {
        __profileUrl: 'http://hl7.org/fhir/StructureDefinition/cdshooksrequestgroup',
        identifier: resource.identifier,
        instantiatesUri: resource.instantiatesUri,
        priority: resource.priority,
        subject: resource.subject,
        authoredOn: resource.authoredOn,
        author: resource.author,
        action: resource.action,
    }
}
