// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Annotation } from "../hl7-fhir-r4-core/Annotation";
import type { Attachment } from "../hl7-fhir-r4-core/Attachment";
import type { BackboneElement } from "../hl7-fhir-r4-core/BackboneElement";
import type { CodeableConcept } from "../hl7-fhir-r4-core/CodeableConcept";
import type { DomainResource } from "../hl7-fhir-r4-core/DomainResource";
import type { Identifier } from "../hl7-fhir-r4-core/Identifier";
import type { Period } from "../hl7-fhir-r4-core/Period";
import type { Reference } from "../hl7-fhir-r4-core/Reference";

export type { Annotation } from "../hl7-fhir-r4-core/Annotation";
export type { Attachment } from "../hl7-fhir-r4-core/Attachment";
export type { BackboneElement } from "../hl7-fhir-r4-core/BackboneElement";
export type { CodeableConcept } from "../hl7-fhir-r4-core/CodeableConcept";
export type { Identifier } from "../hl7-fhir-r4-core/Identifier";
export type { Period } from "../hl7-fhir-r4-core/Period";
export type { Reference } from "../hl7-fhir-r4-core/Reference";

export interface CommunicationRequestPayload extends BackboneElement {
    contentAttachment?: Attachment;
    contentReference?: Reference<"Resource">;
    contentString?: string;
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/CommunicationRequest
export interface CommunicationRequest extends DomainResource {
    resourceType: "CommunicationRequest";

    about?: Reference<"Resource">[];
    authoredOn?: string;
    _authoredOn?: Element;
    basedOn?: Reference<"Resource">[];
    category?: CodeableConcept[];
    doNotPerform?: boolean;
    _doNotPerform?: Element;
    encounter?: Reference<"Encounter">;
    groupIdentifier?: Identifier;
    identifier?: Identifier[];
    medium?: CodeableConcept[];
    note?: Annotation[];
    occurrenceDateTime?: string;
    _occurrenceDateTime?: Element;
    occurrencePeriod?: Period;
    payload?: CommunicationRequestPayload[];
    priority?: ("routine" | "urgent" | "asap" | "stat");
    _priority?: Element;
    reasonCode?: CodeableConcept[];
    reasonReference?: Reference<"Condition" | "DiagnosticReport" | "DocumentReference" | "Observation">[];
    recipient?: Reference<"CareTeam" | "Device" | "Group" | "HealthcareService" | "Organization" | "Patient" | "Practitioner" | "PractitionerRole" | "RelatedPerson">[];
    replaces?: Reference<"CommunicationRequest">[];
    requester?: Reference<"Device" | "Organization" | "Patient" | "Practitioner" | "PractitionerRole" | "RelatedPerson">;
    sender?: Reference<"Device" | "HealthcareService" | "Organization" | "Patient" | "Practitioner" | "PractitionerRole" | "RelatedPerson">;
    status: ("draft" | "active" | "on-hold" | "revoked" | "completed" | "entered-in-error" | "unknown");
    _status?: Element;
    statusReason?: CodeableConcept;
    subject?: Reference<"Group" | "Patient">;
}
export const isCommunicationRequest = (resource: unknown): resource is CommunicationRequest => {
    return resource !== null && typeof resource === "object" && (resource as {resourceType: string}).resourceType === "CommunicationRequest";
}
