// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { CodeableConcept } from "../hl7-fhir-r4-core/CodeableConcept";
import type { DiagnosticReport } from "../hl7-fhir-r4-core/DiagnosticReport";
import type { Extension } from "../hl7-fhir-r4-core/Extension";

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/diagnosticreport-genetics
export interface DiagnosticReport_Genetics {
    __profileUrl: "http://hl7.org/fhir/StructureDefinition/diagnosticreport-genetics";

    extension?: Extension[];
    conclusionCode?: CodeableConcept[];
}

export const attach_DiagnosticReport_Genetics_to_DiagnosticReport = (resource: DiagnosticReport, profile: DiagnosticReport_Genetics): DiagnosticReport => {
    return {
        ...resource,
        meta: {
            profile: ['http://hl7.org/fhir/StructureDefinition/diagnosticreport-genetics']
        },
        extension: profile.extension,
        conclusionCode: profile.conclusionCode,
    }
}

export const extract_DiagnosticReport_Genetics_from_DiagnosticReport = (resource: DiagnosticReport): DiagnosticReport_Genetics => {
    return {
        __profileUrl: 'http://hl7.org/fhir/StructureDefinition/diagnosticreport-genetics',
        extension: resource.extension,
        conclusionCode: resource.conclusionCode,
    }
}
