// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { CodeableConcept } from "../hl7-fhir-r4-core/CodeableConcept";
import type { ContactDetail } from "../hl7-fhir-r4-core/ContactDetail";
import type { DomainResource } from "../hl7-fhir-r4-core/DomainResource";
import type { Identifier } from "../hl7-fhir-r4-core/Identifier";
import type { Period } from "../hl7-fhir-r4-core/Period";
import type { Reference } from "../hl7-fhir-r4-core/Reference";
import type { RelatedArtifact } from "../hl7-fhir-r4-core/RelatedArtifact";
import type { TriggerDefinition } from "../hl7-fhir-r4-core/TriggerDefinition";
import type { UsageContext } from "../hl7-fhir-r4-core/UsageContext";

export type { CodeableConcept } from "../hl7-fhir-r4-core/CodeableConcept";
export type { ContactDetail } from "../hl7-fhir-r4-core/ContactDetail";
export type { Identifier } from "../hl7-fhir-r4-core/Identifier";
export type { Period } from "../hl7-fhir-r4-core/Period";
export type { Reference } from "../hl7-fhir-r4-core/Reference";
export type { RelatedArtifact } from "../hl7-fhir-r4-core/RelatedArtifact";
export type { TriggerDefinition } from "../hl7-fhir-r4-core/TriggerDefinition";
export type { UsageContext } from "../hl7-fhir-r4-core/UsageContext";

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/EventDefinition
export interface EventDefinition extends DomainResource {
    resourceType: "EventDefinition";

    approvalDate?: string;
    _approvalDate?: Element;
    author?: ContactDetail[];
    contact?: ContactDetail[];
    copyright?: string;
    _copyright?: Element;
    date?: string;
    _date?: Element;
    description?: string;
    _description?: Element;
    editor?: ContactDetail[];
    effectivePeriod?: Period;
    endorser?: ContactDetail[];
    experimental?: boolean;
    _experimental?: Element;
    identifier?: Identifier[];
    jurisdiction?: CodeableConcept[];
    lastReviewDate?: string;
    _lastReviewDate?: Element;
    name?: string;
    _name?: Element;
    publisher?: string;
    _publisher?: Element;
    purpose?: string;
    _purpose?: Element;
    relatedArtifact?: RelatedArtifact[];
    reviewer?: ContactDetail[];
    status: ("draft" | "active" | "retired" | "unknown");
    _status?: Element;
    subjectCodeableConcept?: CodeableConcept;
    subjectReference?: Reference<"Group">;
    subtitle?: string;
    _subtitle?: Element;
    title?: string;
    _title?: Element;
    topic?: CodeableConcept[];
    trigger: TriggerDefinition[];
    url?: string;
    _url?: Element;
    usage?: string;
    _usage?: Element;
    useContext?: UsageContext[];
    version?: string;
    _version?: Element;
}
export const isEventDefinition = (resource: unknown): resource is EventDefinition => {
    return resource !== null && typeof resource === "object" && (resource as {resourceType: string}).resourceType === "EventDefinition";
}
