// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Annotation } from "../hl7-fhir-r4-core/Annotation";
import type { BackboneElement } from "../hl7-fhir-r4-core/BackboneElement";
import type { CodeableConcept } from "../hl7-fhir-r4-core/CodeableConcept";
import type { Observation } from "../hl7-fhir-r4-core/Observation";
import type { ObservationReferenceRange } from "../hl7-fhir-r4-core/Observation";
import type { Quantity } from "../hl7-fhir-r4-core/Quantity";
import type { Range } from "../hl7-fhir-r4-core/Range";
import type { Reference } from "../hl7-fhir-r4-core/Reference";

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/triglyceride
export interface Example_Lipid_Profile {
    __profileUrl: "http://hl7.org/fhir/StructureDefinition/triglyceride";

    code: CodeableConcept;
    valueQuantity?: Quantity;
    interpretation?: CodeableConcept[];
    note?: Annotation[];
    referenceRange: ObservationReferenceRange[];
    hasMember?: Reference<'MolecularSequence' | 'Observation' | 'QuestionnaireResponse'>[];
    derivedFrom?: Reference<'DocumentReference' | 'ImagingStudy' | 'Media' | 'MolecularSequence' | 'Observation' | 'QuestionnaireResponse'>[];
}

export const attach_Example_Lipid_Profile_to_Observation = (resource: Observation, profile: Example_Lipid_Profile): Observation => {
    return {
        ...resource,
        meta: {
            profile: ['http://hl7.org/fhir/StructureDefinition/triglyceride']
        },
        code: profile.code,
        valueQuantity: profile.valueQuantity,
        interpretation: profile.interpretation,
        note: profile.note,
        referenceRange: profile.referenceRange,
        hasMember: profile.hasMember,
        derivedFrom: profile.derivedFrom,
    }
}

export const extract_Example_Lipid_Profile_from_Observation = (resource: Observation): Example_Lipid_Profile => {
    if (resource.referenceRange === undefined) {
        throw new Error("'referenceRange' is required for http://hl7.org/fhir/StructureDefinition/triglyceride");
    }
    return {
        __profileUrl: 'http://hl7.org/fhir/StructureDefinition/triglyceride',
        code: resource.code,
        valueQuantity: resource.valueQuantity,
        interpretation: resource.interpretation,
        note: resource.note,
        referenceRange: resource.referenceRange,
        hasMember: resource.hasMember,
        derivedFrom: resource.derivedFrom,
    }
}
