// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { BackboneElement } from "../hl7-fhir-r4-core/BackboneElement";
import type { CodeableConcept } from "../hl7-fhir-r4-core/CodeableConcept";
import type { DomainResource } from "../hl7-fhir-r4-core/DomainResource";
import type { Identifier } from "../hl7-fhir-r4-core/Identifier";
import type { Ratio } from "../hl7-fhir-r4-core/Ratio";
import type { Reference } from "../hl7-fhir-r4-core/Reference";

export type { BackboneElement } from "../hl7-fhir-r4-core/BackboneElement";
export type { CodeableConcept } from "../hl7-fhir-r4-core/CodeableConcept";
export type { Identifier } from "../hl7-fhir-r4-core/Identifier";
export type { Ratio } from "../hl7-fhir-r4-core/Ratio";
export type { Reference } from "../hl7-fhir-r4-core/Reference";

export interface MedicinalProductIngredientSpecifiedSubstance extends BackboneElement {
    code: CodeableConcept;
    confidentiality?: CodeableConcept;
    group: CodeableConcept;
    strength?: MedicinalProductIngredientSpecifiedSubstanceStrength[];
}

export interface MedicinalProductIngredientSpecifiedSubstanceStrength extends BackboneElement {
    concentration?: Ratio;
    concentrationLowLimit?: Ratio;
    country?: CodeableConcept[];
    measurementPoint?: string;
    presentation: Ratio;
    presentationLowLimit?: Ratio;
    referenceStrength?: MedicinalProductIngredientSpecifiedSubstanceStrengthReferenceStrength[];
}

export interface MedicinalProductIngredientSpecifiedSubstanceStrengthReferenceStrength extends BackboneElement {
    country?: CodeableConcept[];
    measurementPoint?: string;
    strength: Ratio;
    strengthLowLimit?: Ratio;
    substance?: CodeableConcept;
}

export interface MedicinalProductIngredientSubstance extends BackboneElement {
    code: CodeableConcept;
    strength?: MedicinalProductIngredientSpecifiedSubstanceStrength[];
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/MedicinalProductIngredient
export interface MedicinalProductIngredient extends DomainResource {
    resourceType: "MedicinalProductIngredient";

    allergenicIndicator?: boolean;
    _allergenicIndicator?: Element;
    identifier?: Identifier;
    manufacturer?: Reference<"Organization">[];
    role: CodeableConcept;
    specifiedSubstance?: MedicinalProductIngredientSpecifiedSubstance[];
    substance?: MedicinalProductIngredientSubstance;
}
export const isMedicinalProductIngredient = (resource: unknown): resource is MedicinalProductIngredient => {
    return resource !== null && typeof resource === "object" && (resource as {resourceType: string}).resourceType === "MedicinalProductIngredient";
}
