// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { BackboneElement } from "../hl7-fhir-r4-core/BackboneElement";
import type { CodeableConcept } from "../hl7-fhir-r4-core/CodeableConcept";
import type { DomainResource } from "../hl7-fhir-r4-core/DomainResource";

export type { BackboneElement } from "../hl7-fhir-r4-core/BackboneElement";
export type { CodeableConcept } from "../hl7-fhir-r4-core/CodeableConcept";

export interface OperationOutcomeIssue extends BackboneElement {
    code: ("invalid" | "structure" | "required" | "value" | "invariant" | "security" | "login" | "unknown" | "expired" | "forbidden" | "suppressed" | "processing" | "not-supported" | "duplicate" | "multiple-matches" | "not-found" | "deleted" | "too-long" | "code-invalid" | "extension" | "too-costly" | "business-rule" | "conflict" | "transient" | "lock-error" | "no-store" | "exception" | "timeout" | "incomplete" | "throttled" | "informational");
    details?: CodeableConcept;
    diagnostics?: string;
    expression?: string[];
    location?: string[];
    severity: ("fatal" | "error" | "warning" | "information");
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/OperationOutcome
export interface OperationOutcome extends DomainResource {
    resourceType: "OperationOutcome";

    issue: OperationOutcomeIssue[];
}
export const isOperationOutcome = (resource: unknown): resource is OperationOutcome => {
    return resource !== null && typeof resource === "object" && (resource as {resourceType: string}).resourceType === "OperationOutcome";
}
