// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { CodeableConcept } from "../hl7-fhir-r4-core/CodeableConcept";
import type { ContactPoint } from "../hl7-fhir-r4-core/ContactPoint";
import type { DomainResource } from "../hl7-fhir-r4-core/DomainResource";
import type { Identifier } from "../hl7-fhir-r4-core/Identifier";
import type { Period } from "../hl7-fhir-r4-core/Period";
import type { Reference } from "../hl7-fhir-r4-core/Reference";

export type { CodeableConcept } from "../hl7-fhir-r4-core/CodeableConcept";
export type { ContactPoint } from "../hl7-fhir-r4-core/ContactPoint";
export type { Identifier } from "../hl7-fhir-r4-core/Identifier";
export type { Period } from "../hl7-fhir-r4-core/Period";
export type { Reference } from "../hl7-fhir-r4-core/Reference";

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/OrganizationAffiliation
export interface OrganizationAffiliation extends DomainResource {
    resourceType: "OrganizationAffiliation";

    active?: boolean;
    _active?: Element;
    code?: CodeableConcept[];
    endpoint?: Reference<"Endpoint">[];
    healthcareService?: Reference<"HealthcareService">[];
    identifier?: Identifier[];
    location?: Reference<"Location">[];
    network?: Reference<"Organization">[];
    organization?: Reference<"Organization">;
    participatingOrganization?: Reference<"Organization">;
    period?: Period;
    specialty?: CodeableConcept[];
    telecom?: ContactPoint[];
}
export const isOrganizationAffiliation = (resource: unknown): resource is OrganizationAffiliation => {
    return resource !== null && typeof resource === "object" && (resource as {resourceType: string}).resourceType === "OrganizationAffiliation";
}
