// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Extension } from "../hl7-fhir-r4-core/Extension";
import type { ServiceRequest } from "../hl7-fhir-r4-core/ServiceRequest";

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/servicerequest-genetics
export interface ServiceRequest_Genetics {
    __profileUrl: "http://hl7.org/fhir/StructureDefinition/servicerequest-genetics";

    extension?: Extension[];
}

export const attach_ServiceRequest_Genetics_to_ServiceRequest = (resource: ServiceRequest, profile: ServiceRequest_Genetics): ServiceRequest => {
    return {
        ...resource,
        meta: {
            profile: ['http://hl7.org/fhir/StructureDefinition/servicerequest-genetics']
        },
        extension: profile.extension,
    }
}

export const extract_ServiceRequest_Genetics_from_ServiceRequest = (resource: ServiceRequest): ServiceRequest_Genetics => {
    return {
        __profileUrl: 'http://hl7.org/fhir/StructureDefinition/servicerequest-genetics',
        extension: resource.extension,
    }
}
