// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Attachment } from "../hl7-fhir-r4-core/Attachment";
import type { BackboneElement } from "../hl7-fhir-r4-core/BackboneElement";
import type { CodeableConcept } from "../hl7-fhir-r4-core/CodeableConcept";
import type { DomainResource } from "../hl7-fhir-r4-core/DomainResource";
import type { Identifier } from "../hl7-fhir-r4-core/Identifier";

export type { Attachment } from "../hl7-fhir-r4-core/Attachment";
export type { BackboneElement } from "../hl7-fhir-r4-core/BackboneElement";
export type { CodeableConcept } from "../hl7-fhir-r4-core/CodeableConcept";
export type { Identifier } from "../hl7-fhir-r4-core/Identifier";

export interface SubstanceNucleicAcidSubunit extends BackboneElement {
    fivePrime?: CodeableConcept;
    length?: number;
    linkage?: SubstanceNucleicAcidSubunitLinkage[];
    sequence?: string;
    sequenceAttachment?: Attachment;
    subunit?: number;
    sugar?: SubstanceNucleicAcidSubunitSugar[];
    threePrime?: CodeableConcept;
}

export interface SubstanceNucleicAcidSubunitLinkage extends BackboneElement {
    connectivity?: string;
    identifier?: Identifier;
    name?: string;
    residueSite?: string;
}

export interface SubstanceNucleicAcidSubunitSugar extends BackboneElement {
    identifier?: Identifier;
    name?: string;
    residueSite?: string;
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/SubstanceNucleicAcid
export interface SubstanceNucleicAcid extends DomainResource {
    resourceType: "SubstanceNucleicAcid";

    areaOfHybridisation?: string;
    _areaOfHybridisation?: Element;
    numberOfSubunits?: number;
    _numberOfSubunits?: Element;
    oligoNucleotideType?: CodeableConcept;
    sequenceType?: CodeableConcept;
    subunit?: SubstanceNucleicAcidSubunit[];
}
export const isSubstanceNucleicAcid = (resource: unknown): resource is SubstanceNucleicAcid => {
    return resource !== null && typeof resource === "object" && (resource as {resourceType: string}).resourceType === "SubstanceNucleicAcid";
}
