// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { BackboneElement } from "../hl7-fhir-r4-core/BackboneElement";
import type { CodeableConcept } from "../hl7-fhir-r4-core/CodeableConcept";
import type { DomainResource } from "../hl7-fhir-r4-core/DomainResource";
import type { Identifier } from "../hl7-fhir-r4-core/Identifier";

export type { BackboneElement } from "../hl7-fhir-r4-core/BackboneElement";
export type { CodeableConcept } from "../hl7-fhir-r4-core/CodeableConcept";
export type { Identifier } from "../hl7-fhir-r4-core/Identifier";

export interface SubstanceSourceMaterialFractionDescription extends BackboneElement {
    fraction?: string;
    materialType?: CodeableConcept;
}

export interface SubstanceSourceMaterialOrganism extends BackboneElement {
    author?: SubstanceSourceMaterialOrganismAuthor[];
    family?: CodeableConcept;
    genus?: CodeableConcept;
    hybrid?: SubstanceSourceMaterialOrganismHybrid;
    intraspecificDescription?: string;
    intraspecificType?: CodeableConcept;
    organismGeneral?: SubstanceSourceMaterialOrganismOrganismGeneral;
    species?: CodeableConcept;
}

export interface SubstanceSourceMaterialOrganismAuthor extends BackboneElement {
    authorDescription?: string;
    authorType?: CodeableConcept;
}

export interface SubstanceSourceMaterialOrganismHybrid extends BackboneElement {
    hybridType?: CodeableConcept;
    maternalOrganismId?: string;
    maternalOrganismName?: string;
    paternalOrganismId?: string;
    paternalOrganismName?: string;
}

export interface SubstanceSourceMaterialOrganismOrganismGeneral extends BackboneElement {
    "class"?: CodeableConcept;
    kingdom?: CodeableConcept;
    order?: CodeableConcept;
    phylum?: CodeableConcept;
}

export interface SubstanceSourceMaterialPartDescription extends BackboneElement {
    part?: CodeableConcept;
    partLocation?: CodeableConcept;
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/SubstanceSourceMaterial
export interface SubstanceSourceMaterial extends DomainResource {
    resourceType: "SubstanceSourceMaterial";

    countryOfOrigin?: CodeableConcept[];
    developmentStage?: CodeableConcept;
    fractionDescription?: SubstanceSourceMaterialFractionDescription[];
    geographicalLocation?: string[];
    _geographicalLocation?: Element;
    organism?: SubstanceSourceMaterialOrganism;
    organismId?: Identifier;
    organismName?: string;
    _organismName?: Element;
    parentSubstanceId?: Identifier[];
    parentSubstanceName?: string[];
    _parentSubstanceName?: Element;
    partDescription?: SubstanceSourceMaterialPartDescription[];
    sourceMaterialClass?: CodeableConcept;
    sourceMaterialState?: CodeableConcept;
    sourceMaterialType?: CodeableConcept;
}
export const isSubstanceSourceMaterial = (resource: unknown): resource is SubstanceSourceMaterial => {
    return resource !== null && typeof resource === "object" && (resource as {resourceType: string}).resourceType === "SubstanceSourceMaterial";
}
