volumes:
  aidbox_pg_data: {}
services:
  aidbox_db:
    image: healthsamurai/aidboxdb:17
    volumes:
      - aidbox_pg_data:/var/lib/postgresql/data:delegated
    environment:
      POSTGRES_USER: aidbox
      POSTGRES_PORT: "5432"
      POSTGRES_DB: aidbox
      POSTGRES_PASSWORD: M3ya7uZxdJ
  aidbox:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    image: healthsamurai/aidboxone:edge
    pull_policy: never
    depends_on:
      - aidbox_db
    ports:
      - 8888:8888
    environment:
      AIDBOX_TERMINOLOGY_SERVICE_BASE_URL: https://tx.fhir.org/r4
      AIDBOX_FHIR_PACKAGES: hl7.fhir.r4.core#4.0.1
      AIDBOX_FHIR_SCHEMA_VALIDATION: true
      AIDBOX_CREATED_AT_URL: https://aidbox.app/ex/createdAt
      AIDBOX_CLIENT_SECRET: secret
      AIDBOX_CORRECT_AIDBOX_FORMAT: true
      AIDBOX_ADMIN_PASSWORD: cwSgexVsRb
      AIDBOX_COMPLIANCE: enabled
      BOX_SEARCH_FHIR__COMPARISONS: true
      PGHOST: aidbox_db
      BOX_COMPATIBILITY_VALIDATION_JSON__SCHEMA_REGEX: "#{:fhir-datetime}"
      BOX_SEARCH_AUTHORIZE_INLINE_REQUESTS: true
      PGUSER: aidbox
      AIDBOX_PORT: 8888
      PGDATABASE: aidbox
      PGPASSWORD: M3ya7uZxdJ
      PGPORT: "5432"
      BOX_SEARCH_INCLUDE_CONFORMANT: true
