import type { Resources } from "@helsenorge/refero";

export const referoResources: Resources = {
  confirmDeleteButtonText: "Confirm Delete Button Text",
  confirmDeleteCancelButtonText: "Confirm Delete Cancel Button Text",
  confirmDeleteHeading: "Confirm Delete Heading",
  confirmDeleteDescription: "Confirm Delete Description",
  validationNotAllowed: "Validation Not Allowed",
  formCancel: "Form Cancel",
  formSend: "Form Send",
  repeatButtonText: "Repeat Button Text",
  errorAfterMaxDate: "Error After Max Date",
  errorBeforeMinDate: "Error Before Min Date",
  oppgiVerdi: "Oppgi Verdi",
  oppgiGyldigVerdi: "Oppgi Gyldig Verdi",
  deleteButtonText: "Delete Button Text",
  validationSummaryHeader: "Validation Summary Header",
  selectDefaultPlaceholder: "Select Default Placeholder",
  supportedFileFormats: "Supported File Formats",
  ikkeBesvart: "Ikke Besvart",
  formRequiredErrorMessage: "Form Required Error Message",
  deleteAttachmentText: "Delete Attachment Text",
  uploadButtonText: "Upload Button Text",
  autoSuggestLoadError: "Auto Suggest Load Error",
  stringOverMaxLengthError: "String Over Max Length Error",
  chooseFilesText: "Choose Files Text",
  autosuggestNoSuggestions: "Autosuggest No Suggestions",
  skipLinkText: "Skip Link Text",
  formSave: "Form Save",
  openChoiceOption: "Open Choice Option",
  year_field_invalid: "Year field invalid",
  year_field_required: "Year field required",
  year_field_mindate: "Year field mindate",
  year_field_maxdate: "Year field maxdate",
  yearmonth_field_month_placeholder: "Yearmonth field month placeholder",
  yearmonth_field_required: "Yearmonth field required",
  adresseKomponent_header: "Adresse Komponent header",
  adresseKomponent_sublabel: "Adresse Komponent sublabel",
  adresseKomponent_velgHelseregion: "Adresse Komponent velg Helseregion",
  adresseKomponent_velgHelseforetak: "Adresse Komponent velg Helseforetak",
  adresseKomponent_velgSykehus: "Adresse Komponent velg Sykehus",
  adresseKomponent_velgAvdeling: "Adresse Komponent velg Avdeling",
  adresseKomponent_skjemaSendesTil: "Adresse Komponent skjema Sendes Til",
  adresseKomponent_feilmelding: "Adresse Komponent feilmelding",
  adresseKomponent_loadError: "Adresse Komponent load Error",
  adresseKomponent_velgKlinikk: "Adresse Komponent velg Klinikk",
  adresseKomponent_velgSeksjon: "Adresse Komponent velg Seksjon",
  adresseKomponent_velgSengepost: "Adresse Komponent velg Sengepost",
  adresseKomponent_velgPoliklinikk: "Adresse Komponent velg Poliklinikk",
  adresseKomponent_velgTjeneste: "Adresse Komponent velg Tjeneste",
  linkOpensInNewTab: "Link Opens In New Tab",
  nextStep: "Next Step",
  previousStep: "Previous Step",
  maxCharactersText: "Max Characters Text",
  attachmentError_minFiles: "Attachment Error min Files",
  attachmentError_maxFiles: "Attachment Error max Files",
  attachmentError_fileSize: "Attachment Error file Size",
  attachmentError_fileType: "Attachment Error file Type",
  dateError_invalid: "Date Error invalid",
  dateError_time_invalid: "Date Error time invalid",
  dateLabel_january: "Date Label january",
  dateLabel_february: "Date Label february",
  dateLabel_march: "Date Label march",
  dateLabel_april: "Date Label april",
  dateLabel_may: "Date Label may",
  dateLabel_june: "Date Label june",
  dateLabel_july: "Date Label july",
  dateLabel_august: "Date Label august",
  dateLabel_september: "Date Label september",
  dateLabel_october: "Date Label october",
  dateLabel_november: "Date Label november",
  dateLabel_december: "Date Label december",
  dateFormat_ddmmyyyy: "Date Format ddmmyyyy",
  timeError_hours_digits: "Time Error hours digits",
  timeError_minutes_digits: "Time Error minutes digits",
  dateLabel_year: "Date Label year",
  dateLabel_month: "Date Label month",
  attachmentError_minFiles_and_maxFiles: "Attachment Error min Files and max Files",
  quantity_unit_sublabel: "Quantity unit sublabel",
  formOptional: "Form Optional",
  formRequired: "Form Required",
  formAllOptional: "Form All Optional",
  formAllRequired: "Form All Required",
  formRequiredInputs: "Form Required Inputs",
  formRequiredSingleCheckbox: "Form Required Single Checkbox",
  formRequiredMultiCheckbox: "Form Required Multi Checkbox",
  formRequiredRadiobuttonList: "Form Required Radiobutton List",
};
