[build]
format = "esm"
target = "browser"
outdir = "dist"
splitting = true
minify = true
sourcemap = "external"

[build.resolve]
extensions = [".ts", ".tsx", ".js", ".jsx"]

# Bundle React and ReactDOM for standalone usage