// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Extension } from "../../hl7-fhir-r4-core/Extension";
import type { GuidanceResponse } from "../../hl7-fhir-r4-core/GuidanceResponse";
import type { Identifier } from "../../hl7-fhir-r4-core/Identifier";

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/cdshooksguidanceresponse
export interface CDS_Hooks_GuidanceResponse extends GuidanceResponse {
    requestIdentifier: Identifier;
    identifier: Identifier[];
    moduleUri: string;
}

export class CDS_Hooks_GuidanceResponseProfile {
    private resource: GuidanceResponse

    constructor (resource: GuidanceResponse) {
        this.resource = resource
    }

    toResource () : GuidanceResponse {
        return this.resource
    }

    toProfile () : CDS_Hooks_GuidanceResponse {
        return this.resource as CDS_Hooks_GuidanceResponse
    }

    public setCdsHooksEndpoint (value: string): this {
        const list = (this.resource.extension ??= [])
        list.push({ url: "http://hl7.org/fhir/StructureDefinition/cqf-cdsHooksEndpoint", valueUri: value })
        return this
    }

    public getCdsHooksEndpoint (): string | undefined {
        const ext = this.resource.extension?.find(e => e.url === "http://hl7.org/fhir/StructureDefinition/cqf-cdsHooksEndpoint")
        return ext?.valueUri
    }

    public getCdsHooksEndpointExtension (): Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "http://hl7.org/fhir/StructureDefinition/cqf-cdsHooksEndpoint")
        return ext
    }

}

