// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Extension } from "../../hl7-fhir-r4-core/Extension";
import type { Questionnaire } from "../../hl7-fhir-r4-core/Questionnaire";

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/cqf-questionnaire
export class CQF_QuestionnaireProfile {
    private resource: Questionnaire

    constructor (resource: Questionnaire) {
        this.resource = resource
    }

    toResource () : Questionnaire {
        return this.resource
    }

    public setLibrary (value: string): this {
        const list = (this.resource.extension ??= [])
        list.push({ url: "http://hl7.org/fhir/StructureDefinition/cqf-library", valueCanonical: value })
        return this
    }

    public getLibrary (): string | undefined {
        const ext = this.resource.extension?.find(e => e.url === "http://hl7.org/fhir/StructureDefinition/cqf-library")
        return ext?.valueCanonical
    }

    public getLibraryExtension (): Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "http://hl7.org/fhir/StructureDefinition/cqf-library")
        return ext
    }

}

