// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Composition } from "../../hl7-fhir-r4-core/Composition";
import type { CompositionSection } from "../../hl7-fhir-r4-core/Composition";

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/example-section-library
export type DocumentSectionLibrary_Section_ProcedureSliceInput = Omit<CompositionSection, "code"> & Required<Pick<CompositionSection, "title">>;
export type DocumentSectionLibrary_Section_MedicationsSliceInput = Omit<CompositionSection, "code"> & Required<Pick<CompositionSection, "title">>;
export type DocumentSectionLibrary_Section_PlanSliceInput = Omit<CompositionSection, "code"> & Required<Pick<CompositionSection, "title">>;

import { applySliceMatch, matchesSlice, extractSliceSimplified } from "../../profile-helpers";

export class DocumentSectionLibraryProfile {
    private resource: Composition

    constructor (resource: Composition) {
        this.resource = resource
    }

    toResource () : Composition {
        return this.resource
    }

    public setProcedure (input: DocumentSectionLibrary_Section_ProcedureSliceInput): this {
        const match = {"code":{"coding":[{"system":"http://loinc.org","code":"29554-3","display":"Procedure Narrative"}]}} as Record<string, unknown>
        const value = applySliceMatch(input as Record<string, unknown>, match) as unknown as CompositionSection
        const list = (this.resource.section ??= [])
        const index = list.findIndex((item) => matchesSlice(item, match))
        if (index === -1) {
            list.push(value)
        } else {
            list[index] = value
        }
        return this
    }

    public setMedications (input: DocumentSectionLibrary_Section_MedicationsSliceInput): this {
        const match = {"code":{"coding":[{"system":"http://loinc.org","code":"29549-3","display":"Medication administered Narrative"}]}} as Record<string, unknown>
        const value = applySliceMatch(input as Record<string, unknown>, match) as unknown as CompositionSection
        const list = (this.resource.section ??= [])
        const index = list.findIndex((item) => matchesSlice(item, match))
        if (index === -1) {
            list.push(value)
        } else {
            list[index] = value
        }
        return this
    }

    public setPlan (input: DocumentSectionLibrary_Section_PlanSliceInput): this {
        const match = {"code":{"coding":[{"system":"http://loinc.org","code":"18776-5","display":"Plan of treatment (narrative)"}]}} as Record<string, unknown>
        const value = applySliceMatch(input as Record<string, unknown>, match) as unknown as CompositionSection
        const list = (this.resource.section ??= [])
        const index = list.findIndex((item) => matchesSlice(item, match))
        if (index === -1) {
            list.push(value)
        } else {
            list[index] = value
        }
        return this
    }

    public getProcedure (): DocumentSectionLibrary_Section_ProcedureSliceInput | undefined {
        const match = {"code":{"coding":[{"system":"http://loinc.org","code":"29554-3","display":"Procedure Narrative"}]}} as Record<string, unknown>
        const list = this.resource.section
        if (!list) return undefined
        const item = list.find((item) => matchesSlice(item, match))
        if (!item) return undefined
        return extractSliceSimplified(item as unknown as Record<string, unknown>, ["code"]) as DocumentSectionLibrary_Section_ProcedureSliceInput
    }

    public getProcedureRaw (): CompositionSection | undefined {
        const match = {"code":{"coding":[{"system":"http://loinc.org","code":"29554-3","display":"Procedure Narrative"}]}} as Record<string, unknown>
        const list = this.resource.section
        if (!list) return undefined
        const item = list.find((item) => matchesSlice(item, match))
        return item
    }

    public getMedications (): DocumentSectionLibrary_Section_MedicationsSliceInput | undefined {
        const match = {"code":{"coding":[{"system":"http://loinc.org","code":"29549-3","display":"Medication administered Narrative"}]}} as Record<string, unknown>
        const list = this.resource.section
        if (!list) return undefined
        const item = list.find((item) => matchesSlice(item, match))
        if (!item) return undefined
        return extractSliceSimplified(item as unknown as Record<string, unknown>, ["code"]) as DocumentSectionLibrary_Section_MedicationsSliceInput
    }

    public getMedicationsRaw (): CompositionSection | undefined {
        const match = {"code":{"coding":[{"system":"http://loinc.org","code":"29549-3","display":"Medication administered Narrative"}]}} as Record<string, unknown>
        const list = this.resource.section
        if (!list) return undefined
        const item = list.find((item) => matchesSlice(item, match))
        return item
    }

    public getPlan (): DocumentSectionLibrary_Section_PlanSliceInput | undefined {
        const match = {"code":{"coding":[{"system":"http://loinc.org","code":"18776-5","display":"Plan of treatment (narrative)"}]}} as Record<string, unknown>
        const list = this.resource.section
        if (!list) return undefined
        const item = list.find((item) => matchesSlice(item, match))
        if (!item) return undefined
        return extractSliceSimplified(item as unknown as Record<string, unknown>, ["code"]) as DocumentSectionLibrary_Section_PlanSliceInput
    }

    public getPlanRaw (): CompositionSection | undefined {
        const match = {"code":{"coding":[{"system":"http://loinc.org","code":"18776-5","display":"Plan of treatment (narrative)"}]}} as Record<string, unknown>
        const list = this.resource.section
        if (!list) return undefined
        const item = list.find((item) => matchesSlice(item, match))
        return item
    }

}

