// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { CodeableConcept } from "../../hl7-fhir-r4-core/CodeableConcept";
import type { Extension } from "../../hl7-fhir-r4-core/Extension";
import type { Observation } from "../../hl7-fhir-r4-core/Observation";
import type { Reference } from "../../hl7-fhir-r4-core/Reference";

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/observation-genetics
export type Observation_genetics_VariantInput = {
    Name?: CodeableConcept;
    Id?: CodeableConcept;
    Type?: CodeableConcept;
}

export type Observation_genetics_AminoAcidChangeInput = {
    Name?: CodeableConcept;
    Type?: CodeableConcept;
}

export type Observation_genetics_AlleleInput = {
    Name?: CodeableConcept;
    State?: CodeableConcept;
    Frequency?: number;
}

export type Observation_genetics_AncestryInput = {
    Name: CodeableConcept;
    Percentage?: number;
    Source?: CodeableConcept;
}

export type Observation_genetics_PhaseSetInput = {
    Id?: string;
    MolecularSequence: Reference[];
}

import { extractComplexExtension } from "../../profile-helpers";

export class Observation_geneticsProfile {
    private resource: Observation

    constructor (resource: Observation) {
        this.resource = resource
    }

    toResource () : Observation {
        return this.resource
    }

    public setGene (value: CodeableConcept): this {
        const list = (this.resource.extension ??= [])
        list.push({ url: "http://hl7.org/fhir/StructureDefinition/observation-geneticsGene", valueCodeableConcept: value })
        return this
    }

    public setDnaregionName (value: string): this {
        const list = (this.resource.extension ??= [])
        list.push({ url: "http://hl7.org/fhir/StructureDefinition/observation-geneticsDNARegionName", valueString: value })
        return this
    }

    public setCopyNumberEvent (value: CodeableConcept): this {
        const list = (this.resource.extension ??= [])
        list.push({ url: "http://hl7.org/fhir/StructureDefinition/observation-geneticsCopyNumberEvent", valueCodeableConcept: value })
        return this
    }

    public setGenomicSourceClass (value: CodeableConcept): this {
        const list = (this.resource.extension ??= [])
        list.push({ url: "http://hl7.org/fhir/StructureDefinition/observation-geneticsGenomicSourceClass", valueCodeableConcept: value })
        return this
    }

    public setInterpretation (value: Reference): this {
        const list = (this.resource.extension ??= [])
        list.push({ url: "http://hl7.org/fhir/StructureDefinition/observation-geneticsInterpretation", valueReference: value })
        return this
    }

    public setVariant (input: Observation_genetics_VariantInput): this {
        const subExtensions: Extension[] = []
        if (input.Name !== undefined) {
            subExtensions.push({ url: "Name", valueCodeableConcept: input.Name })
        }
        if (input.Id !== undefined) {
            subExtensions.push({ url: "Id", valueCodeableConcept: input.Id })
        }
        if (input.Type !== undefined) {
            subExtensions.push({ url: "Type", valueCodeableConcept: input.Type })
        }
        const list = (this.resource.extension ??= [])
        list.push({ url: "http://hl7.org/fhir/StructureDefinition/observation-geneticsVariant", extension: subExtensions })
        return this
    }

    public setAminoAcidChange (input: Observation_genetics_AminoAcidChangeInput): this {
        const subExtensions: Extension[] = []
        if (input.Name !== undefined) {
            subExtensions.push({ url: "Name", valueCodeableConcept: input.Name })
        }
        if (input.Type !== undefined) {
            subExtensions.push({ url: "Type", valueCodeableConcept: input.Type })
        }
        const list = (this.resource.extension ??= [])
        list.push({ url: "http://hl7.org/fhir/StructureDefinition/observation-geneticsAminoAcidChange", extension: subExtensions })
        return this
    }

    public setAllele (input: Observation_genetics_AlleleInput): this {
        const subExtensions: Extension[] = []
        if (input.Name !== undefined) {
            subExtensions.push({ url: "Name", valueCodeableConcept: input.Name })
        }
        if (input.State !== undefined) {
            subExtensions.push({ url: "State", valueCodeableConcept: input.State })
        }
        if (input.Frequency !== undefined) {
            subExtensions.push({ url: "Frequency", valueDecimal: input.Frequency })
        }
        const list = (this.resource.extension ??= [])
        list.push({ url: "http://hl7.org/fhir/StructureDefinition/observation-geneticsAllele", extension: subExtensions })
        return this
    }

    public setAncestry (input: Observation_genetics_AncestryInput): this {
        const subExtensions: Extension[] = []
        if (input.Name !== undefined) {
            subExtensions.push({ url: "Name", valueCodeableConcept: input.Name })
        }
        if (input.Percentage !== undefined) {
            subExtensions.push({ url: "Percentage", valueDecimal: input.Percentage })
        }
        if (input.Source !== undefined) {
            subExtensions.push({ url: "Source", valueCodeableConcept: input.Source })
        }
        const list = (this.resource.extension ??= [])
        list.push({ url: "http://hl7.org/fhir/StructureDefinition/observation-geneticsAncestry", extension: subExtensions })
        return this
    }

    public setPhaseSet (input: Observation_genetics_PhaseSetInput): this {
        const subExtensions: Extension[] = []
        if (input.Id !== undefined) {
            subExtensions.push({ url: "Id", valueUri: input.Id })
        }
        if (input.MolecularSequence) {
            for (const item of input.MolecularSequence) {
                subExtensions.push({ url: "MolecularSequence", valueReference: item })
            }
        }
        const list = (this.resource.extension ??= [])
        list.push({ url: "http://hl7.org/fhir/StructureDefinition/observation-geneticsPhaseSet", extension: subExtensions })
        return this
    }

    public getGene (): CodeableConcept | undefined {
        const ext = this.resource.extension?.find(e => e.url === "http://hl7.org/fhir/StructureDefinition/observation-geneticsGene")
        return ext?.valueCodeableConcept
    }

    public getGeneExtension (): Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "http://hl7.org/fhir/StructureDefinition/observation-geneticsGene")
        return ext
    }

    public getDnaregionName (): string | undefined {
        const ext = this.resource.extension?.find(e => e.url === "http://hl7.org/fhir/StructureDefinition/observation-geneticsDNARegionName")
        return ext?.valueString
    }

    public getDnaregionNameExtension (): Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "http://hl7.org/fhir/StructureDefinition/observation-geneticsDNARegionName")
        return ext
    }

    public getCopyNumberEvent (): CodeableConcept | undefined {
        const ext = this.resource.extension?.find(e => e.url === "http://hl7.org/fhir/StructureDefinition/observation-geneticsCopyNumberEvent")
        return ext?.valueCodeableConcept
    }

    public getCopyNumberEventExtension (): Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "http://hl7.org/fhir/StructureDefinition/observation-geneticsCopyNumberEvent")
        return ext
    }

    public getGenomicSourceClass (): CodeableConcept | undefined {
        const ext = this.resource.extension?.find(e => e.url === "http://hl7.org/fhir/StructureDefinition/observation-geneticsGenomicSourceClass")
        return ext?.valueCodeableConcept
    }

    public getGenomicSourceClassExtension (): Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "http://hl7.org/fhir/StructureDefinition/observation-geneticsGenomicSourceClass")
        return ext
    }

    public getInterpretation (): Reference | undefined {
        const ext = this.resource.extension?.find(e => e.url === "http://hl7.org/fhir/StructureDefinition/observation-geneticsInterpretation")
        return ext?.valueReference
    }

    public getInterpretationExtension (): Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "http://hl7.org/fhir/StructureDefinition/observation-geneticsInterpretation")
        return ext
    }

    public getVariant (): Observation_genetics_VariantInput | undefined {
        const ext = this.resource.extension?.find(e => e.url === "http://hl7.org/fhir/StructureDefinition/observation-geneticsVariant")
        if (!ext) return undefined
        const config = [{ name: "Name", valueField: "valueCodeableConcept", isArray: false }, { name: "Id", valueField: "valueCodeableConcept", isArray: false }, { name: "Type", valueField: "valueCodeableConcept", isArray: false }]
        return extractComplexExtension(ext as unknown as { extension?: Array<{ url?: string; [key: string]: unknown }> }, config) as Observation_genetics_VariantInput
    }

    public getVariantExtension (): Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "http://hl7.org/fhir/StructureDefinition/observation-geneticsVariant")
        return ext
    }

    public getAminoAcidChange (): Observation_genetics_AminoAcidChangeInput | undefined {
        const ext = this.resource.extension?.find(e => e.url === "http://hl7.org/fhir/StructureDefinition/observation-geneticsAminoAcidChange")
        if (!ext) return undefined
        const config = [{ name: "Name", valueField: "valueCodeableConcept", isArray: false }, { name: "Type", valueField: "valueCodeableConcept", isArray: false }]
        return extractComplexExtension(ext as unknown as { extension?: Array<{ url?: string; [key: string]: unknown }> }, config) as Observation_genetics_AminoAcidChangeInput
    }

    public getAminoAcidChangeExtension (): Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "http://hl7.org/fhir/StructureDefinition/observation-geneticsAminoAcidChange")
        return ext
    }

    public getAllele (): Observation_genetics_AlleleInput | undefined {
        const ext = this.resource.extension?.find(e => e.url === "http://hl7.org/fhir/StructureDefinition/observation-geneticsAllele")
        if (!ext) return undefined
        const config = [{ name: "Name", valueField: "valueCodeableConcept", isArray: false }, { name: "State", valueField: "valueCodeableConcept", isArray: false }, { name: "Frequency", valueField: "valueDecimal", isArray: false }]
        return extractComplexExtension(ext as unknown as { extension?: Array<{ url?: string; [key: string]: unknown }> }, config) as Observation_genetics_AlleleInput
    }

    public getAlleleExtension (): Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "http://hl7.org/fhir/StructureDefinition/observation-geneticsAllele")
        return ext
    }

    public getAncestry (): Observation_genetics_AncestryInput | undefined {
        const ext = this.resource.extension?.find(e => e.url === "http://hl7.org/fhir/StructureDefinition/observation-geneticsAncestry")
        if (!ext) return undefined
        const config = [{ name: "Name", valueField: "valueCodeableConcept", isArray: false }, { name: "Percentage", valueField: "valueDecimal", isArray: false }, { name: "Source", valueField: "valueCodeableConcept", isArray: false }]
        return extractComplexExtension(ext as unknown as { extension?: Array<{ url?: string; [key: string]: unknown }> }, config) as Observation_genetics_AncestryInput
    }

    public getAncestryExtension (): Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "http://hl7.org/fhir/StructureDefinition/observation-geneticsAncestry")
        return ext
    }

    public getPhaseSet (): Observation_genetics_PhaseSetInput | undefined {
        const ext = this.resource.extension?.find(e => e.url === "http://hl7.org/fhir/StructureDefinition/observation-geneticsPhaseSet")
        if (!ext) return undefined
        const config = [{ name: "Id", valueField: "valueUri", isArray: false }, { name: "MolecularSequence", valueField: "valueReference", isArray: true }]
        return extractComplexExtension(ext as unknown as { extension?: Array<{ url?: string; [key: string]: unknown }> }, config) as Observation_genetics_PhaseSetInput
    }

    public getPhaseSetExtension (): Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "http://hl7.org/fhir/StructureDefinition/observation-geneticsPhaseSet")
        return ext
    }

}

