// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { CodeableConcept } from "../../hl7-fhir-r4-core/CodeableConcept";
import type { Observation } from "../../hl7-fhir-r4-core/Observation";
import type { Reference } from "../../hl7-fhir-r4-core/Reference";

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/bodytemp
export interface observation_bodytemp extends Observation {
    category: CodeableConcept[];
    subject: Reference<"Patient">;
}

export type Observation_bodytemp_Category_VSCatSliceInput = Omit<CodeableConcept, "coding">;

import { applySliceMatch, matchesSlice, extractSliceSimplified } from "../../profile-helpers";

export class Observation_bodytempProfile {
    private resource: Observation

    constructor (resource: Observation) {
        this.resource = resource
    }

    toResource () : Observation {
        return this.resource
    }

    toProfile () : observation_bodytemp {
        return this.resource as observation_bodytemp
    }

    public setVscat (input?: Observation_bodytemp_Category_VSCatSliceInput): this {
        const match = {"coding":{"code":"vital-signs","system":"http://terminology.hl7.org/CodeSystem/observation-category"}} as Record<string, unknown>
        const value = applySliceMatch((input ?? {}) as Record<string, unknown>, match) as unknown as CodeableConcept
        const list = (this.resource.category ??= [])
        const index = list.findIndex((item) => matchesSlice(item, match))
        if (index === -1) {
            list.push(value)
        } else {
            list[index] = value
        }
        return this
    }

    public getVscat (): Observation_bodytemp_Category_VSCatSliceInput | undefined {
        const match = {"coding":{"code":"vital-signs","system":"http://terminology.hl7.org/CodeSystem/observation-category"}} as Record<string, unknown>
        const list = this.resource.category
        if (!list) return undefined
        const item = list.find((item) => matchesSlice(item, match))
        if (!item) return undefined
        return extractSliceSimplified(item as unknown as Record<string, unknown>, ["coding"]) as Observation_bodytemp_Category_VSCatSliceInput
    }

    public getVscatRaw (): CodeableConcept | undefined {
        const match = {"coding":{"code":"vital-signs","system":"http://terminology.hl7.org/CodeSystem/observation-category"}} as Record<string, unknown>
        const list = this.resource.category
        if (!list) return undefined
        const item = list.find((item) => matchesSlice(item, match))
        return item
    }

}

