version: '3.7'
volumes:
  aidbox_pg_data: {}

services:

  growth_chart:
    build: 
      context: .
      dockerfile: ./Dockerfile.growthchart
    ports:
    - 9000:9000

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.6
    volumes:
    - ./keycloak.json:/opt/keycloak/data/import/keycloak.json
    ports:
      - 8888:8888
    environment:
      KC_HTTP_PORT: 8888
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    command: start-dev --import-realm
  
  launcher:
    image: nginx:alpine
    ports:
      - "7070:80"
    volumes:
      - ./launcher.html:/usr/share/nginx/html/launcher.html:r

  aidbox_db:
    image: healthsamurai/aidboxdb:17
    pull_policy: always
    volumes:
    - aidbox_pg_data:/data:delegated
    environment:
      PGDATA: /data
      POSTGRES_USER: aidbox
      POSTGRES_PORT: '5432'
      POSTGRES_DB: aidbox
      POSTGRES_PASSWORD: nP0s8ALcTk

  aidbox:
    image: healthsamurai/aidboxone:edge
    pull_policy: always
    depends_on:
    - aidbox_db
    ports:
    - 8080:8080
    volumes:
    - ./aidbox.json:/tmp/aidbox.json
    environment:
      BOX_INIT_BUNDLE: file:///tmp/aidbox.json
      BOX_SETTINGS_MODE: "read-write"
      AIDBOX_FHIR_PACKAGES: hl7.fhir.r4.core#4.0.1
      AIDBOX_FHIR_SCHEMA_VALIDATION: true
      AIDBOX_CREATED_AT_URL: https://aidbox.app/ex/createdAt
      AIDBOX_CLIENT_SECRET: vbDPgXnz0H
      AIDBOX_ADMIN_PASSWORD: password
      AIDBOX_COMPLIANCE: enabled
      AIDBOX_LICENSE: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJvZmZsaW5lIjpmYWxzZSwiY3JlYXRvciI6eyJpZCI6IjJkNTU0YWVkLWIxNmUtNDA2Ny05M2I2LWFlOGE5NmU2YjA1YyIsInJlc291cmNlVHlwZSI6IlVzZXIifSwia2V5Ijoib25saW5lLTIwMjIwNTI0LTE0MzY0NyIsIm5hbWUiOiJTTUFSVCBMYXVuY2ggRGVtbyIsImV4cGlyYXRpb24iOiIyMTI0LTA1LTAzVDEzOjA0OjU2LjcyN1oiLCJ0eXBlIjoiZGV2ZWxvcG1lbnQiLCJjcmVhdGVkIjoiMjAyNS0wNS0yN1QxMzowNDo1Ni43MjdaIiwibWF4LWluc3RhbmNlcyI6MiwibWF4LWRiLXNpemUiOjUzNjg3MDkxMjAsInByb2R1Y3QiOiJhaWRib3giLCJwcm9qZWN0Ijp7ImlkIjoiNzA5NzIxNmMtNTRmOC00MjU3LWFjMGItMjhmYjA0ZGI0NjRkIiwicmVzb3VyY2VUeXBlIjoiUHJvamVjdCJ9LCJzdGF0dXMiOiJhY3RpdmUiLCJpZCI6IjE1NmEyMzU5LTY3OWMtNDM2ZS1iNDMzLWUwZDI1NTY3OTY5NSIsImluZm8iOnsiaG9zdGluZyI6InNlbGYtaG9zdGVkIn0sImlzc3VlciI6Imh0dHBzOi8vYWlkYm94LmFwcCJ9.EqIpuAMSpt3WQ7nUves9dwvVR-cdmYehqmcNmdCQTbs4riB6cVHfDwPx4G8XRZeBoJhm_ajS7BZlELqXSuc483MycXpqqsbCsUVO_wlGhyqVEX7N03yyVW2OmT4vilfZBPssVyxuOCoJlKRg2xQ9mz0ylIk1K5PFWHaa1cjsBYo 
      BOX_SEARCH_FHIR__COMPARISONS: true
      PGHOST: aidbox_db
      PGUSER: aidbox
      AIDBOX_PORT: 8080
      PGDATABASE: aidbox
      PGPASSWORD: nP0s8ALcTk
      PGPORT: '5432'
      BOX_SEARCH_INCLUDE_CONFORMANT: true
