// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Element } from "../hl7-fhir-r4-core/Element";
import type { Period } from "../hl7-fhir-r4-core/Period";

export type { Element } from "../hl7-fhir-r4-core/Element";
export type { Period } from "../hl7-fhir-r4-core/Period";

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/ContactPoint
export interface ContactPoint extends Element {
    period?: Period;
    rank?: number;
    _rank?: Element;
    system?: ("phone" | "fax" | "email" | "pager" | "url" | "sms" | "other");
    _system?: Element;
    use?: ("home" | "work" | "temp" | "old" | "mobile");
    _use?: Element;
    value?: string;
    _value?: Element;
}
