// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Address } from "../hl7-fhir-r4-core/Address";
import type { Age } from "../hl7-fhir-r4-core/Age";
import type { Annotation } from "../hl7-fhir-r4-core/Annotation";
import type { Attachment } from "../hl7-fhir-r4-core/Attachment";
import type { BackboneElement } from "../hl7-fhir-r4-core/BackboneElement";
import type { CodeableConcept } from "../hl7-fhir-r4-core/CodeableConcept";
import type { Coding } from "../hl7-fhir-r4-core/Coding";
import type { ContactDetail } from "../hl7-fhir-r4-core/ContactDetail";
import type { ContactPoint } from "../hl7-fhir-r4-core/ContactPoint";
import type { Contributor } from "../hl7-fhir-r4-core/Contributor";
import type { Count } from "../hl7-fhir-r4-core/Count";
import type { DataRequirement } from "../hl7-fhir-r4-core/DataRequirement";
import type { Distance } from "../hl7-fhir-r4-core/Distance";
import type { Dosage } from "../hl7-fhir-r4-core/Dosage";
import type { Duration } from "../hl7-fhir-r4-core/Duration";
import type { Expression } from "../hl7-fhir-r4-core/Expression";
import type { HumanName } from "../hl7-fhir-r4-core/HumanName";
import type { Identifier } from "../hl7-fhir-r4-core/Identifier";
import type { Meta } from "../hl7-fhir-r4-core/Meta";
import type { Money } from "../hl7-fhir-r4-core/Money";
import type { ParameterDefinition } from "../hl7-fhir-r4-core/ParameterDefinition";
import type { Period } from "../hl7-fhir-r4-core/Period";
import type { Quantity } from "../hl7-fhir-r4-core/Quantity";
import type { Range } from "../hl7-fhir-r4-core/Range";
import type { Ratio } from "../hl7-fhir-r4-core/Ratio";
import type { Reference } from "../hl7-fhir-r4-core/Reference";
import type { RelatedArtifact } from "../hl7-fhir-r4-core/RelatedArtifact";
import type { Resource } from "../hl7-fhir-r4-core/Resource";
import type { SampledData } from "../hl7-fhir-r4-core/SampledData";
import type { Signature } from "../hl7-fhir-r4-core/Signature";
import type { Timing } from "../hl7-fhir-r4-core/Timing";
import type { TriggerDefinition } from "../hl7-fhir-r4-core/TriggerDefinition";
import type { UsageContext } from "../hl7-fhir-r4-core/UsageContext";

export type { Address } from "../hl7-fhir-r4-core/Address";
export type { Age } from "../hl7-fhir-r4-core/Age";
export type { Annotation } from "../hl7-fhir-r4-core/Annotation";
export type { Attachment } from "../hl7-fhir-r4-core/Attachment";
export type { BackboneElement } from "../hl7-fhir-r4-core/BackboneElement";
export type { CodeableConcept } from "../hl7-fhir-r4-core/CodeableConcept";
export type { Coding } from "../hl7-fhir-r4-core/Coding";
export type { ContactDetail } from "../hl7-fhir-r4-core/ContactDetail";
export type { ContactPoint } from "../hl7-fhir-r4-core/ContactPoint";
export type { Contributor } from "../hl7-fhir-r4-core/Contributor";
export type { Count } from "../hl7-fhir-r4-core/Count";
export type { DataRequirement } from "../hl7-fhir-r4-core/DataRequirement";
export type { Distance } from "../hl7-fhir-r4-core/Distance";
export type { Dosage } from "../hl7-fhir-r4-core/Dosage";
export type { Duration } from "../hl7-fhir-r4-core/Duration";
export type { Expression } from "../hl7-fhir-r4-core/Expression";
export type { HumanName } from "../hl7-fhir-r4-core/HumanName";
export type { Identifier } from "../hl7-fhir-r4-core/Identifier";
export type { Meta } from "../hl7-fhir-r4-core/Meta";
export type { Money } from "../hl7-fhir-r4-core/Money";
export type { ParameterDefinition } from "../hl7-fhir-r4-core/ParameterDefinition";
export type { Period } from "../hl7-fhir-r4-core/Period";
export type { Quantity } from "../hl7-fhir-r4-core/Quantity";
export type { Range } from "../hl7-fhir-r4-core/Range";
export type { Ratio } from "../hl7-fhir-r4-core/Ratio";
export type { Reference } from "../hl7-fhir-r4-core/Reference";
export type { RelatedArtifact } from "../hl7-fhir-r4-core/RelatedArtifact";
export type { SampledData } from "../hl7-fhir-r4-core/SampledData";
export type { Signature } from "../hl7-fhir-r4-core/Signature";
export type { Timing } from "../hl7-fhir-r4-core/Timing";
export type { TriggerDefinition } from "../hl7-fhir-r4-core/TriggerDefinition";
export type { UsageContext } from "../hl7-fhir-r4-core/UsageContext";

export interface ParametersParameter extends BackboneElement {
    name: string;
    part?: ParametersParameter[];
    resource?: Resource;
    valueAddress?: Address;
    valueAge?: Age;
    valueAnnotation?: Annotation;
    valueAttachment?: Attachment;
    valueBase64Binary?: string;
    valueBoolean?: boolean;
    valueCanonical?: string;
    valueCode?: string;
    valueCodeableConcept?: CodeableConcept;
    valueCoding?: Coding;
    valueContactDetail?: ContactDetail;
    valueContactPoint?: ContactPoint;
    valueContributor?: Contributor;
    valueCount?: Count;
    valueDataRequirement?: DataRequirement;
    valueDate?: string;
    valueDateTime?: string;
    valueDecimal?: number;
    valueDistance?: Distance;
    valueDosage?: Dosage;
    valueDuration?: Duration;
    valueExpression?: Expression;
    valueHumanName?: HumanName;
    valueId?: string;
    valueIdentifier?: Identifier;
    valueInstant?: string;
    valueInteger?: number;
    valueMarkdown?: string;
    valueMeta?: Meta;
    valueMoney?: Money;
    valueOid?: string;
    valueParameterDefinition?: ParameterDefinition;
    valuePeriod?: Period;
    valuePositiveInt?: number;
    valueQuantity?: Quantity;
    valueRange?: Range;
    valueRatio?: Ratio;
    valueReference?: Reference;
    valueRelatedArtifact?: RelatedArtifact;
    valueSampledData?: SampledData;
    valueSignature?: Signature;
    valueString?: string;
    valueTime?: string;
    valueTiming?: Timing;
    valueTriggerDefinition?: TriggerDefinition;
    valueUnsignedInt?: number;
    valueUri?: string;
    valueUrl?: string;
    valueUsageContext?: UsageContext;
    valueUuid?: string;
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/Parameters
export interface Parameters extends Resource {
    resourceType: "Parameters";

    parameter?: ParametersParameter[];
}
export const isParameters = (resource: unknown): resource is Parameters => {
    return resource !== null && typeof resource === "object" && (resource as {resourceType: string}).resourceType === "Parameters";
}
