# WARNING: This file is autogenerated by @atomic-ehr/codegen.
# GitHub: https://github.com/atomic-ehr/codegen
# Any manual changes made to this file may be overwritten.

from __future__ import annotations

from typing import cast

from fhir_types.hl7_fhir_r4_core.base import Extension
from fhir_types.hl7_fhir_r4_core.base import Coding
from fhir_types.profile_helpers import (
    build_resource, validate_choice_required, validate_fixed_value, validate_required
)


class UscoreIndividualSexExtension:
    """USCDI includes a data element for Sex, intended to support the exchange of a recorded sex value. This extension aligns with the USCDI definition of Sex: "Documentation of a specific instance of sex." It enables systems to share the sex value as it was documented in a particular context.  Systems choosing to record sources of information should use the [Provenance resource](element-level-provenance.html).

    CanonicalURL: http://hl7.org/fhir/us/core/StructureDefinition/us-core-individual-sex
    """

    canonical_url: str = "http://hl7.org/fhir/us/core/StructureDefinition/us-core-individual-sex"

    def __init__(self, resource: Extension) -> None:
        self._resource = resource

    @classmethod
    def from_resource(cls, resource: Extension) -> "UscoreIndividualSexExtension":
        profile = cls(resource)
        result = profile.validate()
        if result["errors"]:
            raise ValueError("; ".join(result["errors"]))
        return profile

    @classmethod
    def apply(cls, resource: Extension) -> "UscoreIndividualSexExtension":
        return cls(resource)

    @classmethod
    def create_resource(cls, *, valueCoding: Coding) -> Extension:
        return build_resource(Extension, url="http://hl7.org/fhir/us/core/StructureDefinition/us-core-individual-sex", valueCoding=valueCoding)

    @classmethod
    def create(cls, *, valueCoding: Coding) -> "UscoreIndividualSexExtension":
        return cls.apply(cls.create_resource(valueCoding=valueCoding))

    def to_resource(self) -> Extension:
        return self._resource

    def get_value_coding(self) -> Coding | None:
        return cast('Coding | None', getattr(self._resource, "valueCoding", None))

    def set_value_coding(self, value: Coding) -> "UscoreIndividualSexExtension":
        setattr(self._resource, "valueCoding", value)
        return self

    def get_url(self) -> str | None:
        return cast('str | None', getattr(self._resource, "url", None))

    def set_url(self, value: str) -> "UscoreIndividualSexExtension":
        setattr(self._resource, "url", value)
        return self

    def validate(self) -> dict[str, list[str]]:
        profile_name = "UscoreIndividualSexExtension"
        errors: list[str] = []
        warnings: list[str] = []
        errors.extend(validate_required(self._resource, profile_name, "url"))
        errors.extend(validate_fixed_value(self._resource, profile_name, "url", "http://hl7.org/fhir/us/core/StructureDefinition/us-core-individual-sex"))
        errors.extend(validate_choice_required(self._resource, profile_name, ["valueCoding"]))
        return {"errors": errors, "warnings": warnings}

