# WARNING: This file is autogenerated by @atomic-ehr/codegen.
# GitHub: https://github.com/atomic-ehr/codegen
# Any manual changes made to this file may be overwritten.

from __future__ import annotations

from typing import Any, Literal, cast, overload

from fhir_types.hl7_fhir_r4_core.observation import Observation
from fhir_types.hl7_fhir_r4_core.base import (
    CodeableConcept, Period, Quantity, Range, Ratio, Reference, SampledData
)
from fhir_types.profile_helpers import (
    apply_slice_match, build_resource, ensure_profile, ensure_slice_defaults, get_array_slice, matches_value, \
    set_array_slice, strip_match_keys, validate_choice_required, validate_enum, validate_excluded, validate_fixed_value, \
    validate_must_support, validate_reference, validate_required, validate_slice_cardinality
)


class UscoreBodyWeightProfile:
    """The US Core Body Weight Profile inherits from the US Core Vital Signs Profile. This profile sets minimum expectations for the Observation resource to record, search,  and fetch body weight observations with a standard LOINC code and UCUM units of measure. It specifies which *additional*  core elements, extensions,  vocabularies, and value sets **SHALL** be present in the resource and constrains how the elements are used. Providing the floor for standards development for specific use cases promotes interoperability and adoption.

    CanonicalURL: http://hl7.org/fhir/us/core/StructureDefinition/us-core-body-weight
    """

    canonical_url: str = "http://hl7.org/fhir/us/core/StructureDefinition/us-core-body-weight"

    _vscat_slice_match: dict[str, Any] = {"coding":[{"code":"vital-signs","system":"http://terminology.hl7.org/CodeSystem/observation-category"}]}

    def __init__(self, resource: Observation) -> None:
        self._resource = resource

    @classmethod
    def from_resource(cls, resource: Observation) -> "UscoreBodyWeightProfile":
        meta = getattr(resource, "meta", None)
        profiles = getattr(meta, "profile", None) if meta is not None else None
        if profiles is None or cls.canonical_url not in profiles:
            raise ValueError(f"UscoreBodyWeightProfile: meta.profile must include {cls.canonical_url}")
        profile = cls(resource)
        result = profile.validate()
        if result["errors"]:
            raise ValueError("; ".join(result["errors"]))
        return profile

    @classmethod
    def apply(cls, resource: Observation) -> "UscoreBodyWeightProfile":
        ensure_profile(resource, cls.canonical_url)
        return cls(resource)

    @classmethod
    def create_resource(cls, *, category: list[CodeableConcept] | None = None, status: Literal["registered", "preliminary", "final", "amended", "corrected", "cancelled", "entered-in-error", "unknown"], subject: Reference) -> Observation:
        category_with_defaults = ensure_slice_defaults(list(category or []), cls._vscat_slice_match)

        return build_resource(
            Observation,
            resourceType="Observation",
            code={"coding":[{"system":"http://loinc.org","code":"29463-7"}]},
            category=category_with_defaults,
            status=status,
            subject=subject,
            meta={"profile": [cls.canonical_url]},
        )

    @classmethod
    def create(cls, *, category: list[CodeableConcept] | None = None, status: Literal["registered", "preliminary", "final", "amended", "corrected", "cancelled", "entered-in-error", "unknown"], subject: Reference) -> "UscoreBodyWeightProfile":
        return cls.apply(cls.create_resource(category=category, status=status, subject=subject))

    def to_resource(self) -> Observation:
        return self._resource

    def get_status(self) -> Literal["registered", "preliminary", "final", "amended", "corrected", "cancelled", "entered-in-error", "unknown"] | None:
        return cast('Literal["registered", "preliminary", "final", "amended", "corrected", "cancelled", "entered-in-error", "unknown"] | None', getattr(self._resource, "status", None))

    def set_status(self, value: Literal["registered", "preliminary", "final", "amended", "corrected", "cancelled", "entered-in-error", "unknown"]) -> "UscoreBodyWeightProfile":
        setattr(self._resource, "status", value)
        return self

    def get_subject(self) -> Reference | None:
        return cast('Reference | None', getattr(self._resource, "subject", None))

    def set_subject(self, value: Reference) -> "UscoreBodyWeightProfile":
        setattr(self._resource, "subject", value)
        return self

    def get_category(self) -> list[CodeableConcept] | None:
        return cast('list[CodeableConcept] | None', getattr(self._resource, "category", None))

    def set_category(self, value: list[CodeableConcept]) -> "UscoreBodyWeightProfile":
        setattr(self._resource, "category", value)
        return self

    def get_code(self) -> CodeableConcept | None:
        return cast('CodeableConcept | None', getattr(self._resource, "code", None))

    def set_code(self, value: CodeableConcept) -> "UscoreBodyWeightProfile":
        setattr(self._resource, "code", value)
        return self

    def get_effective_date_time(self) -> str | None:
        return cast('str | None', getattr(self._resource, "effectiveDateTime", None))

    def set_effective_date_time(self, value: str) -> "UscoreBodyWeightProfile":
        setattr(self._resource, "effectivePeriod", None)
        setattr(self._resource, "effectiveDateTime", value)
        return self

    def get_effective_period(self) -> Period | None:
        return cast('Period | None', getattr(self._resource, "effectivePeriod", None))

    def set_effective_period(self, value: Period) -> "UscoreBodyWeightProfile":
        setattr(self._resource, "effectiveDateTime", None)
        setattr(self._resource, "effectivePeriod", value)
        return self

    def get_value_quantity(self) -> Quantity | None:
        return cast('Quantity | None', getattr(self._resource, "valueQuantity", None))

    def set_value_quantity(self, value: Quantity) -> "UscoreBodyWeightProfile":
        setattr(self._resource, "valueQuantity", value)
        return self

    def get_value_codeable_concept(self) -> CodeableConcept | None:
        return cast('CodeableConcept | None', getattr(self._resource, "valueCodeableConcept", None))

    def set_value_codeable_concept(self, value: CodeableConcept) -> "UscoreBodyWeightProfile":
        setattr(self._resource, "valueCodeableConcept", value)
        return self

    def get_value_string(self) -> str | None:
        return cast('str | None', getattr(self._resource, "valueString", None))

    def set_value_string(self, value: str) -> "UscoreBodyWeightProfile":
        setattr(self._resource, "valueString", value)
        return self

    def get_value_boolean(self) -> bool | None:
        return cast('bool | None', getattr(self._resource, "valueBoolean", None))

    def set_value_boolean(self, value: bool) -> "UscoreBodyWeightProfile":
        setattr(self._resource, "valueBoolean", value)
        return self

    def get_value_integer(self) -> int | None:
        return cast('int | None', getattr(self._resource, "valueInteger", None))

    def set_value_integer(self, value: int) -> "UscoreBodyWeightProfile":
        setattr(self._resource, "valueInteger", value)
        return self

    def get_value_range(self) -> Range | None:
        return cast('Range | None', getattr(self._resource, "valueRange", None))

    def set_value_range(self, value: Range) -> "UscoreBodyWeightProfile":
        setattr(self._resource, "valueRange", value)
        return self

    def get_value_ratio(self) -> Ratio | None:
        return cast('Ratio | None', getattr(self._resource, "valueRatio", None))

    def set_value_ratio(self, value: Ratio) -> "UscoreBodyWeightProfile":
        setattr(self._resource, "valueRatio", value)
        return self

    def get_value_sampled_data(self) -> SampledData | None:
        return cast('SampledData | None', getattr(self._resource, "valueSampledData", None))

    def set_value_sampled_data(self, value: SampledData) -> "UscoreBodyWeightProfile":
        setattr(self._resource, "valueSampledData", value)
        return self

    def get_value_time(self) -> str | None:
        return cast('str | None', getattr(self._resource, "valueTime", None))

    def set_value_time(self, value: str) -> "UscoreBodyWeightProfile":
        setattr(self._resource, "valueTime", value)
        return self

    def get_value_date_time(self) -> str | None:
        return cast('str | None', getattr(self._resource, "valueDateTime", None))

    def set_value_date_time(self, value: str) -> "UscoreBodyWeightProfile":
        setattr(self._resource, "valueDateTime", value)
        return self

    def get_value_period(self) -> Period | None:
        return cast('Period | None', getattr(self._resource, "valuePeriod", None))

    def set_value_period(self, value: Period) -> "UscoreBodyWeightProfile":
        setattr(self._resource, "valuePeriod", value)
        return self

    @overload
    def get_vscat(self) -> dict[str, Any] | None: ...
    @overload
    def get_vscat(self, mode: Literal["raw"]) -> CodeableConcept | None: ...
    def get_vscat(self, mode: Literal["raw"] | None = None) -> dict[str, Any] | CodeableConcept | None:
        match = self.__class__._vscat_slice_match
        item = get_array_slice(getattr(self._resource, "category", None), match)
        if mode == "raw":
            return cast('CodeableConcept | None', item)
        item_dict = item if isinstance(item, dict) else item.model_dump(by_alias=True, exclude_none=True)
        return strip_match_keys(item_dict, ["coding"])

    def set_vscat(self, value: dict[str, Any] | None = None) -> "UscoreBodyWeightProfile":
        match = self.__class__._vscat_slice_match
        merged = apply_slice_match((value or {}), match)
        merged = CodeableConcept(**merged)
        items = getattr(self._resource, "category", None) or []
        set_array_slice(items, match, merged)
        setattr(self._resource, "category", items)
        return self

    def validate(self) -> dict[str, list[str]]:
        profile_name = "UscoreBodyWeightProfile"
        errors: list[str] = []
        warnings: list[str] = []
        errors.extend(validate_required(self._resource, profile_name, "status"))
        errors.extend(validate_enum(self._resource, profile_name, "status", ["registered","preliminary","final","amended","corrected","cancelled","entered-in-error","unknown"]))
        errors.extend(validate_required(self._resource, profile_name, "category"))
        errors.extend(validate_slice_cardinality(self._resource, profile_name, "category", {"coding":[{"code":"vital-signs","system":"http://terminology.hl7.org/CodeSystem/observation-category"}]}, "VSCat", 1, 1))
        errors.extend(validate_required(self._resource, profile_name, "code"))
        errors.extend(validate_fixed_value(self._resource, profile_name, "code", {"coding":[{"system":"http://loinc.org","code":"29463-7"}]}))
        errors.extend(validate_required(self._resource, profile_name, "subject"))
        errors.extend(validate_reference(self._resource, profile_name, "subject", ["Patient"]))
        errors.extend(validate_choice_required(self._resource, profile_name, ["effectiveDateTime","effectivePeriod"]))
        errors.extend(validate_reference(self._resource, profile_name, "hasMember", ["MolecularSequence","QuestionnaireResponse","Observation"]))
        errors.extend(validate_reference(self._resource, profile_name, "derivedFrom", ["DocumentReference","ImagingStudy","Media","MolecularSequence","QuestionnaireResponse","Observation"]))
        errors.extend(validate_reference(self._resource, profile_name, "performer", ["PractitionerRole","USCoreCareTeam","USCoreOrganizationProfile","Patient","USCorePractitionerProfile","USCoreRelatedPersonProfile"]))
        errors.extend(validate_excluded(self._resource, profile_name, "valueCodeableConcept"))
        errors.extend(validate_excluded(self._resource, profile_name, "valueString"))
        errors.extend(validate_excluded(self._resource, profile_name, "valueBoolean"))
        errors.extend(validate_excluded(self._resource, profile_name, "valueInteger"))
        errors.extend(validate_excluded(self._resource, profile_name, "valueRange"))
        errors.extend(validate_excluded(self._resource, profile_name, "valueRatio"))
        errors.extend(validate_excluded(self._resource, profile_name, "valueSampledData"))
        errors.extend(validate_excluded(self._resource, profile_name, "valueTime"))
        errors.extend(validate_excluded(self._resource, profile_name, "valueDateTime"))
        errors.extend(validate_excluded(self._resource, profile_name, "valuePeriod"))
        warnings.extend(validate_enum(self._resource, profile_name, "category", ["social-history","vital-signs","imaging","laboratory","procedure","survey","exam","therapy","activity"]))
        warnings.extend(validate_enum(self._resource, profile_name, "code", ["2708-6","29463-7","3140-1","3150-0","3151-8","39156-5","59408-5","59575-1","59576-9","77606-2","8287-5","8289-1","8302-2","8306-3","8310-5","8462-4","8478-0","8480-6","8867-4","9279-1","9843-4"]))
        warnings.extend(validate_enum(self._resource, profile_name, "dataAbsentReason", ["unknown","asked-unknown","temp-unknown","not-asked","asked-declined","masked","not-applicable","unsupported","as-text","error","not-a-number","negative-infinity","positive-infinity","not-performed","not-permitted"]))
        warnings.extend(validate_must_support(self._resource, profile_name, "dataAbsentReason"))
        warnings.extend(validate_must_support(self._resource, profile_name, "performer"))
        return {"errors": errors, "warnings": warnings}

