# WARNING: This file is autogenerated by @atomic-ehr/codegen.
# GitHub: https://github.com/atomic-ehr/codegen
# Any manual changes made to this file may be overwritten.

from __future__ import annotations

from typing import Any, Literal, cast, overload

from fhir_types.hl7_fhir_r4_core.patient import Patient
from fhir_types.hl7_fhir_r4_core.base import Extension
from fhir_types.hl7_fhir_r4_core.base import Coding, HumanName, Identifier
from .extension_uscore_ethnicity_extension import UscoreEthnicityExtension
from .extension_uscore_individual_sex_extension import UscoreIndividualSexExtension
from .extension_uscore_interpreter_needed_extension import UscoreInterpreterNeededExtension
from .extension_uscore_race_extension import UscoreRaceExtension
from .extension_uscore_tribal_affiliation_extension import UscoreTribalAffiliationExtension
from fhir_types.profile_helpers import (
    _get_key, build_resource, ensure_profile, extract_complex_extension, get_extension_value, is_extension, \
    is_record, push_extension, validate_must_support, validate_required
)


class UscorePatientProfile:
    """The US Core Patient Profile inherits from the FHIR [Patient](https://hl7.org/fhir/R4/patient.html) resource; refer to it for scope and usage definitions. This profile meets the requirements of the [U.S. Core Data for Interoperability (USCDI)](https://www.healthit.gov/isp/united-states-core-data-interoperability-uscdi) *Patient Demographics/Information* Data Class. It sets minimum expectations for the Patient resource to record, search, and fetch basic demographics and other administrative information about an individual patient. It specifies which core elements, extensions, vocabularies, and value sets **SHALL** be present and constrains how the elements are used. Providing the floor for standards development for specific use cases promotes interoperability and adoption.

    CanonicalURL: http://hl7.org/fhir/us/core/StructureDefinition/us-core-patient
    """

    canonical_url: str = "http://hl7.org/fhir/us/core/StructureDefinition/us-core-patient"

    def __init__(self, resource: Patient) -> None:
        self._resource = resource

    @classmethod
    def from_resource(cls, resource: Patient) -> "UscorePatientProfile":
        meta = getattr(resource, "meta", None)
        profiles = getattr(meta, "profile", None) if meta is not None else None
        if profiles is None or cls.canonical_url not in profiles:
            raise ValueError(f"UscorePatientProfile: meta.profile must include {cls.canonical_url}")
        profile = cls(resource)
        result = profile.validate()
        if result["errors"]:
            raise ValueError("; ".join(result["errors"]))
        return profile

    @classmethod
    def apply(cls, resource: Patient) -> "UscorePatientProfile":
        ensure_profile(resource, cls.canonical_url)
        return cls(resource)

    @classmethod
    def create_resource(cls, *, identifier: list[Identifier], name: list[HumanName]) -> Patient:
        return build_resource(
            Patient,
            resourceType="Patient",
            identifier=identifier,
            name=name,
            meta={"profile": [cls.canonical_url]},
        )

    @classmethod
    def create(cls, *, identifier: list[Identifier], name: list[HumanName]) -> "UscorePatientProfile":
        return cls.apply(cls.create_resource(identifier=identifier, name=name))

    def to_resource(self) -> Patient:
        return self._resource

    def get_identifier(self) -> list[Identifier] | None:
        return cast('list[Identifier] | None', getattr(self._resource, "identifier", None))

    def set_identifier(self, value: list[Identifier]) -> "UscorePatientProfile":
        setattr(self._resource, "identifier", value)
        return self

    def get_name(self) -> list[HumanName] | None:
        return cast('list[HumanName] | None', getattr(self._resource, "name", None))

    def set_name(self, value: list[HumanName]) -> "UscorePatientProfile":
        setattr(self._resource, "name", value)
        return self

    @overload
    def get_race(self) -> dict[str, Any] | None: ...
    @overload
    def get_race(self, mode: Literal["raw"]) -> Extension | None: ...
    @overload
    def get_race(self, mode: Literal["profile"]) -> UscoreRaceExtension | None: ...
    def get_race(self, mode: Literal["raw", "profile"] | None = None) -> dict[str, Any] | Extension | UscoreRaceExtension | None:
        exts = getattr(self._resource, "extension", None) or []
        ext = next((e for e in exts if is_extension(e, "http://hl7.org/fhir/us/core/StructureDefinition/us-core-race")), None)
        if ext is None:
            return None
        ext_obj = ext if not isinstance(ext, dict) else Extension(**ext)
        if mode == "raw":
            return ext_obj
        if mode == "profile":
            return UscoreRaceExtension.apply(ext_obj)
        config = [{"name": "ombCategory", "valueField": "valueCoding", "isArray": False}, {"name": "detailed", "valueField": "valueCoding", "isArray": True}, {"name": "text", "valueField": "valueString", "isArray": False}]
        return extract_complex_extension(ext, config)

    def set_race(self, value: "UscoreRaceExtension | Extension | dict[str, Any]") -> "UscorePatientProfile":
        if isinstance(value, UscoreRaceExtension):
            push_extension(self._resource, value.to_resource())
        elif is_extension(value):
            if _get_key(value, "url") != "http://hl7.org/fhir/us/core/StructureDefinition/us-core-race":
                raise ValueError(f"Expected extension url 'http://hl7.org/fhir/us/core/StructureDefinition/us-core-race', got {_get_key(value, 'url')!r}")
            push_extension(self._resource, value)
        else:
            assert is_record(value)
            sub_extensions = []
            if value.get("ombCategory") is not None:
                sub_extensions.append({"url": "ombCategory", "valueCoding": value["ombCategory"]})
            for item in value.get("detailed", []):
                sub_extensions.append({"url": "detailed", "valueCoding": item})
            if value.get("text") is not None:
                sub_extensions.append({"url": "text", "valueString": value["text"]})
            push_extension(self._resource, Extension(url="http://hl7.org/fhir/us/core/StructureDefinition/us-core-race", extension=sub_extensions))
        return self

    @overload
    def get_ethnicity(self) -> dict[str, Any] | None: ...
    @overload
    def get_ethnicity(self, mode: Literal["raw"]) -> Extension | None: ...
    @overload
    def get_ethnicity(self, mode: Literal["profile"]) -> UscoreEthnicityExtension | None: ...
    def get_ethnicity(self, mode: Literal["raw", "profile"] | None = None) -> dict[str, Any] | Extension | UscoreEthnicityExtension | None:
        exts = getattr(self._resource, "extension", None) or []
        ext = next((e for e in exts if is_extension(e, "http://hl7.org/fhir/us/core/StructureDefinition/us-core-ethnicity")), None)
        if ext is None:
            return None
        ext_obj = ext if not isinstance(ext, dict) else Extension(**ext)
        if mode == "raw":
            return ext_obj
        if mode == "profile":
            return UscoreEthnicityExtension.apply(ext_obj)
        config = [{"name": "ombCategory", "valueField": "valueCoding", "isArray": False}, {"name": "detailed", "valueField": "valueCoding", "isArray": True}, {"name": "text", "valueField": "valueString", "isArray": False}]
        return extract_complex_extension(ext, config)

    def set_ethnicity(self, value: "UscoreEthnicityExtension | Extension | dict[str, Any]") -> "UscorePatientProfile":
        if isinstance(value, UscoreEthnicityExtension):
            push_extension(self._resource, value.to_resource())
        elif is_extension(value):
            if _get_key(value, "url") != "http://hl7.org/fhir/us/core/StructureDefinition/us-core-ethnicity":
                raise ValueError(f"Expected extension url 'http://hl7.org/fhir/us/core/StructureDefinition/us-core-ethnicity', got {_get_key(value, 'url')!r}")
            push_extension(self._resource, value)
        else:
            assert is_record(value)
            sub_extensions = []
            if value.get("ombCategory") is not None:
                sub_extensions.append({"url": "ombCategory", "valueCoding": value["ombCategory"]})
            for item in value.get("detailed", []):
                sub_extensions.append({"url": "detailed", "valueCoding": item})
            if value.get("text") is not None:
                sub_extensions.append({"url": "text", "valueString": value["text"]})
            push_extension(self._resource, Extension(url="http://hl7.org/fhir/us/core/StructureDefinition/us-core-ethnicity", extension=sub_extensions))
        return self

    @overload
    def get_tribal_affiliation(self) -> dict[str, Any] | None: ...
    @overload
    def get_tribal_affiliation(self, mode: Literal["raw"]) -> Extension | None: ...
    @overload
    def get_tribal_affiliation(self, mode: Literal["profile"]) -> UscoreTribalAffiliationExtension | None: ...
    def get_tribal_affiliation(self, mode: Literal["raw", "profile"] | None = None) -> dict[str, Any] | Extension | UscoreTribalAffiliationExtension | None:
        exts = getattr(self._resource, "extension", None) or []
        ext = next((e for e in exts if is_extension(e, "http://hl7.org/fhir/us/core/StructureDefinition/us-core-tribal-affiliation")), None)
        if ext is None:
            return None
        ext_obj = ext if not isinstance(ext, dict) else Extension(**ext)
        if mode == "raw":
            return ext_obj
        if mode == "profile":
            return UscoreTribalAffiliationExtension.apply(ext_obj)
        config = [{"name": "tribalAffiliation", "valueField": "valueCodeableConcept", "isArray": False}, {"name": "isEnrolled", "valueField": "valueBoolean", "isArray": False}]
        return extract_complex_extension(ext, config)

    def set_tribal_affiliation(self, value: "UscoreTribalAffiliationExtension | Extension | dict[str, Any]") -> "UscorePatientProfile":
        if isinstance(value, UscoreTribalAffiliationExtension):
            push_extension(self._resource, value.to_resource())
        elif is_extension(value):
            if _get_key(value, "url") != "http://hl7.org/fhir/us/core/StructureDefinition/us-core-tribal-affiliation":
                raise ValueError(f"Expected extension url 'http://hl7.org/fhir/us/core/StructureDefinition/us-core-tribal-affiliation', got {_get_key(value, 'url')!r}")
            push_extension(self._resource, value)
        else:
            assert is_record(value)
            sub_extensions = []
            if value.get("tribalAffiliation") is not None:
                sub_extensions.append({"url": "tribalAffiliation", "valueCodeableConcept": value["tribalAffiliation"]})
            if value.get("isEnrolled") is not None:
                sub_extensions.append({"url": "isEnrolled", "valueBoolean": value["isEnrolled"]})
            push_extension(self._resource, Extension(url="http://hl7.org/fhir/us/core/StructureDefinition/us-core-tribal-affiliation", extension=sub_extensions))
        return self

    @overload
    def get_sex(self) -> Coding | None: ...
    @overload
    def get_sex(self, mode: Literal["raw"]) -> Extension | None: ...
    @overload
    def get_sex(self, mode: Literal["profile"]) -> UscoreIndividualSexExtension | None: ...
    def get_sex(self, mode: Literal["raw", "profile"] | None = None) -> Coding | Extension | UscoreIndividualSexExtension | None:
        exts = getattr(self._resource, "extension", None) or []
        ext = next((e for e in exts if is_extension(e, "http://hl7.org/fhir/us/core/StructureDefinition/us-core-individual-sex")), None)
        if ext is None:
            return None
        ext_obj = ext if not isinstance(ext, dict) else Extension(**ext)
        if mode == "raw":
            return ext_obj
        if mode == "profile":
            return UscoreIndividualSexExtension.apply(ext_obj)
        return cast('Coding | None', get_extension_value(ext, "valueCoding"))

    def set_sex(self, value: "UscoreIndividualSexExtension | Extension | Coding") -> "UscorePatientProfile":
        if isinstance(value, UscoreIndividualSexExtension):
            push_extension(self._resource, value.to_resource())
        elif is_extension(value):
            if _get_key(value, "url") != "http://hl7.org/fhir/us/core/StructureDefinition/us-core-individual-sex":
                raise ValueError(f"Expected extension url 'http://hl7.org/fhir/us/core/StructureDefinition/us-core-individual-sex', got {_get_key(value, 'url')!r}")
            push_extension(self._resource, value)
        else:
            assert not isinstance(value, Extension)
            push_extension(self._resource, Extension(url="http://hl7.org/fhir/us/core/StructureDefinition/us-core-individual-sex", valueCoding=value))
        return self

    @overload
    def get_interpreter_required(self) -> Coding | None: ...
    @overload
    def get_interpreter_required(self, mode: Literal["raw"]) -> Extension | None: ...
    @overload
    def get_interpreter_required(self, mode: Literal["profile"]) -> UscoreInterpreterNeededExtension | None: ...
    def get_interpreter_required(self, mode: Literal["raw", "profile"] | None = None) -> Coding | Extension | UscoreInterpreterNeededExtension | None:
        exts = getattr(self._resource, "extension", None) or []
        ext = next((e for e in exts if is_extension(e, "http://hl7.org/fhir/us/core/StructureDefinition/us-core-interpreter-needed")), None)
        if ext is None:
            return None
        ext_obj = ext if not isinstance(ext, dict) else Extension(**ext)
        if mode == "raw":
            return ext_obj
        if mode == "profile":
            return UscoreInterpreterNeededExtension.apply(ext_obj)
        return cast('Coding | None', get_extension_value(ext, "valueCoding"))

    def set_interpreter_required(self, value: "UscoreInterpreterNeededExtension | Extension | Coding") -> "UscorePatientProfile":
        if isinstance(value, UscoreInterpreterNeededExtension):
            push_extension(self._resource, value.to_resource())
        elif is_extension(value):
            if _get_key(value, "url") != "http://hl7.org/fhir/us/core/StructureDefinition/us-core-interpreter-needed":
                raise ValueError(f"Expected extension url 'http://hl7.org/fhir/us/core/StructureDefinition/us-core-interpreter-needed', got {_get_key(value, 'url')!r}")
            push_extension(self._resource, value)
        else:
            assert not isinstance(value, Extension)
            push_extension(self._resource, Extension(url="http://hl7.org/fhir/us/core/StructureDefinition/us-core-interpreter-needed", valueCoding=value))
        return self

    def validate(self) -> dict[str, list[str]]:
        profile_name = "UscorePatientProfile"
        errors: list[str] = []
        warnings: list[str] = []
        errors.extend(validate_required(self._resource, profile_name, "identifier"))
        errors.extend(validate_required(self._resource, profile_name, "name"))
        warnings.extend(validate_must_support(self._resource, profile_name, "birthDate"))
        warnings.extend(validate_must_support(self._resource, profile_name, "address"))
        return {"errors": errors, "warnings": warnings}

