FROM node:18 AS builder

ARG VITE_AIDBOX_URL
ARG VITE_SMARTAPP_SUBSCRIPTIONS_API

# Set environment variables during the build process
ENV VITE_AIDBOX_URL=$VITE_AIDBOX_URL
ENV VITE_SMARTAPP_SUBSCRIPTIONS_API=$VITE_SMARTAPP_SUBSCRIPTIONS_API

WORKDIR /app

COPY ./front/package.json ./front/package-lock.json ./
RUN npm install

COPY ./front/ ./

RUN npm run build

CMD ["npm", "run", "preview"]