volumes:
  postgres_data: {}
services:
  postgres:
    image: postgres:17
    volumes:
    - postgres_data:/var/lib/postgresql/data:delegated
    command:
    - postgres
    - -c
    - shared_preload_libraries=pg_stat_statements
    environment:
      POSTGRES_USER: aidbox
      POSTGRES_PORT: '5432'
      POSTGRES_DB: aidbox
      POSTGRES_PASSWORD: aidbox
  aidbox:
    image: healthsamurai/aidboxone:edge
    # image: nginx:latest
    pull_policy: always
    depends_on:
    - postgres
    ports:
    - 8080:8080
    volumes:
    - ./init-bundle.json.tpl:/tmp/init-bundle.json.tpl
    entrypoint:
      - /bin/sh
      - -c
      - |
        VARS=$$(printf '$${%s} ' $$(env | cut -d= -f1))
        envsubst "$$VARS" < /tmp/init-bundle.json.tpl > /tmp/init-bundle.json
        /aidbox.sh
    environment:
      BOX_INIT_BUNDLE: file:///tmp/init-bundle.json
      INIT_BUNDLE_CLIENT_ID: client-id
      INIT_BUNDLE_CLIENT_SECRET: client-secret
      BOX_ADMIN_PASSWORD: t_LRDXTuel
      BOX_BOOTSTRAP_FHIR_PACKAGES: hl7.fhir.r4.core#4.0.1
      BOX_COMPATIBILITY_VALIDATION_JSON__SCHEMA_REGEX: '#{:fhir-datetime}'
      BOX_DB_DATABASE: aidbox
      BOX_DB_HOST: postgres
      BOX_DB_PASSWORD: aidbox
      BOX_DB_PORT: '5432'
      BOX_DB_USER: aidbox
      BOX_FHIR_COMPLIANT_MODE: true
      BOX_FHIR_CORRECT_AIDBOX_FORMAT: true
      BOX_FHIR_CREATEDAT_URL: https://aidbox.app/ex/createdAt
      BOX_FHIR_SCHEMA_VALIDATION: true
      BOX_FHIR_SEARCH_AUTHORIZE_INLINE_REQUESTS: true
      BOX_FHIR_SEARCH_CHAIN_SUBSELECT: true
      BOX_FHIR_SEARCH_COMPARISONS: true
      BOX_FHIR_TERMINOLOGY_SERVICE_BASE_URL: https://tx.health-samurai.io/fhir
      BOX_ROOT_CLIENT_SECRET: L_N3G5oUT0
      BOX_SEARCH_INCLUDE_CONFORMANT: true
      BOX_SECURITY_AUDIT_LOG_ENABLED: true
      BOX_SECURITY_DEV_MODE: true
      BOX_SETTINGS_MODE: read-write
      BOX_WEB_BASE_URL: http://localhost:8080
      BOX_WEB_PORT: 8080
    healthcheck:
      test: curl -f http://localhost:8080/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 90
      start_period: 30s
