# WARNING: This file is autogenerated by @atomic-ehr/codegen.
# GitHub: https://github.com/atomic-ehr/codegen
# Any manual changes made to this file may be overwritten.

from __future__ import annotations

from typing import Any, Literal, cast

from fhir_types.hl7_fhir_r4_core.bundle import Bundle
from fhir_types.hl7_fhir_r4_core.bundle import BundleEntry
from fhir_types.hl7_fhir_r4_core.organization import Organization
from fhir_types.hl7_fhir_r4_core.patient import Patient
from fhir_types.hl7_fhir_r4_core.resource import Resource
from fhir_types.profile_helpers import (
    build_resource, ensure_profile, get_array_slice, get_array_slices, set_array_slice, set_array_slices, \
    validate_slice_cardinality
)


class ExampleTypedBundleProfile:
    """A Bundle profile that slices entry[] by resource type — used to test type discriminator support.

    CanonicalURL: http://example.org/fhir/StructureDefinition/ExampleTypedBundle
    """

    canonical_url: str = "http://example.org/fhir/StructureDefinition/ExampleTypedBundle"

    _patient_entry_slice_match: dict[str, Any] = {"resource":{"resourceType":"Patient"}}
    _organization_entry_slice_match: dict[str, Any] = {"resource":{"resourceType":"Organization"}}

    def __init__(self, resource: Bundle[Patient | Organization, Resource]) -> None:
        self._resource = resource

    @classmethod
    def from_resource(cls, resource: Bundle[Patient | Organization, Resource]) -> "ExampleTypedBundleProfile":
        meta = getattr(resource, "meta", None)
        profiles = getattr(meta, "profile", None) if meta is not None else None
        if profiles is None or cls.canonical_url not in profiles:
            raise ValueError(f"ExampleTypedBundleProfile: meta.profile must include {cls.canonical_url}")
        profile = cls(resource)
        result = profile.validate()
        if result["errors"]:
            raise ValueError("; ".join(result["errors"]))
        return profile

    @classmethod
    def apply(cls, resource: Bundle[Patient | Organization, Resource]) -> "ExampleTypedBundleProfile":
        ensure_profile(resource, cls.canonical_url)
        return cls(resource)

    @classmethod
    def create_resource(cls, *, type: Literal["document", "message", "transaction", "transaction-response", "batch", "batch-response", "history", "searchset", "collection"]) -> Bundle[Patient | Organization, Resource]:
        return build_resource(
            Bundle,
            resourceType="Bundle",
            type=type,
            meta={"profile": [cls.canonical_url]},
        )

    @classmethod
    def create(cls, *, type: Literal["document", "message", "transaction", "transaction-response", "batch", "batch-response", "history", "searchset", "collection"]) -> "ExampleTypedBundleProfile":
        return cls.apply(cls.create_resource(type=type))

    def to_resource(self) -> Bundle[Patient | Organization, Resource]:
        return self._resource

    def get_type(self) -> Literal["document", "message", "transaction", "transaction-response", "batch", "batch-response", "history", "searchset", "collection"] | None:
        return cast('Literal["document", "message", "transaction", "transaction-response", "batch", "batch-response", "history", "searchset", "collection"] | None', getattr(self._resource, "type", None))

    def set_type(self, value: Literal["document", "message", "transaction", "transaction-response", "batch", "batch-response", "history", "searchset", "collection"]) -> "ExampleTypedBundleProfile":
        setattr(self._resource, "type", value)
        return self

    def get_patient_entry(self, mode: str | None = None) -> BundleEntry[Patient] | None:
        match = self.__class__._patient_entry_slice_match
        return cast('BundleEntry[Patient] | None', get_array_slice(getattr(self._resource, "entry", None), match))

    def get_organization_entry(self, mode: str | None = None) -> list[BundleEntry[Organization]] | None:
        match = self.__class__._organization_entry_slice_match
        result = get_array_slices(getattr(self._resource, "entry", None), match)
        return cast('list[BundleEntry[Organization]] | None', result or None)

    def set_patient_entry(self, value: BundleEntry[Patient] | None = None) -> "ExampleTypedBundleProfile":
        match = self.__class__._patient_entry_slice_match
        items = getattr(self._resource, "entry", None) or []
        set_array_slice(items, match, value)
        setattr(self._resource, "entry", items)
        return self

    def set_organization_entry(self, values: list[BundleEntry[Organization]]) -> "ExampleTypedBundleProfile":
        match = self.__class__._organization_entry_slice_match
        items = list(getattr(self._resource, "entry", None) or [])
        set_array_slices(items, match, values)
        setattr(self._resource, "entry", items)
        return self

    def validate(self) -> dict[str, list[str]]:
        profile_name = "ExampleTypedBundleProfile"
        errors: list[str] = []
        warnings: list[str] = []
        errors.extend(validate_slice_cardinality(self._resource, profile_name, "entry", {"resource":{"resourceType":"Patient"}}, "PatientEntry", 1, 1))
        return {"errors": errors, "warnings": warnings}

