name: IPS CL app image

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-ips-ig-cl

on:
  push:
    branches:
      - main
    paths:
      - 'ips_ig_cl/**' # Only trigger if files within ips_ig change
  workflow_dispatch:

jobs:
  build-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          push: true
          no-cache: true
          platforms: linux/amd64,linux/arm64
          context: ./ips_ig_cl
          file: ./ips_ig_cl/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}